/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_trans CASADI_PREFIX(trans)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_trans(const casadi_real* x, const casadi_int* sp_x, casadi_real* y,
    const casadi_int* sp_y, casadi_int* tmp) {
  casadi_int ncol_x, nnz_x, ncol_y, k;
  const casadi_int* row_x, *colind_y;
  ncol_x = sp_x[1];
  nnz_x = sp_x[2 + ncol_x];
  row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2;
  for (k=0; k<ncol_y; ++k) tmp[k] = colind_y[k];
  for (k=0; k<nnz_x; ++k) {
    y[tmp[row_x[k]]++] = x[k];
  }
}

static const casadi_int casadi_s0[2] = {0, 78};
static const casadi_int casadi_s1[1] = {3};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[2] = {0, 76};
static const casadi_int casadi_s5[1] = {2};
static const casadi_int casadi_s6[4] = {0, 3, 8, 16};
static const casadi_int casadi_s7[3] = {10, 13, 18};
static const casadi_int casadi_s8[6] = {1, 4, 6, 11, 14, 19};
static const casadi_int casadi_s9[6] = {2, 5, 7, 12, 15, 20};
static const casadi_int casadi_s10[32] = {8, 8, 0, 3, 6, 8, 13, 16, 21, 21, 21, 2, 6, 7, 2, 6, 7, 6, 7, 3, 4, 5, 6, 7, 5, 6, 7, 3, 4, 5, 6, 7};
static const casadi_int casadi_s11[32] = {8, 8, 0, 0, 0, 2, 4, 6, 9, 15, 21, 0, 1, 3, 5, 3, 5, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s12[19] = {8, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s13[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s14[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s15[3] = {0, 0, 0};
static const casadi_int casadi_s16[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s17[3] = {8, 0, 0};

static const casadi_real casadi_c0[78] = {0., 0., 0., 0., 1.2500000000000000e+00, 1.8750000000000000e+00, 2.5000000000000000e+00, 3.1250000000000000e+00, 3.7500000000000000e+00, 4.3750000000000000e+00, 5., 5.2453380000000003e+00, 5.4906769999999998e+00, 5.7360150000000001e+00, 5.9813530000000004e+00, 6.2266919999999999e+00, 6.4720300000000002e+00, 6.7173689999999997e+00, 6.9627070000000000e+00, 7.2080450000000003e+00, 7.4533839999999998e+00, 7.6987220000000001e+00, 7.9440600000000003e+00, 8.1893989999999999e+00, 8.4347370000000002e+00, 8.6800759999999997e+00, 8.9254140000000000e+00, 9.5504140000000000e+00, 1.0175414000000000e+01, 1.0800414000000000e+01, 1.1425414000000000e+01, 1.2050414000000000e+01, 1.2675414000000000e+01, 1.3300414000000000e+01, 1.3925414000000000e+01, 1.4550414000000000e+01, 1.5175414000000000e+01, 1.5800414000000000e+01, 1.6425414000000000e+01, 1.7050414000000000e+01, 1.7675414000000000e+01, 1.8300414000000000e+01, 1.8925414000000000e+01, 1.9550414000000000e+01, 2.0175414000000000e+01, 2.0800414000000000e+01, 2.1425414000000000e+01, 2.2050414000000000e+01, 2.2675414000000000e+01, 2.3300414000000000e+01, 2.3925414000000000e+01, 2.4550414000000000e+01, 2.5175414000000000e+01, 2.5800414000000000e+01, 2.6425414000000000e+01, 2.6670414000000001e+01, 2.6915413999999998e+01, 2.7160413999999999e+01, 2.7405414000000000e+01, 2.7650414000000001e+01, 2.7895413999999999e+01, 2.8140414000000000e+01, 2.8385414000000001e+01, 2.8630413999999998e+01, 2.8875413999999999e+01, 2.9120414000000000e+01, 2.9365414000000001e+01, 2.9610413999999999e+01, 2.9855414000000000e+01, 3.0100414000000001e+01, 3.0345414000000002e+01, 3.0970414000000002e+01, 3.1595414000000002e+01, 3.2220413999999998e+01, 5.2845413999999998e+01, 5.2845413999999998e+01, 5.2845413999999998e+01, 5.2845413999999998e+01};
static const casadi_real casadi_c1[74] = {6.8813407938829532e-16, 2.7952717678989550e-04, -5.5905435356960981e-04, 8.3858153034713863e-04, -3.1446807388000359e-03, 1.1740141424876104e-02, -4.3815884960732868e-02, 1.6352339841808286e-01, -4.5359350821290706e-01, -3.9131804904117917e-01, -4.0232631547442688e-01, -3.9937666569630953e-01, -4.0016702682176675e-01, -3.9995523005566758e-01, -4.0001205348193164e-01, -3.9999655615701829e-01, -4.0000172191802169e-01, -3.9999655615690144e-01, -4.0001205348241714e-01, -3.9995523013101464e-01, -4.0016702635850404e-01, -3.9937666275749539e-01, -4.0232631527716256e-01, -3.9131804876141985e-01, -4.5359351035251200e-01, 1.6352342149695412e-01, -4.3815968733685762e-02, 1.1740453437781091e-02, -3.1458450174377105e-03, 8.4292663197142617e-04, -2.2586151044641593e-04, 6.0519409811394083e-05, -1.6216128798159694e-05, 4.3451053820086308e-06, -1.1642927284032971e-06, 3.1206552974408207e-07, -8.3969392458416277e-08, 2.3812047337317961e-08, -1.1278806530247471e-08, 2.1303185585341266e-08, -7.3933936930160481e-08, 2.7443256259875820e-07, -1.0237963139267120e-06, 3.8207526958601992e-06, -1.4259214475925762e-05, 5.3216105215366090e-05, -1.9860520639439851e-04, 7.4120472037035210e-04, -2.7662136750947696e-03, 1.0323649980013765e-02, -3.8528386244965226e-02, 1.4378989499985131e-01, -3.9873251976690743e-01, 5.2927500857770671e-01, 3.6536086144625446e-01, 4.0928154563726488e-01, 3.9751295600469227e-01, 4.0066663034396749e-01, 3.9982052261942558e-01, 4.0005127917834959e-01, 3.9997436066715442e-01, 4.0005127815305902e-01, 3.9982052672058915e-01, 4.0066661496459344e-01, 3.9751301342104689e-01, 4.0928133135119515e-01, 3.6536166117419772e-01, 5.2927202395199902e-01, -3.9871407909783851e-01, 1.4359570263215679e-01, -3.7824104636547326e-02, 4.9329880178682889e-01, -7.8927808285890917e+00, -1.5266455039322114e-19};
static const casadi_real casadi_c2[76] = {0., 0., 0., 1.2500000000000000e+00, 1.8750000000000000e+00, 2.5000000000000000e+00, 3.1250000000000000e+00, 3.7500000000000000e+00, 4.3750000000000000e+00, 5., 5.2453380000000003e+00, 5.4906769999999998e+00, 5.7360150000000001e+00, 5.9813530000000004e+00, 6.2266919999999999e+00, 6.4720300000000002e+00, 6.7173689999999997e+00, 6.9627070000000000e+00, 7.2080450000000003e+00, 7.4533839999999998e+00, 7.6987220000000001e+00, 7.9440600000000003e+00, 8.1893989999999999e+00, 8.4347370000000002e+00, 8.6800759999999997e+00, 8.9254140000000000e+00, 9.5504140000000000e+00, 1.0175414000000000e+01, 1.0800414000000000e+01, 1.1425414000000000e+01, 1.2050414000000000e+01, 1.2675414000000000e+01, 1.3300414000000000e+01, 1.3925414000000000e+01, 1.4550414000000000e+01, 1.5175414000000000e+01, 1.5800414000000000e+01, 1.6425414000000000e+01, 1.7050414000000000e+01, 1.7675414000000000e+01, 1.8300414000000000e+01, 1.8925414000000000e+01, 1.9550414000000000e+01, 2.0175414000000000e+01, 2.0800414000000000e+01, 2.1425414000000000e+01, 2.2050414000000000e+01, 2.2675414000000000e+01, 2.3300414000000000e+01, 2.3925414000000000e+01, 2.4550414000000000e+01, 2.5175414000000000e+01, 2.5800414000000000e+01, 2.6425414000000000e+01, 2.6670414000000001e+01, 2.6915413999999998e+01, 2.7160413999999999e+01, 2.7405414000000000e+01, 2.7650414000000001e+01, 2.7895413999999999e+01, 2.8140414000000000e+01, 2.8385414000000001e+01, 2.8630413999999998e+01, 2.8875413999999999e+01, 2.9120414000000000e+01, 2.9365414000000001e+01, 2.9610413999999999e+01, 2.9855414000000000e+01, 3.0100414000000001e+01, 3.0345414000000002e+01, 3.0970414000000002e+01, 3.1595414000000002e+01, 3.2220413999999998e+01, 5.2845413999999998e+01, 5.2845413999999998e+01, 5.2845413999999998e+01};
static const casadi_real casadi_c3[73] = {6.7086522429409782e-04, -1.3417304485752086e-03, 1.6771630607000983e-03, -6.3732196306354799e-03, 2.3815715461881826e-02, -8.8889642216974360e-02, 3.3174285340610521e-01, -1.2380817714075141e+00, 1.6745561440738099e-01, -4.4869736757733272e-02, 1.2022783957327051e-02, -3.2215150185412500e-03, 8.6328444161809048e-04, -2.3161219157227732e-04, 6.3167156566170524e-05, -2.1055661922823235e-05, 2.1055662399284442e-05, -6.3167159021253929e-05, 2.3161220112019099e-04, -8.6328224624246776e-04, 3.2215251088984873e-03, -1.2022778796930393e-02, 4.4869737093983335e-02, -1.6745562091293142e-01, 1.2380818220017134e+00, -3.3174302436902381e-01, 8.8890275474346955e-02, -2.3818077528350082e-02, 6.3820346390546191e-03, -1.7100610278685474e-03, 4.5820947241249606e-04, -1.2277686177528607e-04, 3.2897974688269318e-05, -8.8150369766590846e-06, 2.3621732130358068e-06, -6.3365587552399733e-07, 1.7245030367317478e-07, -5.6145366188104691e-08, 5.2131187384941987e-08, -1.5237939602480279e-07, 5.5738639924626991e-07, -2.0771662024407525e-06, 7.7512784156590585e-06, -2.8927947474857539e-05, 1.0796051150606697e-04, -4.0291409857562340e-04, 1.5036958828236011e-03, -5.6118694327441949e-03, 2.0943781848173658e-02, -7.8163257959966398e-02, 2.9170924999170650e-01, -1.0886737420068731e+00, 2.4968812421828219e+00, -6.6903733523041786e-01, 1.7926809873881810e-01, -4.8035059724785834e-02, 1.2872140160306999e-02, -3.4535009164975107e-03, 9.4186350581234625e-04, -3.1395310691901873e-04, 3.1394892205954128e-04, -9.4184258150972321e-04, 3.4534214040990948e-03, -1.2871843034883821e-02, 4.8033950735299008e-02, -1.7926395990611205e-01, 6.6902188888898217e-01, -2.4968235956497828e+00, 1.0882470536387858e+00, -2.9027169162992716e-01, 7.2839712880920185e-02, -1.1839171242883655e+00, 1.1480408477947770e+00};

/* kapparef_s:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_kapparef_s:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c2,casadi_s4,casadi_s5,casadi_s2,casadi_c3,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z:(i0[8],i1[8],i2[2],i3[],i4[],i5[16])->(o0[8],o1[8x8,21nz],o2[8x8,8nz],o3[8x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+4, *rr, *ss;
  const casadi_int *cii;
  const casadi_real **arg1=arg+6, *cs;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, *w8=w+20, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24, *w25=w+44, *w26=w+52, *w27=w+73, *w32=w+77, *w35=w+81, *w36=w+83, *w37=w+85, *w38=w+88, *w39=w+91, *w40=w+97, *w41=w+103;
  /* #0: @0 = input[1][0] */
  w0 = arg[1] ? arg[1][0] : 0;
  /* #1: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #2: @2 = input[1][2] */
  w2 = arg[1] ? arg[1][2] : 0;
  /* #3: @3 = input[1][3] */
  w3 = arg[1] ? arg[1][3] : 0;
  /* #4: @4 = input[1][4] */
  w4 = arg[1] ? arg[1][4] : 0;
  /* #5: @5 = input[1][5] */
  w5 = arg[1] ? arg[1][5] : 0;
  /* #6: @6 = input[1][6] */
  w6 = arg[1] ? arg[1][6] : 0;
  /* #7: @7 = input[1][7] */
  w7 = arg[1] ? arg[1][7] : 0;
  /* #8: @8 = vertcat(@0, @1, @2, @3, @4, @5, @6, @7) */
  rr=w8;
  *rr++ = w0;
  *rr++ = w1;
  *rr++ = w2;
  *rr++ = w3;
  *rr++ = w4;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w7;
  /* #9: @0 = input[0][6] */
  w0 = arg[0] ? arg[0][6] : 0;
  /* #10: @1 = input[0][7] */
  w1 = arg[0] ? arg[0][7] : 0;
  /* #11: @2 = cos(@1) */
  w2 = cos( w1 );
  /* #12: @3 = (@0*@2) */
  w3  = (w0*w2);
  /* #13: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #14: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #15: @6 = (@3*@5) */
  w6  = (w3*w5);
  /* #16: @7 = sin(@4) */
  w7 = sin( w4 );
  /* #17: @9 = (@3*@7) */
  w9  = (w3*w7);
  /* #18: @10 = sin(@1) */
  w10 = sin( w1 );
  /* #19: @11 = (@0*@10) */
  w11  = (w0*w10);
  /* #20: @12 = 1.03 */
  w12 = 1.0300000000000000e+00;
  /* #21: @11 = (@11/@12) */
  w11 /= w12;
  /* #22: @12 = input[0][5] */
  w12 = arg[0] ? arg[0][5] : 0;
  /* #23: @13 = cos(@12) */
  w13 = cos( w12 );
  /* #24: @14 = (@3*@13) */
  w14  = (w3*w13);
  /* #25: @15 = 1 */
  w15 = 1.;
  /* #26: @16 = input[0][3] */
  w16 = arg[0] ? arg[0][3] : 0;
  /* #27: @17 = kapparef_s(@16) */
  arg1[0]=(&w16);
  res1[0]=(&w17);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #28: @18 = input[0][4] */
  w18 = arg[0] ? arg[0][4] : 0;
  /* #29: @19 = (@17*@18) */
  w19  = (w17*w18);
  /* #30: @15 = (@15-@19) */
  w15 -= w19;
  /* #31: @14 = (@14/@15) */
  w14 /= w15;
  /* #32: @19 = sin(@12) */
  w19 = sin( w12 );
  /* #33: @20 = (@3*@19) */
  w20  = (w3*w19);
  /* #34: @21 = kapparef_s(@16) */
  arg1[0]=(&w16);
  res1[0]=(&w21);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #35: @22 = (@21*@14) */
  w22  = (w21*w14);
  /* #36: @22 = (@11-@22) */
  w22  = (w11-w22);
  /* #37: @23 = input[2][0] */
  w23 = arg[2] ? arg[2][0] : 0;
  /* #38: @24 = input[2][1] */
  w24 = arg[2] ? arg[2][1] : 0;
  /* #39: @25 = vertcat(@6, @9, @11, @14, @20, @22, @23, @24) */
  rr=w25;
  *rr++ = w6;
  *rr++ = w9;
  *rr++ = w11;
  *rr++ = w14;
  *rr++ = w20;
  *rr++ = w22;
  *rr++ = w23;
  *rr++ = w24;
  /* #40: @8 = (@8-@25) */
  for (i=0, rr=w8, cs=w25; i<8; ++i) (*rr++) -= (*cs++);
  /* #41: output[0][0] = @8 */
  casadi_copy(w8, 8, res[0]);
  /* #42: @26 = zeros(8x8,21nz) */
  casadi_clear(w26, 21);
  /* #43: @6 = sin(@4) */
  w6 = sin( w4 );
  /* #44: @27 = ones(8x1,4nz) */
  casadi_fill(w27, 4, 1.);
  /* #45: {NULL, NULL, @9, @11, NULL, NULL, NULL, NULL} = vertsplit(@27) */
  w9 = w27[2];
  w11 = w27[3];
  /* #46: @6 = (@6*@9) */
  w6 *= w9;
  /* #47: @6 = (@3*@6) */
  w6  = (w3*w6);
  /* #48: @6 = (-@6) */
  w6 = (- w6 );
  /* #49: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #50: @4 = (@4*@9) */
  w4 *= w9;
  /* #51: @4 = (@3*@4) */
  w4  = (w3*w4);
  /* #52: @28 = 00 */
  /* #53: @9 = (@14/@15) */
  w9  = (w14/w15);
  /* #54: @29 = 00 */
  /* #55: @20 = fwd1_kapparef_s(@16, @29, @11) */
  arg1[0]=(&w16);
  arg1[1]=0;
  arg1[2]=(&w11);
  res1[0]=(&w20);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #56: @18 = (@18*@20) */
  w18 *= w20;
  /* #57: @18 = (@9*@18) */
  w18  = (w9*w18);
  /* #58: @29 = 00 */
  /* #59: @30 = 00 */
  /* #60: @20 = fwd1_kapparef_s(@16, @30, @11) */
  arg1[0]=(&w16);
  arg1[1]=0;
  arg1[2]=(&w11);
  res1[0]=(&w20);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #61: @14 = (@14*@20) */
  w14 *= w20;
  /* #62: @20 = (@21*@18) */
  w20  = (w21*w18);
  /* #63: @14 = (@14+@20) */
  w14 += w20;
  /* #64: @14 = (-@14) */
  w14 = (- w14 );
  /* #65: @30 = 00 */
  /* #66: @31 = 00 */
  /* #67: @27 = vertcat(@6, @4, @28, @18, @29, @14, @30, @31) */
  rr=w27;
  *rr++ = w6;
  *rr++ = w4;
  *rr++ = w18;
  *rr++ = w14;
  /* #68: @27 = (-@27) */
  for (i=0, rr=w27, cs=w27; i<4; ++i) *rr++ = (- *cs++ );
  /* #69: @32 = @27[:4] */
  for (rr=w32, ss=w27+0; ss!=w27+4; ss+=1) *rr++ = *ss;
  /* #70: (@26[0, 3, 8, 16] = @32) */
  for (cii=casadi_s6, rr=w26, ss=w32; cii!=casadi_s6+4; ++cii, ++ss) rr[*cii] = *ss;
  /* #71: @28 = 00 */
  /* #72: @29 = 00 */
  /* #73: @30 = 00 */
  /* #74: @6 = ones(8x1,1nz) */
  w6 = 1.;
  /* #75: {NULL, NULL, NULL, NULL, @4, NULL, NULL, NULL} = vertsplit(@6) */
  w4 = w6;
  /* #76: @17 = (@17*@4) */
  w17 *= w4;
  /* #77: @9 = (@9*@17) */
  w9 *= w17;
  /* #78: @31 = 00 */
  /* #79: @17 = (@21*@9) */
  w17  = (w21*w9);
  /* #80: @17 = (-@17) */
  w17 = (- w17 );
  /* #81: @33 = 00 */
  /* #82: @34 = 00 */
  /* #83: @35 = vertcat(@28, @29, @30, @9, @31, @17, @33, @34) */
  rr=w35;
  *rr++ = w9;
  *rr++ = w17;
  /* #84: @35 = (-@35) */
  for (i=0, rr=w35, cs=w35; i<2; ++i) *rr++ = (- *cs++ );
  /* #85: @36 = @35[:2] */
  for (rr=w36, ss=w35+0; ss!=w35+2; ss+=1) *rr++ = *ss;
  /* #86: (@26[9:25:8] = @36) */
  for (rr=w26+9, ss=w36; rr!=w26+25; rr+=8) *rr = *ss++;
  /* #87: @28 = 00 */
  /* #88: @29 = 00 */
  /* #89: @30 = 00 */
  /* #90: @9 = sin(@12) */
  w9 = sin( w12 );
  /* #91: @17 = ones(8x1,1nz) */
  w17 = 1.;
  /* #92: {NULL, NULL, NULL, NULL, NULL, @4, NULL, NULL} = vertsplit(@17) */
  w4 = w17;
  /* #93: @9 = (@9*@4) */
  w9 *= w4;
  /* #94: @9 = (@3*@9) */
  w9  = (w3*w9);
  /* #95: @9 = (@9/@15) */
  w9 /= w15;
  /* #96: @17 = (-@9) */
  w17 = (- w9 );
  /* #97: @12 = cos(@12) */
  w12 = cos( w12 );
  /* #98: @12 = (@12*@4) */
  w12 *= w4;
  /* #99: @3 = (@3*@12) */
  w3 *= w12;
  /* #100: @9 = (@21*@9) */
  w9  = (w21*w9);
  /* #101: @31 = 00 */
  /* #102: @33 = 00 */
  /* #103: @37 = vertcat(@28, @29, @30, @17, @3, @9, @31, @33) */
  rr=w37;
  *rr++ = w17;
  *rr++ = w3;
  *rr++ = w9;
  /* #104: @37 = (-@37) */
  for (i=0, rr=w37, cs=w37; i<3; ++i) *rr++ = (- *cs++ );
  /* #105: @38 = @37[:3] */
  for (rr=w38, ss=w37+0; ss!=w37+3; ss+=1) *rr++ = *ss;
  /* #106: (@26[10, 13, 18] = @38) */
  for (cii=casadi_s7, rr=w26, ss=w38; cii!=casadi_s7+3; ++cii, ++ss) rr[*cii] = *ss;
  /* #107: @17 = ones(8x1,1nz) */
  w17 = 1.;
  /* #108: {NULL, NULL, NULL, NULL, NULL, NULL, @3, NULL} = vertsplit(@17) */
  w3 = w17;
  /* #109: @2 = (@2*@3) */
  w2 *= w3;
  /* #110: @17 = (@5*@2) */
  w17  = (w5*w2);
  /* #111: @9 = (@7*@2) */
  w9  = (w7*w2);
  /* #112: @12 = 0.970874 */
  w12 = 9.7087378640776700e-01;
  /* #113: @10 = (@10*@3) */
  w10 *= w3;
  /* #114: @10 = (@12*@10) */
  w10  = (w12*w10);
  /* #115: @3 = (@13*@2) */
  w3  = (w13*w2);
  /* #116: @3 = (@3/@15) */
  w3 /= w15;
  /* #117: @2 = (@19*@2) */
  w2  = (w19*w2);
  /* #118: @4 = (@21*@3) */
  w4  = (w21*w3);
  /* #119: @4 = (@10-@4) */
  w4  = (w10-w4);
  /* #120: @28 = 00 */
  /* #121: @29 = 00 */
  /* #122: @39 = vertcat(@17, @9, @10, @3, @2, @4, @28, @29) */
  rr=w39;
  *rr++ = w17;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w3;
  *rr++ = w2;
  *rr++ = w4;
  /* #123: @39 = (-@39) */
  for (i=0, rr=w39, cs=w39; i<6; ++i) *rr++ = (- *cs++ );
  /* #124: @40 = @39[:6] */
  for (rr=w40, ss=w39+0; ss!=w39+6; ss+=1) *rr++ = *ss;
  /* #125: (@26[1, 4, 6, 11, 14, 19] = @40) */
  for (cii=casadi_s8, rr=w26, ss=w40; cii!=casadi_s8+6; ++cii, ++ss) rr[*cii] = *ss;
  /* #126: @17 = sin(@1) */
  w17 = sin( w1 );
  /* #127: @9 = ones(8x1,1nz) */
  w9 = 1.;
  /* #128: {NULL, NULL, NULL, NULL, NULL, NULL, NULL, @10} = vertsplit(@9) */
  w10 = w9;
  /* #129: @17 = (@17*@10) */
  w17 *= w10;
  /* #130: @17 = (@0*@17) */
  w17  = (w0*w17);
  /* #131: @5 = (@5*@17) */
  w5 *= w17;
  /* #132: @5 = (-@5) */
  w5 = (- w5 );
  /* #133: @7 = (@7*@17) */
  w7 *= w17;
  /* #134: @7 = (-@7) */
  w7 = (- w7 );
  /* #135: @1 = cos(@1) */
  w1 = cos( w1 );
  /* #136: @1 = (@1*@10) */
  w1 *= w10;
  /* #137: @0 = (@0*@1) */
  w0 *= w1;
  /* #138: @12 = (@12*@0) */
  w12 *= w0;
  /* #139: @13 = (@13*@17) */
  w13 *= w17;
  /* #140: @13 = (@13/@15) */
  w13 /= w15;
  /* #141: @15 = (-@13) */
  w15 = (- w13 );
  /* #142: @19 = (@19*@17) */
  w19 *= w17;
  /* #143: @19 = (-@19) */
  w19 = (- w19 );
  /* #144: @21 = (@21*@13) */
  w21 *= w13;
  /* #145: @21 = (@12+@21) */
  w21  = (w12+w21);
  /* #146: @28 = 00 */
  /* #147: @29 = 00 */
  /* #148: @40 = vertcat(@5, @7, @12, @15, @19, @21, @28, @29) */
  rr=w40;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w12;
  *rr++ = w15;
  *rr++ = w19;
  *rr++ = w21;
  /* #149: @40 = (-@40) */
  for (i=0, rr=w40, cs=w40; i<6; ++i) *rr++ = (- *cs++ );
  /* #150: @39 = @40[:6] */
  for (rr=w39, ss=w40+0; ss!=w40+6; ss+=1) *rr++ = *ss;
  /* #151: (@26[2, 5, 7, 12, 15, 20] = @39) */
  for (cii=casadi_s9, rr=w26, ss=w39; cii!=casadi_s9+6; ++cii, ++ss) rr[*cii] = *ss;
  /* #152: @41 = @26' */
  casadi_trans(w26,casadi_s10, w41, casadi_s11, iw);
  /* #153: output[1][0] = @41 */
  casadi_copy(w41, 21, res[1]);
  /* #154: @8 = zeros(8x8,8nz) */
  casadi_clear(w8, 8);
  /* #155: @25 = ones(8x1) */
  casadi_fill(w25, 8, 1.);
  /* #156: (@8[:8] = @25) */
  for (rr=w8+0, ss=w25; rr!=w8+8; rr+=1) *rr = *ss++;
  /* #157: @25 = @8' */
  casadi_trans(w8,casadi_s12, w25, casadi_s12, iw);
  /* #158: output[2][0] = @25 */
  casadi_copy(w25, 8, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s13;
    case 2: return casadi_s14;
    case 3: return casadi_s15;
    case 4: return casadi_s15;
    case 5: return casadi_s16;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s13;
    case 1: return casadi_s11;
    case 2: return casadi_s12;
    case 3: return casadi_s17;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tri_frenet_lifted_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 14;
  if (sz_res) *sz_res = 12;
  if (sz_iw) *sz_iw = 9;
  if (sz_w) *sz_w = 124;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
