/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_mtimes CASADI_PREFIX(mtimes)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s14 CASADI_PREFIX(s14)
#define casadi_s15 CASADI_PREFIX(s15)
#define casadi_s16 CASADI_PREFIX(s16)
#define casadi_s17 CASADI_PREFIX(s17)
#define casadi_s18 CASADI_PREFIX(s18)
#define casadi_s19 CASADI_PREFIX(s19)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s20 CASADI_PREFIX(s20)
#define casadi_s21 CASADI_PREFIX(s21)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_mtimes(const casadi_real* x, const casadi_int* sp_x, const casadi_real* y, const casadi_int* sp_y, casadi_real* z, const casadi_int* sp_z, casadi_real* w, casadi_int tr) {
  casadi_int ncol_x, ncol_y, ncol_z, cc;
  const casadi_int *colind_x, *row_x, *colind_y, *row_y, *colind_z, *row_z;
  ncol_x = sp_x[1];
  colind_x = sp_x+2; row_x = sp_x + 2 + ncol_x+1;
  ncol_y = sp_y[1];
  colind_y = sp_y+2; row_y = sp_y + 2 + ncol_y+1;
  ncol_z = sp_z[1];
  colind_z = sp_z+2; row_z = sp_z + 2 + ncol_z+1;
  if (tr) {
    for (cc=0; cc<ncol_z; ++cc) {
      casadi_int kk;
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        w[row_y[kk]] = y[kk];
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_z[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          z[kk] += x[kk1] * w[row_x[kk1]];
        }
      }
    }
  } else {
    for (cc=0; cc<ncol_y; ++cc) {
      casadi_int kk;
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        w[row_z[kk]] = z[kk];
      }
      for (kk=colind_y[cc]; kk<colind_y[cc+1]; ++kk) {
        casadi_int kk1;
        casadi_int rr = row_y[kk];
        for (kk1=colind_x[rr]; kk1<colind_x[rr+1]; ++kk1) {
          w[row_x[kk1]] += x[kk1]*y[kk];
        }
      }
      for (kk=colind_z[cc]; kk<colind_z[cc+1]; ++kk) {
        z[kk] = w[row_z[kk]];
      }
    }
  }
}

static const casadi_int casadi_s0[2] = {0, 78};
static const casadi_int casadi_s1[1] = {3};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[2] = {0, 76};
static const casadi_int casadi_s5[1] = {2};
static const casadi_int casadi_s6[7] = {1, 2, 0, 1, 2, 0, 0};
static const casadi_int casadi_s7[5] = {2, 1, 0, 1, 0};
static const casadi_int casadi_s8[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s9[6] = {1, 2, 0, 1, 1, 0};
static const casadi_int casadi_s10[9] = {2, 2, 0, 2, 4, 0, 1, 0, 1};
static const casadi_int casadi_s11[15] = {0, 3, 6, 9, 12, 14, 16, 18, 20, 23, 26, 29, 32, 34, 36};
static const casadi_int casadi_s12[5] = {2, 1, 0, 1, 1};
static const casadi_int casadi_s13[6] = {1, 2, 0, 0, 1, 0};
static const casadi_int casadi_s14[15] = {1, 4, 7, 10, 13, 15, 17, 19, 21, 24, 27, 30, 33, 35, 37};
static const casadi_int casadi_s15[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s16[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s17[3] = {0, 0, 0};
static const casadi_int casadi_s18[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s19[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s20[56] = {10, 15, 0, 3, 6, 9, 12, 14, 16, 18, 20, 23, 26, 29, 32, 34, 36, 38, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 2, 3, 2, 3, 2, 3, 2, 3, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4, 8, 9, 8, 9, 5, 6};
static const casadi_int casadi_s21[3] = {15, 0, 0};

static const casadi_real casadi_c0[78] = {0., 0., 0., 0., 1.2500000000000000e+00, 1.8750000000000000e+00, 2.5000000000000000e+00, 3.1250000000000000e+00, 3.7500000000000000e+00, 4.3750000000000000e+00, 5., 5.2453380000000003e+00, 5.4906769999999998e+00, 5.7360150000000001e+00, 5.9813530000000004e+00, 6.2266919999999999e+00, 6.4720300000000002e+00, 6.7173689999999997e+00, 6.9627070000000000e+00, 7.2080450000000003e+00, 7.4533839999999998e+00, 7.6987220000000001e+00, 7.9440600000000003e+00, 8.1893989999999999e+00, 8.4347370000000002e+00, 8.6800759999999997e+00, 8.9254140000000000e+00, 9.5504140000000000e+00, 1.0175414000000000e+01, 1.0800414000000000e+01, 1.1425414000000000e+01, 1.2050414000000000e+01, 1.2675414000000000e+01, 1.3300414000000000e+01, 1.3925414000000000e+01, 1.4550414000000000e+01, 1.5175414000000000e+01, 1.5800414000000000e+01, 1.6425414000000000e+01, 1.7050414000000000e+01, 1.7675414000000000e+01, 1.8300414000000000e+01, 1.8925414000000000e+01, 1.9550414000000000e+01, 2.0175414000000000e+01, 2.0800414000000000e+01, 2.1425414000000000e+01, 2.2050414000000000e+01, 2.2675414000000000e+01, 2.3300414000000000e+01, 2.3925414000000000e+01, 2.4550414000000000e+01, 2.5175414000000000e+01, 2.5800414000000000e+01, 2.6425414000000000e+01, 2.6670414000000001e+01, 2.6915413999999998e+01, 2.7160413999999999e+01, 2.7405414000000000e+01, 2.7650414000000001e+01, 2.7895413999999999e+01, 2.8140414000000000e+01, 2.8385414000000001e+01, 2.8630413999999998e+01, 2.8875413999999999e+01, 2.9120414000000000e+01, 2.9365414000000001e+01, 2.9610413999999999e+01, 2.9855414000000000e+01, 3.0100414000000001e+01, 3.0345414000000002e+01, 3.0970414000000002e+01, 3.1595414000000002e+01, 3.2220413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01};
static const casadi_real casadi_c1[74] = {1.2294395982889900e-14, 2.7952717679117324e-04, -5.5905435356318612e-04, 8.3858153035421522e-04, -3.1446807387973488e-03, 1.1740141424881839e-02, -4.3815884960733388e-02, 1.6352339841808494e-01, -4.5359350821290079e-01, -3.9131804904117706e-01, -4.0232631547442710e-01, -3.9937666569630093e-01, -4.0016702682177213e-01, -3.9995523005566586e-01, -4.0001205348192193e-01, -3.9999655615703672e-01, -4.0000172191799771e-01, -3.9999655615692303e-01, -4.0001205348240559e-01, -3.9995523013101142e-01, -4.0016702635852186e-01, -3.9937666275747141e-01, -4.0232631527718049e-01, -3.9131804876141540e-01, -4.5359351035250917e-01, 1.6352342149694324e-01, -4.3815968733675381e-02, 1.1740453437773132e-02, -3.1458450174321573e-03, 8.4292663196823363e-04, -2.2586151044492900e-04, 6.0519409813433068e-05, -1.6216128802851870e-05, 4.3451053870444890e-06, -1.1642927324180945e-06, 3.1206553058398549e-07, -8.3969389995630436e-08, 2.3812042704813497e-08, -1.1278800750564135e-08, 2.1303181091743585e-08, -7.3933936459711063e-08, 2.7443256769708847e-07, -1.0237963229360985e-06, 3.8207527061514885e-06, -1.4259214484904430e-05, 5.3216105221296967e-05, -1.9860520639674792e-04, 7.4120472037036500e-04, -2.7662136750929659e-03, 1.0323649980011904e-02, -3.8528386244964706e-02, 1.4378989499985134e-01, -3.9873251976690666e-01, 5.2927500857770626e-01, 3.6536086144625729e-01, 4.0928154563725633e-01, 3.9751295600472114e-01, 4.0066663034386563e-01, 3.9982052261980155e-01, 4.0005127917694722e-01, 3.9997436067239633e-01, 4.0005127813346958e-01, 3.9982052679373425e-01, 4.0066661469158077e-01, 3.9751301443994819e-01, 4.0928132754862945e-01, 3.6536167536552827e-01, 5.2927197098926360e-01, -3.9871375186475705e-01, 1.4359225665263775e-01, -3.7811607028998884e-02, 7.3510662734108756e-01, -1.7642559056186784e+01, 5.6351208730960875e-20};
static const casadi_real casadi_c2[76] = {0., 0., 0., 1.2500000000000000e+00, 1.8750000000000000e+00, 2.5000000000000000e+00, 3.1250000000000000e+00, 3.7500000000000000e+00, 4.3750000000000000e+00, 5., 5.2453380000000003e+00, 5.4906769999999998e+00, 5.7360150000000001e+00, 5.9813530000000004e+00, 6.2266919999999999e+00, 6.4720300000000002e+00, 6.7173689999999997e+00, 6.9627070000000000e+00, 7.2080450000000003e+00, 7.4533839999999998e+00, 7.6987220000000001e+00, 7.9440600000000003e+00, 8.1893989999999999e+00, 8.4347370000000002e+00, 8.6800759999999997e+00, 8.9254140000000000e+00, 9.5504140000000000e+00, 1.0175414000000000e+01, 1.0800414000000000e+01, 1.1425414000000000e+01, 1.2050414000000000e+01, 1.2675414000000000e+01, 1.3300414000000000e+01, 1.3925414000000000e+01, 1.4550414000000000e+01, 1.5175414000000000e+01, 1.5800414000000000e+01, 1.6425414000000000e+01, 1.7050414000000000e+01, 1.7675414000000000e+01, 1.8300414000000000e+01, 1.8925414000000000e+01, 1.9550414000000000e+01, 2.0175414000000000e+01, 2.0800414000000000e+01, 2.1425414000000000e+01, 2.2050414000000000e+01, 2.2675414000000000e+01, 2.3300414000000000e+01, 2.3925414000000000e+01, 2.4550414000000000e+01, 2.5175414000000000e+01, 2.5800414000000000e+01, 2.6425414000000000e+01, 2.6670414000000001e+01, 2.6915413999999998e+01, 2.7160413999999999e+01, 2.7405414000000000e+01, 2.7650414000000001e+01, 2.7895413999999999e+01, 2.8140414000000000e+01, 2.8385414000000001e+01, 2.8630413999999998e+01, 2.8875413999999999e+01, 2.9120414000000000e+01, 2.9365414000000001e+01, 2.9610413999999999e+01, 2.9855414000000000e+01, 3.0100414000000001e+01, 3.0345414000000002e+01, 3.0970414000000002e+01, 3.1595414000000002e+01, 3.2220413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01};
static const casadi_real casadi_c3[73] = {6.7086522426930927e-04, -1.3417304485669750e-03, 1.6771630607008818e-03, -6.3732196306425029e-03, 2.3815715461886700e-02, -8.8889642216984366e-02, 3.3174285340610937e-01, -1.2380817714075056e+00, 1.6745561440736981e-01, -4.4869736757742841e-02, 1.2022783957363010e-02, -3.2215150185982808e-03, 8.6328444164708704e-04, -2.3161219153956461e-04, 6.3167156451527040e-05, -2.1055661750026254e-05, 2.1055662213346205e-05, -6.3167158886261421e-05, 2.3161220108624083e-04, -8.6328224632819910e-04, 3.2215251090688419e-03, -1.2022778797101176e-02, 4.4869737094074484e-02, -1.6745562091293559e-01, 1.2380818220016858e+00, -3.3174302436898984e-01, 8.8890275474317632e-02, -2.3818077528328464e-02, 6.3820346390406259e-03, -1.7100610278610604e-03, 4.5820947241337936e-04, -1.2277686178605591e-04, 3.2897974703834179e-05, -8.8150369911401343e-06, 2.3621732208033280e-06, -6.3365587292738554e-07, 1.7245029232071030e-07, -5.6145349528604218e-08, 5.2131170947692357e-08, -1.5237938808232744e-07, 5.5738640665087926e-07, -2.0771662250130993e-06, 7.7512784465401400e-06, -2.8927947505689471e-05, 1.0796051152992224e-04, -4.0291409858887186e-04, 1.5036958828273808e-03, -5.6118694327413300e-03, 2.0943781848167795e-02, -7.8163257959962582e-02, 2.9170924999170572e-01, -1.0886737420068715e+00, 2.4968812421828184e+00, -6.6903733523040443e-01, 1.7926809873877164e-01, -4.8035059724633157e-02, 1.2872140159773327e-02, -3.4535009145472430e-03, 9.4186349855380331e-04, -3.1395307979956920e-04, 3.1394882070708653e-04, -9.4184220300136021e-04, 3.4534199912102685e-03, -1.2871837761765729e-02, 4.8033931055842000e-02, -1.7926388646163754e-01, 6.6902161479075373e-01, -2.4968225727013964e+00, 1.0882394819747045e+00, -2.9024618189061918e-01, 7.2745245587772858e-02, -1.7642559056186757e+00, 1.7282506830550319e+00};

/* kapparef_s:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_kapparef_s:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c2,casadi_s4,casadi_s5,casadi_s2,casadi_c3,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt:(i0[8],i1[2],i2[],i3[16])->(o0[15],o1[10x15,38nz],o2[15x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+3, *rr, *ss, *tt;
  const casadi_int *cii;
  const casadi_real **arg1=arg+4, *cr, *cs;
  casadi_real w0, *w1=w+13, w2, w3, w4, w5, w6, w7, w8, *w9=w+22, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, *w24=w+38, *w25=w+54, *w26=w+56, *w27=w+58, *w28=w+62, *w29=w+66, *w30=w+68, *w31=w+70, *w32=w+74, *w33=w+78, *w34=w+82, *w35=w+84, *w36=w+86, *w37=w+90, *w38=w+92, *w39=w+94, *w40=w+98, *w41=w+100, *w42=w+104, *w43=w+106, *w44=w+108, *w45=w+110, *w46=w+114, *w47=w+116, *w48=w+118, *w49=w+122, *w50=w+124, *w51=w+126, w52, *w53=w+131, *w54=w+133, w55, w56, *w57=w+139, *w58=w+141, *w59=w+143, *w60=w+145, *w61=w+149, *w62=w+151, *w63=w+153, *w64=w+157, *w65=w+159, *w66=w+161, *w67=w+165, *w68=w+167, *w69=w+171, *w70=w+209, w71, w72, w73, w75, w76, w77, w78, w79, w80, w81, w82, w83, w84, w85, w86, *w87=w+230, *w88=w+245, *w95=w+248, *w96=w+256;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #2: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = -1.41421 */
  w3 = -1.4142135623730951e+00;
  /* #4: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #6: @5 = (@3*@5) */
  w5  = (w3*w5);
  /* #7: @5 = (@2+@5) */
  w5  = (w2+w5);
  /* #8: @6 = input[0][1] */
  w6 = arg[0] ? arg[0][1] : 0;
  /* #9: @7 = -1.41421 */
  w7 = -1.4142135623730951e+00;
  /* #10: @8 = sin(@4) */
  w8 = sin( w4 );
  /* #11: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #12: @8 = (@6+@8) */
  w8  = (w6+w8);
  /* #13: @9 = vertcat(@5, @8) */
  rr=w9;
  *rr++ = w5;
  *rr++ = w8;
  /* #14: @5 = input[3][0] */
  w5 = arg[3] ? arg[3][0] : 0;
  /* #15: @8 = input[3][1] */
  w8 = arg[3] ? arg[3][1] : 0;
  /* #16: @10 = input[3][2] */
  w10 = arg[3] ? arg[3][2] : 0;
  /* #17: @11 = input[3][3] */
  w11 = arg[3] ? arg[3][3] : 0;
  /* #18: @12 = input[3][4] */
  w12 = arg[3] ? arg[3][4] : 0;
  /* #19: @13 = input[3][5] */
  w13 = arg[3] ? arg[3][5] : 0;
  /* #20: @14 = input[3][6] */
  w14 = arg[3] ? arg[3][6] : 0;
  /* #21: @15 = input[3][7] */
  w15 = arg[3] ? arg[3][7] : 0;
  /* #22: @16 = input[3][8] */
  w16 = arg[3] ? arg[3][8] : 0;
  /* #23: @17 = input[3][9] */
  w17 = arg[3] ? arg[3][9] : 0;
  /* #24: @18 = input[3][10] */
  w18 = arg[3] ? arg[3][10] : 0;
  /* #25: @19 = input[3][11] */
  w19 = arg[3] ? arg[3][11] : 0;
  /* #26: @20 = input[3][12] */
  w20 = arg[3] ? arg[3][12] : 0;
  /* #27: @21 = input[3][13] */
  w21 = arg[3] ? arg[3][13] : 0;
  /* #28: @22 = input[3][14] */
  w22 = arg[3] ? arg[3][14] : 0;
  /* #29: @23 = input[3][15] */
  w23 = arg[3] ? arg[3][15] : 0;
  /* #30: @24 = vertcat(@5, @8, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23) */
  rr=w24;
  *rr++ = w5;
  *rr++ = w8;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  /* #31: @25 = @24[:2] */
  for (rr=w25, ss=w24+0; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #32: @25 = (@9-@25) */
  for (i=0, rr=w25, cr=w9, cs=w25; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #33: @26 = @25' */
  casadi_copy(w25, 2, w26);
  /* #34: @27 = zeros(2x2) */
  casadi_clear(w27, 4);
  /* #35: @28 = zeros(2x2) */
  casadi_clear(w28, 4);
  /* #36: @5 = cos(@11) */
  w5 = cos( w11 );
  /* #37: @8 = sin(@11) */
  w8 = sin( w11 );
  /* #38: @8 = (-@8) */
  w8 = (- w8 );
  /* #39: @29 = horzcat(@5, @8) */
  rr=w29;
  *rr++ = w5;
  *rr++ = w8;
  /* #40: @29 = @29' */
  /* #41: @5 = sin(@11) */
  w5 = sin( w11 );
  /* #42: @8 = cos(@11) */
  w8 = cos( w11 );
  /* #43: @30 = horzcat(@5, @8) */
  rr=w30;
  *rr++ = w5;
  *rr++ = w8;
  /* #44: @30 = @30' */
  /* #45: @31 = horzcat(@29, @30) */
  rr=w31;
  for (i=0, cs=w29; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<2; ++i) *rr++ = *cs++;
  /* #46: @5 = 1 */
  w5 = 1.;
  /* #47: @8 = 1.5 */
  w8 = 1.5000000000000000e+00;
  /* #48: @8 = (@8*@10) */
  w8 *= w10;
  /* #49: @5 = (@5+@8) */
  w5 += w8;
  /* #50: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #51: @5 = (1./@5) */
  w5 = (1./ w5 );
  /* #52: @8 = 0 */
  w8 = 0.;
  /* #53: @29 = horzcat(@5, @8) */
  rr=w29;
  *rr++ = w5;
  *rr++ = w8;
  /* #54: @29 = @29' */
  /* #55: @5 = 0 */
  w5 = 0.;
  /* #56: @8 = 1 */
  w8 = 1.;
  /* #57: @8 = (@8+@10) */
  w8 += w10;
  /* #58: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #59: @8 = (1./@8) */
  w8 = (1./ w8 );
  /* #60: @30 = horzcat(@5, @8) */
  rr=w30;
  *rr++ = w5;
  *rr++ = w8;
  /* #61: @30 = @30' */
  /* #62: @32 = horzcat(@29, @30) */
  rr=w32;
  for (i=0, cs=w29; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<2; ++i) *rr++ = *cs++;
  /* #63: @33 = @32' */
  for (i=0, rr=w33, cs=w32; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #64: @28 = mac(@31,@33,@28) */
  for (i=0, rr=w28; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w33+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #65: @33 = @31' */
  for (i=0, rr=w33, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #66: @27 = mac(@28,@33,@27) */
  for (i=0, rr=w27; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w28+j, tt=w33+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #67: @1 = mac(@26,@27,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #68: @0 = mac(@1,@25,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #69: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #70: @5 = 1 */
  w5 = 1.;
  /* #71: @5 = (@0-@5) */
  w5  = (w0-w5);
  /* #72: output[0][0] = @5 */
  if (res[0]) res[0][0] = w5;
  /* #73: @5 = 0 */
  w5 = 0.;
  /* #74: @26 = zeros(1x2) */
  casadi_clear(w26, 2);
  /* #75: @29 = @24[4:6] */
  for (rr=w29, ss=w24+4; ss!=w24+6; ss+=1) *rr++ = *ss;
  /* #76: @29 = (@9-@29) */
  for (i=0, rr=w29, cr=w9, cs=w29; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #77: @30 = @29' */
  casadi_copy(w29, 2, w30);
  /* #78: @28 = zeros(2x2) */
  casadi_clear(w28, 4);
  /* #79: @33 = zeros(2x2) */
  casadi_clear(w33, 4);
  /* #80: @8 = cos(@15) */
  w8 = cos( w15 );
  /* #81: @12 = sin(@15) */
  w12 = sin( w15 );
  /* #82: @12 = (-@12) */
  w12 = (- w12 );
  /* #83: @34 = horzcat(@8, @12) */
  rr=w34;
  *rr++ = w8;
  *rr++ = w12;
  /* #84: @34 = @34' */
  /* #85: @8 = sin(@15) */
  w8 = sin( w15 );
  /* #86: @12 = cos(@15) */
  w12 = cos( w15 );
  /* #87: @35 = horzcat(@8, @12) */
  rr=w35;
  *rr++ = w8;
  *rr++ = w12;
  /* #88: @35 = @35' */
  /* #89: @31 = horzcat(@34, @35) */
  rr=w31;
  for (i=0, cs=w34; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  /* #90: @8 = 1 */
  w8 = 1.;
  /* #91: @12 = 1.5 */
  w12 = 1.5000000000000000e+00;
  /* #92: @12 = (@12*@14) */
  w12 *= w14;
  /* #93: @8 = (@8+@12) */
  w8 += w12;
  /* #94: @8 = sq(@8) */
  w8 = casadi_sq( w8 );
  /* #95: @8 = (1./@8) */
  w8 = (1./ w8 );
  /* #96: @12 = 0 */
  w12 = 0.;
  /* #97: @34 = horzcat(@8, @12) */
  rr=w34;
  *rr++ = w8;
  *rr++ = w12;
  /* #98: @34 = @34' */
  /* #99: @8 = 0 */
  w8 = 0.;
  /* #100: @12 = 1 */
  w12 = 1.;
  /* #101: @12 = (@12+@14) */
  w12 += w14;
  /* #102: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #103: @12 = (1./@12) */
  w12 = (1./ w12 );
  /* #104: @35 = horzcat(@8, @12) */
  rr=w35;
  *rr++ = w8;
  *rr++ = w12;
  /* #105: @35 = @35' */
  /* #106: @32 = horzcat(@34, @35) */
  rr=w32;
  for (i=0, cs=w34; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<2; ++i) *rr++ = *cs++;
  /* #107: @36 = @32' */
  for (i=0, rr=w36, cs=w32; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #108: @33 = mac(@31,@36,@33) */
  for (i=0, rr=w33; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w36+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #109: @36 = @31' */
  for (i=0, rr=w36, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #110: @28 = mac(@33,@36,@28) */
  for (i=0, rr=w28; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w33+j, tt=w36+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #111: @26 = mac(@30,@28,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w28+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #112: @5 = mac(@26,@29,@5) */
  for (i=0, rr=(&w5); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #113: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #114: @8 = 1 */
  w8 = 1.;
  /* #115: @8 = (@5-@8) */
  w8  = (w5-w8);
  /* #116: output[0][1] = @8 */
  if (res[0]) res[0][1] = w8;
  /* #117: @8 = 0 */
  w8 = 0.;
  /* #118: @30 = zeros(1x2) */
  casadi_clear(w30, 2);
  /* #119: @34 = @24[8:10] */
  for (rr=w34, ss=w24+8; ss!=w24+10; ss+=1) *rr++ = *ss;
  /* #120: @34 = (@9-@34) */
  for (i=0, rr=w34, cr=w9, cs=w34; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #121: @35 = @34' */
  casadi_copy(w34, 2, w35);
  /* #122: @33 = zeros(2x2) */
  casadi_clear(w33, 4);
  /* #123: @36 = zeros(2x2) */
  casadi_clear(w36, 4);
  /* #124: @12 = cos(@19) */
  w12 = cos( w19 );
  /* #125: @13 = sin(@19) */
  w13 = sin( w19 );
  /* #126: @13 = (-@13) */
  w13 = (- w13 );
  /* #127: @37 = horzcat(@12, @13) */
  rr=w37;
  *rr++ = w12;
  *rr++ = w13;
  /* #128: @37 = @37' */
  /* #129: @12 = sin(@19) */
  w12 = sin( w19 );
  /* #130: @13 = cos(@19) */
  w13 = cos( w19 );
  /* #131: @38 = horzcat(@12, @13) */
  rr=w38;
  *rr++ = w12;
  *rr++ = w13;
  /* #132: @38 = @38' */
  /* #133: @31 = horzcat(@37, @38) */
  rr=w31;
  for (i=0, cs=w37; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<2; ++i) *rr++ = *cs++;
  /* #134: @12 = 1 */
  w12 = 1.;
  /* #135: @13 = 1.5 */
  w13 = 1.5000000000000000e+00;
  /* #136: @13 = (@13*@18) */
  w13 *= w18;
  /* #137: @12 = (@12+@13) */
  w12 += w13;
  /* #138: @12 = sq(@12) */
  w12 = casadi_sq( w12 );
  /* #139: @12 = (1./@12) */
  w12 = (1./ w12 );
  /* #140: @13 = 0 */
  w13 = 0.;
  /* #141: @37 = horzcat(@12, @13) */
  rr=w37;
  *rr++ = w12;
  *rr++ = w13;
  /* #142: @37 = @37' */
  /* #143: @12 = 0 */
  w12 = 0.;
  /* #144: @13 = 1 */
  w13 = 1.;
  /* #145: @13 = (@13+@18) */
  w13 += w18;
  /* #146: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #147: @13 = (1./@13) */
  w13 = (1./ w13 );
  /* #148: @38 = horzcat(@12, @13) */
  rr=w38;
  *rr++ = w12;
  *rr++ = w13;
  /* #149: @38 = @38' */
  /* #150: @32 = horzcat(@37, @38) */
  rr=w32;
  for (i=0, cs=w37; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<2; ++i) *rr++ = *cs++;
  /* #151: @39 = @32' */
  for (i=0, rr=w39, cs=w32; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #152: @36 = mac(@31,@39,@36) */
  for (i=0, rr=w36; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w39+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #153: @39 = @31' */
  for (i=0, rr=w39, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #154: @33 = mac(@36,@39,@33) */
  for (i=0, rr=w33; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w36+j, tt=w39+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #155: @30 = mac(@35,@33,@30) */
  for (i=0, rr=w30; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w33+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #156: @8 = mac(@30,@34,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w34+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #157: @8 = sqrt(@8) */
  w8 = sqrt( w8 );
  /* #158: @12 = 1 */
  w12 = 1.;
  /* #159: @12 = (@8-@12) */
  w12  = (w8-w12);
  /* #160: output[0][2] = @12 */
  if (res[0]) res[0][2] = w12;
  /* #161: @12 = 0 */
  w12 = 0.;
  /* #162: @35 = zeros(1x2) */
  casadi_clear(w35, 2);
  /* #163: @37 = @24[12:14] */
  for (rr=w37, ss=w24+12; ss!=w24+14; ss+=1) *rr++ = *ss;
  /* #164: @9 = (@9-@37) */
  for (i=0, rr=w9, cs=w37; i<2; ++i) (*rr++) -= (*cs++);
  /* #165: @37 = @9' */
  casadi_copy(w9, 2, w37);
  /* #166: @36 = zeros(2x2) */
  casadi_clear(w36, 4);
  /* #167: @39 = zeros(2x2) */
  casadi_clear(w39, 4);
  /* #168: @13 = cos(@23) */
  w13 = cos( w23 );
  /* #169: @16 = sin(@23) */
  w16 = sin( w23 );
  /* #170: @16 = (-@16) */
  w16 = (- w16 );
  /* #171: @38 = horzcat(@13, @16) */
  rr=w38;
  *rr++ = w13;
  *rr++ = w16;
  /* #172: @38 = @38' */
  /* #173: @13 = sin(@23) */
  w13 = sin( w23 );
  /* #174: @16 = cos(@23) */
  w16 = cos( w23 );
  /* #175: @40 = horzcat(@13, @16) */
  rr=w40;
  *rr++ = w13;
  *rr++ = w16;
  /* #176: @40 = @40' */
  /* #177: @31 = horzcat(@38, @40) */
  rr=w31;
  for (i=0, cs=w38; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<2; ++i) *rr++ = *cs++;
  /* #178: @13 = 1 */
  w13 = 1.;
  /* #179: @16 = 1.5 */
  w16 = 1.5000000000000000e+00;
  /* #180: @16 = (@16*@22) */
  w16 *= w22;
  /* #181: @13 = (@13+@16) */
  w13 += w16;
  /* #182: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #183: @13 = (1./@13) */
  w13 = (1./ w13 );
  /* #184: @16 = 0 */
  w16 = 0.;
  /* #185: @38 = horzcat(@13, @16) */
  rr=w38;
  *rr++ = w13;
  *rr++ = w16;
  /* #186: @38 = @38' */
  /* #187: @13 = 0 */
  w13 = 0.;
  /* #188: @16 = 1 */
  w16 = 1.;
  /* #189: @16 = (@16+@22) */
  w16 += w22;
  /* #190: @16 = sq(@16) */
  w16 = casadi_sq( w16 );
  /* #191: @16 = (1./@16) */
  w16 = (1./ w16 );
  /* #192: @40 = horzcat(@13, @16) */
  rr=w40;
  *rr++ = w13;
  *rr++ = w16;
  /* #193: @40 = @40' */
  /* #194: @32 = horzcat(@38, @40) */
  rr=w32;
  for (i=0, cs=w38; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<2; ++i) *rr++ = *cs++;
  /* #195: @41 = @32' */
  for (i=0, rr=w41, cs=w32; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #196: @39 = mac(@31,@41,@39) */
  for (i=0, rr=w39; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w41+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #197: @41 = @31' */
  for (i=0, rr=w41, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #198: @36 = mac(@39,@41,@36) */
  for (i=0, rr=w36; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w39+j, tt=w41+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #199: @35 = mac(@37,@36,@35) */
  for (i=0, rr=w35; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w36+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #200: @12 = mac(@35,@9,@12) */
  for (i=0, rr=(&w12); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w9+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #201: @12 = sqrt(@12) */
  w12 = sqrt( w12 );
  /* #202: @13 = 1 */
  w13 = 1.;
  /* #203: @13 = (@12-@13) */
  w13  = (w12-w13);
  /* #204: output[0][3] = @13 */
  if (res[0]) res[0][3] = w13;
  /* #205: @13 = 0 */
  w13 = 0.;
  /* #206: @37 = zeros(1x2) */
  casadi_clear(w37, 2);
  /* #207: @38 = vertcat(@2, @6) */
  rr=w38;
  *rr++ = w2;
  *rr++ = w6;
  /* #208: @40 = @24[:2] */
  for (rr=w40, ss=w24+0; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #209: @40 = (@38-@40) */
  for (i=0, rr=w40, cr=w38, cs=w40; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #210: @42 = @40' */
  casadi_copy(w40, 2, w42);
  /* #211: @39 = zeros(2x2) */
  casadi_clear(w39, 4);
  /* #212: @41 = zeros(2x2) */
  casadi_clear(w41, 4);
  /* #213: @16 = cos(@11) */
  w16 = cos( w11 );
  /* #214: @17 = sin(@11) */
  w17 = sin( w11 );
  /* #215: @17 = (-@17) */
  w17 = (- w17 );
  /* #216: @43 = horzcat(@16, @17) */
  rr=w43;
  *rr++ = w16;
  *rr++ = w17;
  /* #217: @43 = @43' */
  /* #218: @16 = sin(@11) */
  w16 = sin( w11 );
  /* #219: @17 = cos(@11) */
  w17 = cos( w11 );
  /* #220: @44 = horzcat(@16, @17) */
  rr=w44;
  *rr++ = w16;
  *rr++ = w17;
  /* #221: @44 = @44' */
  /* #222: @31 = horzcat(@43, @44) */
  rr=w31;
  for (i=0, cs=w43; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #223: @16 = 1 */
  w16 = 1.;
  /* #224: @17 = 1.5 */
  w17 = 1.5000000000000000e+00;
  /* #225: @17 = (@17*@10) */
  w17 *= w10;
  /* #226: @16 = (@16+@17) */
  w16 += w17;
  /* #227: @16 = sq(@16) */
  w16 = casadi_sq( w16 );
  /* #228: @16 = (1./@16) */
  w16 = (1./ w16 );
  /* #229: @17 = 0 */
  w17 = 0.;
  /* #230: @43 = horzcat(@16, @17) */
  rr=w43;
  *rr++ = w16;
  *rr++ = w17;
  /* #231: @43 = @43' */
  /* #232: @16 = 0 */
  w16 = 0.;
  /* #233: @17 = 1 */
  w17 = 1.;
  /* #234: @17 = (@17+@10) */
  w17 += w10;
  /* #235: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #236: @17 = (1./@17) */
  w17 = (1./ w17 );
  /* #237: @44 = horzcat(@16, @17) */
  rr=w44;
  *rr++ = w16;
  *rr++ = w17;
  /* #238: @44 = @44' */
  /* #239: @32 = horzcat(@43, @44) */
  rr=w32;
  for (i=0, cs=w43; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<2; ++i) *rr++ = *cs++;
  /* #240: @45 = @32' */
  for (i=0, rr=w45, cs=w32; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #241: @41 = mac(@31,@45,@41) */
  for (i=0, rr=w41; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w45+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #242: @45 = @31' */
  for (i=0, rr=w45, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #243: @39 = mac(@41,@45,@39) */
  for (i=0, rr=w39; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w41+j, tt=w45+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #244: @37 = mac(@42,@39,@37) */
  for (i=0, rr=w37; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w42+j, tt=w39+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #245: @13 = mac(@37,@40,@13) */
  for (i=0, rr=(&w13); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w40+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #246: @13 = sqrt(@13) */
  w13 = sqrt( w13 );
  /* #247: @16 = 1 */
  w16 = 1.;
  /* #248: @16 = (@13-@16) */
  w16  = (w13-w16);
  /* #249: output[0][4] = @16 */
  if (res[0]) res[0][4] = w16;
  /* #250: @16 = 0 */
  w16 = 0.;
  /* #251: @42 = zeros(1x2) */
  casadi_clear(w42, 2);
  /* #252: @43 = @24[4:6] */
  for (rr=w43, ss=w24+4; ss!=w24+6; ss+=1) *rr++ = *ss;
  /* #253: @43 = (@38-@43) */
  for (i=0, rr=w43, cr=w38, cs=w43; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #254: @44 = @43' */
  casadi_copy(w43, 2, w44);
  /* #255: @41 = zeros(2x2) */
  casadi_clear(w41, 4);
  /* #256: @45 = zeros(2x2) */
  casadi_clear(w45, 4);
  /* #257: @17 = cos(@15) */
  w17 = cos( w15 );
  /* #258: @20 = sin(@15) */
  w20 = sin( w15 );
  /* #259: @20 = (-@20) */
  w20 = (- w20 );
  /* #260: @46 = horzcat(@17, @20) */
  rr=w46;
  *rr++ = w17;
  *rr++ = w20;
  /* #261: @46 = @46' */
  /* #262: @17 = sin(@15) */
  w17 = sin( w15 );
  /* #263: @20 = cos(@15) */
  w20 = cos( w15 );
  /* #264: @47 = horzcat(@17, @20) */
  rr=w47;
  *rr++ = w17;
  *rr++ = w20;
  /* #265: @47 = @47' */
  /* #266: @31 = horzcat(@46, @47) */
  rr=w31;
  for (i=0, cs=w46; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<2; ++i) *rr++ = *cs++;
  /* #267: @17 = 1 */
  w17 = 1.;
  /* #268: @20 = 1.5 */
  w20 = 1.5000000000000000e+00;
  /* #269: @20 = (@20*@14) */
  w20 *= w14;
  /* #270: @17 = (@17+@20) */
  w17 += w20;
  /* #271: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #272: @17 = (1./@17) */
  w17 = (1./ w17 );
  /* #273: @20 = 0 */
  w20 = 0.;
  /* #274: @46 = horzcat(@17, @20) */
  rr=w46;
  *rr++ = w17;
  *rr++ = w20;
  /* #275: @46 = @46' */
  /* #276: @17 = 0 */
  w17 = 0.;
  /* #277: @20 = 1 */
  w20 = 1.;
  /* #278: @20 = (@20+@14) */
  w20 += w14;
  /* #279: @20 = sq(@20) */
  w20 = casadi_sq( w20 );
  /* #280: @20 = (1./@20) */
  w20 = (1./ w20 );
  /* #281: @47 = horzcat(@17, @20) */
  rr=w47;
  *rr++ = w17;
  *rr++ = w20;
  /* #282: @47 = @47' */
  /* #283: @32 = horzcat(@46, @47) */
  rr=w32;
  for (i=0, cs=w46; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<2; ++i) *rr++ = *cs++;
  /* #284: @48 = @32' */
  for (i=0, rr=w48, cs=w32; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #285: @45 = mac(@31,@48,@45) */
  for (i=0, rr=w45; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w48+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #286: @48 = @31' */
  for (i=0, rr=w48, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #287: @41 = mac(@45,@48,@41) */
  for (i=0, rr=w41; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w45+j, tt=w48+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #288: @42 = mac(@44,@41,@42) */
  for (i=0, rr=w42; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w44+j, tt=w41+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #289: @16 = mac(@42,@43,@16) */
  for (i=0, rr=(&w16); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w42+j, tt=w43+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #290: @16 = sqrt(@16) */
  w16 = sqrt( w16 );
  /* #291: @17 = 1 */
  w17 = 1.;
  /* #292: @17 = (@16-@17) */
  w17  = (w16-w17);
  /* #293: output[0][5] = @17 */
  if (res[0]) res[0][5] = w17;
  /* #294: @17 = 0 */
  w17 = 0.;
  /* #295: @44 = zeros(1x2) */
  casadi_clear(w44, 2);
  /* #296: @46 = @24[8:10] */
  for (rr=w46, ss=w24+8; ss!=w24+10; ss+=1) *rr++ = *ss;
  /* #297: @46 = (@38-@46) */
  for (i=0, rr=w46, cr=w38, cs=w46; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #298: @47 = @46' */
  casadi_copy(w46, 2, w47);
  /* #299: @45 = zeros(2x2) */
  casadi_clear(w45, 4);
  /* #300: @48 = zeros(2x2) */
  casadi_clear(w48, 4);
  /* #301: @20 = cos(@19) */
  w20 = cos( w19 );
  /* #302: @21 = sin(@19) */
  w21 = sin( w19 );
  /* #303: @21 = (-@21) */
  w21 = (- w21 );
  /* #304: @49 = horzcat(@20, @21) */
  rr=w49;
  *rr++ = w20;
  *rr++ = w21;
  /* #305: @49 = @49' */
  /* #306: @20 = sin(@19) */
  w20 = sin( w19 );
  /* #307: @21 = cos(@19) */
  w21 = cos( w19 );
  /* #308: @50 = horzcat(@20, @21) */
  rr=w50;
  *rr++ = w20;
  *rr++ = w21;
  /* #309: @50 = @50' */
  /* #310: @31 = horzcat(@49, @50) */
  rr=w31;
  for (i=0, cs=w49; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<2; ++i) *rr++ = *cs++;
  /* #311: @20 = 1 */
  w20 = 1.;
  /* #312: @21 = 1.5 */
  w21 = 1.5000000000000000e+00;
  /* #313: @21 = (@21*@18) */
  w21 *= w18;
  /* #314: @20 = (@20+@21) */
  w20 += w21;
  /* #315: @20 = sq(@20) */
  w20 = casadi_sq( w20 );
  /* #316: @20 = (1./@20) */
  w20 = (1./ w20 );
  /* #317: @21 = 0 */
  w21 = 0.;
  /* #318: @49 = horzcat(@20, @21) */
  rr=w49;
  *rr++ = w20;
  *rr++ = w21;
  /* #319: @49 = @49' */
  /* #320: @20 = 0 */
  w20 = 0.;
  /* #321: @21 = 1 */
  w21 = 1.;
  /* #322: @21 = (@21+@18) */
  w21 += w18;
  /* #323: @21 = sq(@21) */
  w21 = casadi_sq( w21 );
  /* #324: @21 = (1./@21) */
  w21 = (1./ w21 );
  /* #325: @50 = horzcat(@20, @21) */
  rr=w50;
  *rr++ = w20;
  *rr++ = w21;
  /* #326: @50 = @50' */
  /* #327: @32 = horzcat(@49, @50) */
  rr=w32;
  for (i=0, cs=w49; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<2; ++i) *rr++ = *cs++;
  /* #328: @51 = @32' */
  for (i=0, rr=w51, cs=w32; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #329: @48 = mac(@31,@51,@48) */
  for (i=0, rr=w48; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w51+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #330: @51 = @31' */
  for (i=0, rr=w51, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #331: @45 = mac(@48,@51,@45) */
  for (i=0, rr=w45; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w48+j, tt=w51+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #332: @44 = mac(@47,@45,@44) */
  for (i=0, rr=w44; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w45+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #333: @17 = mac(@44,@46,@17) */
  for (i=0, rr=(&w17); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w44+j, tt=w46+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #334: @17 = sqrt(@17) */
  w17 = sqrt( w17 );
  /* #335: @20 = 1 */
  w20 = 1.;
  /* #336: @20 = (@17-@20) */
  w20  = (w17-w20);
  /* #337: output[0][6] = @20 */
  if (res[0]) res[0][6] = w20;
  /* #338: @20 = 0 */
  w20 = 0.;
  /* #339: @47 = zeros(1x2) */
  casadi_clear(w47, 2);
  /* #340: @49 = @24[12:14] */
  for (rr=w49, ss=w24+12; ss!=w24+14; ss+=1) *rr++ = *ss;
  /* #341: @38 = (@38-@49) */
  for (i=0, rr=w38, cs=w49; i<2; ++i) (*rr++) -= (*cs++);
  /* #342: @49 = @38' */
  casadi_copy(w38, 2, w49);
  /* #343: @48 = zeros(2x2) */
  casadi_clear(w48, 4);
  /* #344: @51 = zeros(2x2) */
  casadi_clear(w51, 4);
  /* #345: @21 = cos(@23) */
  w21 = cos( w23 );
  /* #346: @52 = sin(@23) */
  w52 = sin( w23 );
  /* #347: @52 = (-@52) */
  w52 = (- w52 );
  /* #348: @50 = horzcat(@21, @52) */
  rr=w50;
  *rr++ = w21;
  *rr++ = w52;
  /* #349: @50 = @50' */
  /* #350: @21 = sin(@23) */
  w21 = sin( w23 );
  /* #351: @52 = cos(@23) */
  w52 = cos( w23 );
  /* #352: @53 = horzcat(@21, @52) */
  rr=w53;
  *rr++ = w21;
  *rr++ = w52;
  /* #353: @53 = @53' */
  /* #354: @31 = horzcat(@50, @53) */
  rr=w31;
  for (i=0, cs=w50; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<2; ++i) *rr++ = *cs++;
  /* #355: @21 = 1 */
  w21 = 1.;
  /* #356: @52 = 1.5 */
  w52 = 1.5000000000000000e+00;
  /* #357: @52 = (@52*@22) */
  w52 *= w22;
  /* #358: @21 = (@21+@52) */
  w21 += w52;
  /* #359: @21 = sq(@21) */
  w21 = casadi_sq( w21 );
  /* #360: @21 = (1./@21) */
  w21 = (1./ w21 );
  /* #361: @52 = 0 */
  w52 = 0.;
  /* #362: @50 = horzcat(@21, @52) */
  rr=w50;
  *rr++ = w21;
  *rr++ = w52;
  /* #363: @50 = @50' */
  /* #364: @21 = 0 */
  w21 = 0.;
  /* #365: @52 = 1 */
  w52 = 1.;
  /* #366: @52 = (@52+@22) */
  w52 += w22;
  /* #367: @52 = sq(@52) */
  w52 = casadi_sq( w52 );
  /* #368: @52 = (1./@52) */
  w52 = (1./ w52 );
  /* #369: @53 = horzcat(@21, @52) */
  rr=w53;
  *rr++ = w21;
  *rr++ = w52;
  /* #370: @53 = @53' */
  /* #371: @32 = horzcat(@50, @53) */
  rr=w32;
  for (i=0, cs=w50; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<2; ++i) *rr++ = *cs++;
  /* #372: @54 = @32' */
  for (i=0, rr=w54, cs=w32; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #373: @51 = mac(@31,@54,@51) */
  for (i=0, rr=w51; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w54+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #374: @54 = @31' */
  for (i=0, rr=w54, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #375: @48 = mac(@51,@54,@48) */
  for (i=0, rr=w48; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w51+j, tt=w54+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #376: @47 = mac(@49,@48,@47) */
  for (i=0, rr=w47; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w49+j, tt=w48+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #377: @20 = mac(@47,@38,@20) */
  for (i=0, rr=(&w20); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w38+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #378: @20 = sqrt(@20) */
  w20 = sqrt( w20 );
  /* #379: @21 = 1 */
  w21 = 1.;
  /* #380: @21 = (@20-@21) */
  w21  = (w20-w21);
  /* #381: output[0][7] = @21 */
  if (res[0]) res[0][7] = w21;
  /* #382: @21 = 0 */
  w21 = 0.;
  /* #383: @49 = zeros(1x2) */
  casadi_clear(w49, 2);
  /* #384: @52 = 1.41421 */
  w52 = 1.4142135623730951e+00;
  /* #385: @55 = cos(@4) */
  w55 = cos( w4 );
  /* #386: @55 = (@52*@55) */
  w55  = (w52*w55);
  /* #387: @2 = (@2+@55) */
  w2 += w55;
  /* #388: @55 = 1.41421 */
  w55 = 1.4142135623730951e+00;
  /* #389: @56 = sin(@4) */
  w56 = sin( w4 );
  /* #390: @56 = (@55*@56) */
  w56  = (w55*w56);
  /* #391: @6 = (@6+@56) */
  w6 += w56;
  /* #392: @50 = vertcat(@2, @6) */
  rr=w50;
  *rr++ = w2;
  *rr++ = w6;
  /* #393: @53 = @24[:2] */
  for (rr=w53, ss=w24+0; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #394: @53 = (@50-@53) */
  for (i=0, rr=w53, cr=w50, cs=w53; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #395: @57 = @53' */
  casadi_copy(w53, 2, w57);
  /* #396: @51 = zeros(2x2) */
  casadi_clear(w51, 4);
  /* #397: @54 = zeros(2x2) */
  casadi_clear(w54, 4);
  /* #398: @2 = cos(@11) */
  w2 = cos( w11 );
  /* #399: @6 = sin(@11) */
  w6 = sin( w11 );
  /* #400: @6 = (-@6) */
  w6 = (- w6 );
  /* #401: @58 = horzcat(@2, @6) */
  rr=w58;
  *rr++ = w2;
  *rr++ = w6;
  /* #402: @58 = @58' */
  /* #403: @2 = sin(@11) */
  w2 = sin( w11 );
  /* #404: @11 = cos(@11) */
  w11 = cos( w11 );
  /* #405: @59 = horzcat(@2, @11) */
  rr=w59;
  *rr++ = w2;
  *rr++ = w11;
  /* #406: @59 = @59' */
  /* #407: @31 = horzcat(@58, @59) */
  rr=w31;
  for (i=0, cs=w58; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w59; i<2; ++i) *rr++ = *cs++;
  /* #408: @2 = 1 */
  w2 = 1.;
  /* #409: @11 = 1.5 */
  w11 = 1.5000000000000000e+00;
  /* #410: @11 = (@11*@10) */
  w11 *= w10;
  /* #411: @2 = (@2+@11) */
  w2 += w11;
  /* #412: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #413: @2 = (1./@2) */
  w2 = (1./ w2 );
  /* #414: @11 = 0 */
  w11 = 0.;
  /* #415: @58 = horzcat(@2, @11) */
  rr=w58;
  *rr++ = w2;
  *rr++ = w11;
  /* #416: @58 = @58' */
  /* #417: @2 = 0 */
  w2 = 0.;
  /* #418: @11 = 1 */
  w11 = 1.;
  /* #419: @11 = (@11+@10) */
  w11 += w10;
  /* #420: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #421: @11 = (1./@11) */
  w11 = (1./ w11 );
  /* #422: @59 = horzcat(@2, @11) */
  rr=w59;
  *rr++ = w2;
  *rr++ = w11;
  /* #423: @59 = @59' */
  /* #424: @32 = horzcat(@58, @59) */
  rr=w32;
  for (i=0, cs=w58; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w59; i<2; ++i) *rr++ = *cs++;
  /* #425: @60 = @32' */
  for (i=0, rr=w60, cs=w32; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #426: @54 = mac(@31,@60,@54) */
  for (i=0, rr=w54; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w60+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #427: @60 = @31' */
  for (i=0, rr=w60, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #428: @51 = mac(@54,@60,@51) */
  for (i=0, rr=w51; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w54+j, tt=w60+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #429: @49 = mac(@57,@51,@49) */
  for (i=0, rr=w49; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w57+j, tt=w51+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #430: @21 = mac(@49,@53,@21) */
  for (i=0, rr=(&w21); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w49+j, tt=w53+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #431: @21 = sqrt(@21) */
  w21 = sqrt( w21 );
  /* #432: @2 = 1 */
  w2 = 1.;
  /* #433: @2 = (@21-@2) */
  w2  = (w21-w2);
  /* #434: output[0][8] = @2 */
  if (res[0]) res[0][8] = w2;
  /* #435: @2 = 0 */
  w2 = 0.;
  /* #436: @57 = zeros(1x2) */
  casadi_clear(w57, 2);
  /* #437: @58 = @24[4:6] */
  for (rr=w58, ss=w24+4; ss!=w24+6; ss+=1) *rr++ = *ss;
  /* #438: @58 = (@50-@58) */
  for (i=0, rr=w58, cr=w50, cs=w58; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #439: @59 = @58' */
  casadi_copy(w58, 2, w59);
  /* #440: @54 = zeros(2x2) */
  casadi_clear(w54, 4);
  /* #441: @60 = zeros(2x2) */
  casadi_clear(w60, 4);
  /* #442: @11 = cos(@15) */
  w11 = cos( w15 );
  /* #443: @10 = sin(@15) */
  w10 = sin( w15 );
  /* #444: @10 = (-@10) */
  w10 = (- w10 );
  /* #445: @61 = horzcat(@11, @10) */
  rr=w61;
  *rr++ = w11;
  *rr++ = w10;
  /* #446: @61 = @61' */
  /* #447: @11 = sin(@15) */
  w11 = sin( w15 );
  /* #448: @15 = cos(@15) */
  w15 = cos( w15 );
  /* #449: @62 = horzcat(@11, @15) */
  rr=w62;
  *rr++ = w11;
  *rr++ = w15;
  /* #450: @62 = @62' */
  /* #451: @31 = horzcat(@61, @62) */
  rr=w31;
  for (i=0, cs=w61; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w62; i<2; ++i) *rr++ = *cs++;
  /* #452: @11 = 1 */
  w11 = 1.;
  /* #453: @15 = 1.5 */
  w15 = 1.5000000000000000e+00;
  /* #454: @15 = (@15*@14) */
  w15 *= w14;
  /* #455: @11 = (@11+@15) */
  w11 += w15;
  /* #456: @11 = sq(@11) */
  w11 = casadi_sq( w11 );
  /* #457: @11 = (1./@11) */
  w11 = (1./ w11 );
  /* #458: @15 = 0 */
  w15 = 0.;
  /* #459: @61 = horzcat(@11, @15) */
  rr=w61;
  *rr++ = w11;
  *rr++ = w15;
  /* #460: @61 = @61' */
  /* #461: @11 = 0 */
  w11 = 0.;
  /* #462: @15 = 1 */
  w15 = 1.;
  /* #463: @15 = (@15+@14) */
  w15 += w14;
  /* #464: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #465: @15 = (1./@15) */
  w15 = (1./ w15 );
  /* #466: @62 = horzcat(@11, @15) */
  rr=w62;
  *rr++ = w11;
  *rr++ = w15;
  /* #467: @62 = @62' */
  /* #468: @32 = horzcat(@61, @62) */
  rr=w32;
  for (i=0, cs=w61; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w62; i<2; ++i) *rr++ = *cs++;
  /* #469: @63 = @32' */
  for (i=0, rr=w63, cs=w32; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #470: @60 = mac(@31,@63,@60) */
  for (i=0, rr=w60; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w63+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #471: @63 = @31' */
  for (i=0, rr=w63, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #472: @54 = mac(@60,@63,@54) */
  for (i=0, rr=w54; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w60+j, tt=w63+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #473: @57 = mac(@59,@54,@57) */
  for (i=0, rr=w57; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w59+j, tt=w54+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #474: @2 = mac(@57,@58,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w57+j, tt=w58+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #475: @2 = sqrt(@2) */
  w2 = sqrt( w2 );
  /* #476: @11 = 1 */
  w11 = 1.;
  /* #477: @11 = (@2-@11) */
  w11  = (w2-w11);
  /* #478: output[0][9] = @11 */
  if (res[0]) res[0][9] = w11;
  /* #479: @11 = 0 */
  w11 = 0.;
  /* #480: @59 = zeros(1x2) */
  casadi_clear(w59, 2);
  /* #481: @61 = @24[8:10] */
  for (rr=w61, ss=w24+8; ss!=w24+10; ss+=1) *rr++ = *ss;
  /* #482: @61 = (@50-@61) */
  for (i=0, rr=w61, cr=w50, cs=w61; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #483: @62 = @61' */
  casadi_copy(w61, 2, w62);
  /* #484: @60 = zeros(2x2) */
  casadi_clear(w60, 4);
  /* #485: @63 = zeros(2x2) */
  casadi_clear(w63, 4);
  /* #486: @15 = cos(@19) */
  w15 = cos( w19 );
  /* #487: @14 = sin(@19) */
  w14 = sin( w19 );
  /* #488: @14 = (-@14) */
  w14 = (- w14 );
  /* #489: @64 = horzcat(@15, @14) */
  rr=w64;
  *rr++ = w15;
  *rr++ = w14;
  /* #490: @64 = @64' */
  /* #491: @15 = sin(@19) */
  w15 = sin( w19 );
  /* #492: @19 = cos(@19) */
  w19 = cos( w19 );
  /* #493: @65 = horzcat(@15, @19) */
  rr=w65;
  *rr++ = w15;
  *rr++ = w19;
  /* #494: @65 = @65' */
  /* #495: @31 = horzcat(@64, @65) */
  rr=w31;
  for (i=0, cs=w64; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w65; i<2; ++i) *rr++ = *cs++;
  /* #496: @15 = 1 */
  w15 = 1.;
  /* #497: @19 = 1.5 */
  w19 = 1.5000000000000000e+00;
  /* #498: @19 = (@19*@18) */
  w19 *= w18;
  /* #499: @15 = (@15+@19) */
  w15 += w19;
  /* #500: @15 = sq(@15) */
  w15 = casadi_sq( w15 );
  /* #501: @15 = (1./@15) */
  w15 = (1./ w15 );
  /* #502: @19 = 0 */
  w19 = 0.;
  /* #503: @64 = horzcat(@15, @19) */
  rr=w64;
  *rr++ = w15;
  *rr++ = w19;
  /* #504: @64 = @64' */
  /* #505: @15 = 0 */
  w15 = 0.;
  /* #506: @19 = 1 */
  w19 = 1.;
  /* #507: @19 = (@19+@18) */
  w19 += w18;
  /* #508: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #509: @19 = (1./@19) */
  w19 = (1./ w19 );
  /* #510: @65 = horzcat(@15, @19) */
  rr=w65;
  *rr++ = w15;
  *rr++ = w19;
  /* #511: @65 = @65' */
  /* #512: @32 = horzcat(@64, @65) */
  rr=w32;
  for (i=0, cs=w64; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w65; i<2; ++i) *rr++ = *cs++;
  /* #513: @66 = @32' */
  for (i=0, rr=w66, cs=w32; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #514: @63 = mac(@31,@66,@63) */
  for (i=0, rr=w63; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w66+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #515: @66 = @31' */
  for (i=0, rr=w66, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #516: @60 = mac(@63,@66,@60) */
  for (i=0, rr=w60; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w63+j, tt=w66+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #517: @59 = mac(@62,@60,@59) */
  for (i=0, rr=w59; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w62+j, tt=w60+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #518: @11 = mac(@59,@61,@11) */
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w59+j, tt=w61+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #519: @11 = sqrt(@11) */
  w11 = sqrt( w11 );
  /* #520: @15 = 1 */
  w15 = 1.;
  /* #521: @15 = (@11-@15) */
  w15  = (w11-w15);
  /* #522: output[0][10] = @15 */
  if (res[0]) res[0][10] = w15;
  /* #523: @15 = 0 */
  w15 = 0.;
  /* #524: @62 = zeros(1x2) */
  casadi_clear(w62, 2);
  /* #525: @64 = @24[12:14] */
  for (rr=w64, ss=w24+12; ss!=w24+14; ss+=1) *rr++ = *ss;
  /* #526: @50 = (@50-@64) */
  for (i=0, rr=w50, cs=w64; i<2; ++i) (*rr++) -= (*cs++);
  /* #527: @64 = @50' */
  casadi_copy(w50, 2, w64);
  /* #528: @63 = zeros(2x2) */
  casadi_clear(w63, 4);
  /* #529: @66 = zeros(2x2) */
  casadi_clear(w66, 4);
  /* #530: @19 = cos(@23) */
  w19 = cos( w23 );
  /* #531: @18 = sin(@23) */
  w18 = sin( w23 );
  /* #532: @18 = (-@18) */
  w18 = (- w18 );
  /* #533: @65 = horzcat(@19, @18) */
  rr=w65;
  *rr++ = w19;
  *rr++ = w18;
  /* #534: @65 = @65' */
  /* #535: @19 = sin(@23) */
  w19 = sin( w23 );
  /* #536: @23 = cos(@23) */
  w23 = cos( w23 );
  /* #537: @67 = horzcat(@19, @23) */
  rr=w67;
  *rr++ = w19;
  *rr++ = w23;
  /* #538: @67 = @67' */
  /* #539: @31 = horzcat(@65, @67) */
  rr=w31;
  for (i=0, cs=w65; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w67; i<2; ++i) *rr++ = *cs++;
  /* #540: @19 = 1 */
  w19 = 1.;
  /* #541: @23 = 1.5 */
  w23 = 1.5000000000000000e+00;
  /* #542: @23 = (@23*@22) */
  w23 *= w22;
  /* #543: @19 = (@19+@23) */
  w19 += w23;
  /* #544: @19 = sq(@19) */
  w19 = casadi_sq( w19 );
  /* #545: @19 = (1./@19) */
  w19 = (1./ w19 );
  /* #546: @23 = 0 */
  w23 = 0.;
  /* #547: @65 = horzcat(@19, @23) */
  rr=w65;
  *rr++ = w19;
  *rr++ = w23;
  /* #548: @65 = @65' */
  /* #549: @19 = 0 */
  w19 = 0.;
  /* #550: @23 = 1 */
  w23 = 1.;
  /* #551: @23 = (@23+@22) */
  w23 += w22;
  /* #552: @23 = sq(@23) */
  w23 = casadi_sq( w23 );
  /* #553: @23 = (1./@23) */
  w23 = (1./ w23 );
  /* #554: @67 = horzcat(@19, @23) */
  rr=w67;
  *rr++ = w19;
  *rr++ = w23;
  /* #555: @67 = @67' */
  /* #556: @32 = horzcat(@65, @67) */
  rr=w32;
  for (i=0, cs=w65; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w67; i<2; ++i) *rr++ = *cs++;
  /* #557: @68 = @32' */
  for (i=0, rr=w68, cs=w32; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #558: @66 = mac(@31,@68,@66) */
  for (i=0, rr=w66; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w68+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #559: @68 = @31' */
  for (i=0, rr=w68, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #560: @63 = mac(@66,@68,@63) */
  for (i=0, rr=w63; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w66+j, tt=w68+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #561: @62 = mac(@64,@63,@62) */
  for (i=0, rr=w62; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w63+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #562: @15 = mac(@62,@50,@15) */
  for (i=0, rr=(&w15); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w62+j, tt=w50+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #563: @15 = sqrt(@15) */
  w15 = sqrt( w15 );
  /* #564: @19 = 1 */
  w19 = 1.;
  /* #565: @19 = (@15-@19) */
  w19  = (w15-w19);
  /* #566: output[0][11] = @19 */
  if (res[0]) res[0][11] = w19;
  /* #567: @19 = input[0][6] */
  w19 = arg[0] ? arg[0][6] : 0;
  /* #568: @23 = input[0][7] */
  w23 = arg[0] ? arg[0][7] : 0;
  /* #569: @22 = cos(@23) */
  w22 = cos( w23 );
  /* #570: @18 = (@19*@22) */
  w18  = (w19*w22);
  /* #571: output[0][12] = @18 */
  if (res[0]) res[0][12] = w18;
  /* #572: @18 = sin(@23) */
  w18 = sin( w23 );
  /* #573: @14 = (@19*@18) */
  w14  = (w19*w18);
  /* #574: @10 = 1.03 */
  w10 = 1.0300000000000000e+00;
  /* #575: @14 = (@14/@10) */
  w14 /= w10;
  /* #576: output[0][13] = @14 */
  if (res[0]) res[0][13] = w14;
  /* #577: @14 = input[0][3] */
  w14 = arg[0] ? arg[0][3] : 0;
  /* #578: @10 = kapparef_s(@14) */
  arg1[0]=(&w14);
  res1[0]=(&w10);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #579: @6 = input[0][4] */
  w6 = arg[0] ? arg[0][4] : 0;
  /* #580: @56 = (@10*@6) */
  w56  = (w10*w6);
  /* #581: output[0][14] = @56 */
  if (res[0]) res[0][14] = w56;
  /* #582: @69 = zeros(10x15,38nz) */
  casadi_clear(w69, 38);
  /* #583: @56 = 0 */
  w56 = 0.;
  /* #584: @70 = ones(10x1,6nz) */
  casadi_fill(w70, 6, 1.);
  /* #585: {NULL, NULL, @71, NULL, NULL, @72, NULL, NULL, @73, NULL} = vertsplit(@70) */
  w71 = w70[2];
  w72 = w70[3];
  w73 = w70[5];
  /* #586: @74 = 00 */
  /* #587: @75 = vertcat(@71, @74) */
  rr=(&w75);
  *rr++ = w71;
  /* #588: @56 = mac(@1,@75,@56) */
  casadi_mtimes(w1, casadi_s6, (&w75), casadi_s7, (&w56), casadi_s8, w, 0);
  /* #589: @76 = 0 */
  w76 = 0.;
  /* #590: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #591: @77 = @75' */
  casadi_copy((&w75), 1, (&w77));
  /* #592: @64 = mac(@77,@27,@64) */
  casadi_mtimes((&w77), casadi_s9, w27, casadi_s10, w64, casadi_s6, w, 0);
  /* #593: @76 = mac(@64,@25,@76) */
  for (i=0, rr=(&w76); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #594: @56 = (@56+@76) */
  w56 += w76;
  /* #595: @0 = (2.*@0) */
  w0 = (2.* w0 );
  /* #596: @56 = (@56/@0) */
  w56 /= w0;
  /* #597: @76 = 0 */
  w76 = 0.;
  /* #598: @76 = mac(@26,@75,@76) */
  casadi_mtimes(w26, casadi_s6, (&w75), casadi_s7, (&w76), casadi_s8, w, 0);
  /* #599: @77 = 0 */
  w77 = 0.;
  /* #600: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #601: @78 = @75' */
  casadi_copy((&w75), 1, (&w78));
  /* #602: @64 = mac(@78,@28,@64) */
  casadi_mtimes((&w78), casadi_s9, w28, casadi_s10, w64, casadi_s6, w, 0);
  /* #603: @77 = mac(@64,@29,@77) */
  for (i=0, rr=(&w77); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #604: @76 = (@76+@77) */
  w76 += w77;
  /* #605: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #606: @76 = (@76/@5) */
  w76 /= w5;
  /* #607: @77 = 0 */
  w77 = 0.;
  /* #608: @77 = mac(@30,@75,@77) */
  casadi_mtimes(w30, casadi_s6, (&w75), casadi_s7, (&w77), casadi_s8, w, 0);
  /* #609: @78 = 0 */
  w78 = 0.;
  /* #610: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #611: @79 = @75' */
  casadi_copy((&w75), 1, (&w79));
  /* #612: @64 = mac(@79,@33,@64) */
  casadi_mtimes((&w79), casadi_s9, w33, casadi_s10, w64, casadi_s6, w, 0);
  /* #613: @78 = mac(@64,@34,@78) */
  for (i=0, rr=(&w78); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w34+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #614: @77 = (@77+@78) */
  w77 += w78;
  /* #615: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #616: @77 = (@77/@8) */
  w77 /= w8;
  /* #617: @78 = 0 */
  w78 = 0.;
  /* #618: @78 = mac(@35,@75,@78) */
  casadi_mtimes(w35, casadi_s6, (&w75), casadi_s7, (&w78), casadi_s8, w, 0);
  /* #619: @79 = 0 */
  w79 = 0.;
  /* #620: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #621: @75 = @75' */
  /* #622: @64 = mac(@75,@36,@64) */
  casadi_mtimes((&w75), casadi_s9, w36, casadi_s10, w64, casadi_s6, w, 0);
  /* #623: @79 = mac(@64,@9,@79) */
  for (i=0, rr=(&w79); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w9+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #624: @78 = (@78+@79) */
  w78 += w79;
  /* #625: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #626: @78 = (@78/@12) */
  w78 /= w12;
  /* #627: @79 = 0 */
  w79 = 0.;
  /* #628: @74 = 00 */
  /* #629: @75 = vertcat(@71, @74) */
  rr=(&w75);
  *rr++ = w71;
  /* #630: @79 = mac(@37,@75,@79) */
  casadi_mtimes(w37, casadi_s6, (&w75), casadi_s7, (&w79), casadi_s8, w, 0);
  /* #631: @80 = 0 */
  w80 = 0.;
  /* #632: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #633: @81 = @75' */
  casadi_copy((&w75), 1, (&w81));
  /* #634: @64 = mac(@81,@39,@64) */
  casadi_mtimes((&w81), casadi_s9, w39, casadi_s10, w64, casadi_s6, w, 0);
  /* #635: @80 = mac(@64,@40,@80) */
  for (i=0, rr=(&w80); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w40+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #636: @79 = (@79+@80) */
  w79 += w80;
  /* #637: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #638: @79 = (@79/@13) */
  w79 /= w13;
  /* #639: @80 = 0 */
  w80 = 0.;
  /* #640: @80 = mac(@42,@75,@80) */
  casadi_mtimes(w42, casadi_s6, (&w75), casadi_s7, (&w80), casadi_s8, w, 0);
  /* #641: @81 = 0 */
  w81 = 0.;
  /* #642: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #643: @82 = @75' */
  casadi_copy((&w75), 1, (&w82));
  /* #644: @64 = mac(@82,@41,@64) */
  casadi_mtimes((&w82), casadi_s9, w41, casadi_s10, w64, casadi_s6, w, 0);
  /* #645: @81 = mac(@64,@43,@81) */
  for (i=0, rr=(&w81); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w43+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #646: @80 = (@80+@81) */
  w80 += w81;
  /* #647: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #648: @80 = (@80/@16) */
  w80 /= w16;
  /* #649: @81 = 0 */
  w81 = 0.;
  /* #650: @81 = mac(@44,@75,@81) */
  casadi_mtimes(w44, casadi_s6, (&w75), casadi_s7, (&w81), casadi_s8, w, 0);
  /* #651: @82 = 0 */
  w82 = 0.;
  /* #652: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #653: @83 = @75' */
  casadi_copy((&w75), 1, (&w83));
  /* #654: @64 = mac(@83,@45,@64) */
  casadi_mtimes((&w83), casadi_s9, w45, casadi_s10, w64, casadi_s6, w, 0);
  /* #655: @82 = mac(@64,@46,@82) */
  for (i=0, rr=(&w82); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w46+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #656: @81 = (@81+@82) */
  w81 += w82;
  /* #657: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #658: @81 = (@81/@17) */
  w81 /= w17;
  /* #659: @82 = 0 */
  w82 = 0.;
  /* #660: @82 = mac(@47,@75,@82) */
  casadi_mtimes(w47, casadi_s6, (&w75), casadi_s7, (&w82), casadi_s8, w, 0);
  /* #661: @83 = 0 */
  w83 = 0.;
  /* #662: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #663: @75 = @75' */
  /* #664: @64 = mac(@75,@48,@64) */
  casadi_mtimes((&w75), casadi_s9, w48, casadi_s10, w64, casadi_s6, w, 0);
  /* #665: @83 = mac(@64,@38,@83) */
  for (i=0, rr=(&w83); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w38+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #666: @82 = (@82+@83) */
  w82 += w83;
  /* #667: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #668: @82 = (@82/@20) */
  w82 /= w20;
  /* #669: @83 = 0 */
  w83 = 0.;
  /* #670: @74 = 00 */
  /* #671: @75 = vertcat(@71, @74) */
  rr=(&w75);
  *rr++ = w71;
  /* #672: @83 = mac(@49,@75,@83) */
  casadi_mtimes(w49, casadi_s6, (&w75), casadi_s7, (&w83), casadi_s8, w, 0);
  /* #673: @71 = 0 */
  w71 = 0.;
  /* #674: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #675: @84 = @75' */
  casadi_copy((&w75), 1, (&w84));
  /* #676: @64 = mac(@84,@51,@64) */
  casadi_mtimes((&w84), casadi_s9, w51, casadi_s10, w64, casadi_s6, w, 0);
  /* #677: @71 = mac(@64,@53,@71) */
  for (i=0, rr=(&w71); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w53+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #678: @83 = (@83+@71) */
  w83 += w71;
  /* #679: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #680: @83 = (@83/@21) */
  w83 /= w21;
  /* #681: @71 = 0 */
  w71 = 0.;
  /* #682: @71 = mac(@57,@75,@71) */
  casadi_mtimes(w57, casadi_s6, (&w75), casadi_s7, (&w71), casadi_s8, w, 0);
  /* #683: @84 = 0 */
  w84 = 0.;
  /* #684: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #685: @85 = @75' */
  casadi_copy((&w75), 1, (&w85));
  /* #686: @64 = mac(@85,@54,@64) */
  casadi_mtimes((&w85), casadi_s9, w54, casadi_s10, w64, casadi_s6, w, 0);
  /* #687: @84 = mac(@64,@58,@84) */
  for (i=0, rr=(&w84); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w58+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #688: @71 = (@71+@84) */
  w71 += w84;
  /* #689: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #690: @71 = (@71/@2) */
  w71 /= w2;
  /* #691: @84 = 0 */
  w84 = 0.;
  /* #692: @84 = mac(@59,@75,@84) */
  casadi_mtimes(w59, casadi_s6, (&w75), casadi_s7, (&w84), casadi_s8, w, 0);
  /* #693: @85 = 0 */
  w85 = 0.;
  /* #694: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #695: @86 = @75' */
  casadi_copy((&w75), 1, (&w86));
  /* #696: @64 = mac(@86,@60,@64) */
  casadi_mtimes((&w86), casadi_s9, w60, casadi_s10, w64, casadi_s6, w, 0);
  /* #697: @85 = mac(@64,@61,@85) */
  for (i=0, rr=(&w85); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w61+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #698: @84 = (@84+@85) */
  w84 += w85;
  /* #699: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #700: @84 = (@84/@11) */
  w84 /= w11;
  /* #701: @85 = 0 */
  w85 = 0.;
  /* #702: @85 = mac(@62,@75,@85) */
  casadi_mtimes(w62, casadi_s6, (&w75), casadi_s7, (&w85), casadi_s8, w, 0);
  /* #703: @86 = 0 */
  w86 = 0.;
  /* #704: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #705: @75 = @75' */
  /* #706: @64 = mac(@75,@63,@64) */
  casadi_mtimes((&w75), casadi_s9, w63, casadi_s10, w64, casadi_s6, w, 0);
  /* #707: @86 = mac(@64,@50,@86) */
  for (i=0, rr=(&w86); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w50+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #708: @85 = (@85+@86) */
  w85 += w86;
  /* #709: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #710: @85 = (@85/@15) */
  w85 /= w15;
  /* #711: @22 = (@22*@73) */
  w22 *= w73;
  /* #712: @86 = 0.970874 */
  w86 = 9.7087378640776700e-01;
  /* #713: @18 = (@18*@73) */
  w18 *= w73;
  /* #714: @18 = (@86*@18) */
  w18  = (w86*w18);
  /* #715: @74 = 00 */
  /* #716: @73 = fwd1_kapparef_s(@14, @74, @72) */
  arg1[0]=(&w14);
  arg1[1]=0;
  arg1[2]=(&w72);
  res1[0]=(&w73);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #717: @6 = (@6*@73) */
  w6 *= w73;
  /* #718: @87 = vertcat(@56, @76, @77, @78, @79, @80, @81, @82, @83, @71, @84, @85, @22, @18, @6) */
  rr=w87;
  *rr++ = w56;
  *rr++ = w76;
  *rr++ = w77;
  *rr++ = w78;
  *rr++ = w79;
  *rr++ = w80;
  *rr++ = w81;
  *rr++ = w82;
  *rr++ = w83;
  *rr++ = w71;
  *rr++ = w84;
  *rr++ = w85;
  *rr++ = w22;
  *rr++ = w18;
  *rr++ = w6;
  /* #719: (@69[0, 3, 6, 9, 12, 14, 16, 18, 20, 23, 26, 29, 32, 34, 36] = @87) */
  for (cii=casadi_s11, rr=w69, ss=w87; cii!=casadi_s11+15; ++cii, ++ss) rr[*cii] = *ss;
  /* #720: @56 = 0 */
  w56 = 0.;
  /* #721: @74 = 00 */
  /* #722: @88 = ones(10x1,3nz) */
  casadi_fill(w88, 3, 1.);
  /* #723: {NULL, NULL, NULL, @76, NULL, NULL, @77, NULL, NULL, @78} = vertsplit(@88) */
  w76 = w88[0];
  w77 = w88[1];
  w78 = w88[2];
  /* #724: @79 = vertcat(@74, @76) */
  rr=(&w79);
  *rr++ = w76;
  /* #725: @56 = mac(@1,@79,@56) */
  casadi_mtimes(w1, casadi_s6, (&w79), casadi_s12, (&w56), casadi_s8, w, 0);
  /* #726: @80 = 0 */
  w80 = 0.;
  /* #727: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #728: @81 = @79' */
  casadi_copy((&w79), 1, (&w81));
  /* #729: @64 = mac(@81,@27,@64) */
  casadi_mtimes((&w81), casadi_s13, w27, casadi_s10, w64, casadi_s6, w, 0);
  /* #730: @80 = mac(@64,@25,@80) */
  for (i=0, rr=(&w80); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #731: @56 = (@56+@80) */
  w56 += w80;
  /* #732: @56 = (@56/@0) */
  w56 /= w0;
  /* #733: @80 = 0 */
  w80 = 0.;
  /* #734: @80 = mac(@26,@79,@80) */
  casadi_mtimes(w26, casadi_s6, (&w79), casadi_s12, (&w80), casadi_s8, w, 0);
  /* #735: @81 = 0 */
  w81 = 0.;
  /* #736: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #737: @82 = @79' */
  casadi_copy((&w79), 1, (&w82));
  /* #738: @64 = mac(@82,@28,@64) */
  casadi_mtimes((&w82), casadi_s13, w28, casadi_s10, w64, casadi_s6, w, 0);
  /* #739: @81 = mac(@64,@29,@81) */
  for (i=0, rr=(&w81); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #740: @80 = (@80+@81) */
  w80 += w81;
  /* #741: @80 = (@80/@5) */
  w80 /= w5;
  /* #742: @81 = 0 */
  w81 = 0.;
  /* #743: @81 = mac(@30,@79,@81) */
  casadi_mtimes(w30, casadi_s6, (&w79), casadi_s12, (&w81), casadi_s8, w, 0);
  /* #744: @82 = 0 */
  w82 = 0.;
  /* #745: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #746: @83 = @79' */
  casadi_copy((&w79), 1, (&w83));
  /* #747: @64 = mac(@83,@33,@64) */
  casadi_mtimes((&w83), casadi_s13, w33, casadi_s10, w64, casadi_s6, w, 0);
  /* #748: @82 = mac(@64,@34,@82) */
  for (i=0, rr=(&w82); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w34+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #749: @81 = (@81+@82) */
  w81 += w82;
  /* #750: @81 = (@81/@8) */
  w81 /= w8;
  /* #751: @82 = 0 */
  w82 = 0.;
  /* #752: @82 = mac(@35,@79,@82) */
  casadi_mtimes(w35, casadi_s6, (&w79), casadi_s12, (&w82), casadi_s8, w, 0);
  /* #753: @83 = 0 */
  w83 = 0.;
  /* #754: @64 = zeros(1x2) */
  casadi_clear(w64, 2);
  /* #755: @79 = @79' */
  /* #756: @64 = mac(@79,@36,@64) */
  casadi_mtimes((&w79), casadi_s13, w36, casadi_s10, w64, casadi_s6, w, 0);
  /* #757: @83 = mac(@64,@9,@83) */
  for (i=0, rr=(&w83); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w64+j, tt=w9+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #758: @82 = (@82+@83) */
  w82 += w83;
  /* #759: @82 = (@82/@12) */
  w82 /= w12;
  /* #760: @83 = 0 */
  w83 = 0.;
  /* #761: @74 = 00 */
  /* #762: @79 = vertcat(@74, @76) */
  rr=(&w79);
  *rr++ = w76;
  /* #763: @83 = mac(@37,@79,@83) */
  casadi_mtimes(w37, casadi_s6, (&w79), casadi_s12, (&w83), casadi_s8, w, 0);
  /* #764: @71 = 0 */
  w71 = 0.;
  /* #765: @37 = zeros(1x2) */
  casadi_clear(w37, 2);
  /* #766: @84 = @79' */
  casadi_copy((&w79), 1, (&w84));
  /* #767: @37 = mac(@84,@39,@37) */
  casadi_mtimes((&w84), casadi_s13, w39, casadi_s10, w37, casadi_s6, w, 0);
  /* #768: @71 = mac(@37,@40,@71) */
  for (i=0, rr=(&w71); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w37+j, tt=w40+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #769: @83 = (@83+@71) */
  w83 += w71;
  /* #770: @83 = (@83/@13) */
  w83 /= w13;
  /* #771: @13 = 0 */
  w13 = 0.;
  /* #772: @13 = mac(@42,@79,@13) */
  casadi_mtimes(w42, casadi_s6, (&w79), casadi_s12, (&w13), casadi_s8, w, 0);
  /* #773: @71 = 0 */
  w71 = 0.;
  /* #774: @42 = zeros(1x2) */
  casadi_clear(w42, 2);
  /* #775: @84 = @79' */
  casadi_copy((&w79), 1, (&w84));
  /* #776: @42 = mac(@84,@41,@42) */
  casadi_mtimes((&w84), casadi_s13, w41, casadi_s10, w42, casadi_s6, w, 0);
  /* #777: @71 = mac(@42,@43,@71) */
  for (i=0, rr=(&w71); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w42+j, tt=w43+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #778: @13 = (@13+@71) */
  w13 += w71;
  /* #779: @13 = (@13/@16) */
  w13 /= w16;
  /* #780: @16 = 0 */
  w16 = 0.;
  /* #781: @16 = mac(@44,@79,@16) */
  casadi_mtimes(w44, casadi_s6, (&w79), casadi_s12, (&w16), casadi_s8, w, 0);
  /* #782: @71 = 0 */
  w71 = 0.;
  /* #783: @44 = zeros(1x2) */
  casadi_clear(w44, 2);
  /* #784: @84 = @79' */
  casadi_copy((&w79), 1, (&w84));
  /* #785: @44 = mac(@84,@45,@44) */
  casadi_mtimes((&w84), casadi_s13, w45, casadi_s10, w44, casadi_s6, w, 0);
  /* #786: @71 = mac(@44,@46,@71) */
  for (i=0, rr=(&w71); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w44+j, tt=w46+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #787: @16 = (@16+@71) */
  w16 += w71;
  /* #788: @16 = (@16/@17) */
  w16 /= w17;
  /* #789: @17 = 0 */
  w17 = 0.;
  /* #790: @17 = mac(@47,@79,@17) */
  casadi_mtimes(w47, casadi_s6, (&w79), casadi_s12, (&w17), casadi_s8, w, 0);
  /* #791: @71 = 0 */
  w71 = 0.;
  /* #792: @47 = zeros(1x2) */
  casadi_clear(w47, 2);
  /* #793: @79 = @79' */
  /* #794: @47 = mac(@79,@48,@47) */
  casadi_mtimes((&w79), casadi_s13, w48, casadi_s10, w47, casadi_s6, w, 0);
  /* #795: @71 = mac(@47,@38,@71) */
  for (i=0, rr=(&w71); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w38+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #796: @17 = (@17+@71) */
  w17 += w71;
  /* #797: @17 = (@17/@20) */
  w17 /= w20;
  /* #798: @20 = 0 */
  w20 = 0.;
  /* #799: @74 = 00 */
  /* #800: @71 = vertcat(@74, @76) */
  rr=(&w71);
  *rr++ = w76;
  /* #801: @20 = mac(@49,@71,@20) */
  casadi_mtimes(w49, casadi_s6, (&w71), casadi_s12, (&w20), casadi_s8, w, 0);
  /* #802: @76 = 0 */
  w76 = 0.;
  /* #803: @47 = zeros(1x2) */
  casadi_clear(w47, 2);
  /* #804: @79 = @71' */
  casadi_copy((&w71), 1, (&w79));
  /* #805: @47 = mac(@79,@51,@47) */
  casadi_mtimes((&w79), casadi_s13, w51, casadi_s10, w47, casadi_s6, w, 0);
  /* #806: @76 = mac(@47,@53,@76) */
  for (i=0, rr=(&w76); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w53+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #807: @20 = (@20+@76) */
  w20 += w76;
  /* #808: @20 = (@20/@21) */
  w20 /= w21;
  /* #809: @76 = 0 */
  w76 = 0.;
  /* #810: @76 = mac(@57,@71,@76) */
  casadi_mtimes(w57, casadi_s6, (&w71), casadi_s12, (&w76), casadi_s8, w, 0);
  /* #811: @79 = 0 */
  w79 = 0.;
  /* #812: @47 = zeros(1x2) */
  casadi_clear(w47, 2);
  /* #813: @84 = @71' */
  casadi_copy((&w71), 1, (&w84));
  /* #814: @47 = mac(@84,@54,@47) */
  casadi_mtimes((&w84), casadi_s13, w54, casadi_s10, w47, casadi_s6, w, 0);
  /* #815: @79 = mac(@47,@58,@79) */
  for (i=0, rr=(&w79); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w58+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #816: @76 = (@76+@79) */
  w76 += w79;
  /* #817: @76 = (@76/@2) */
  w76 /= w2;
  /* #818: @79 = 0 */
  w79 = 0.;
  /* #819: @79 = mac(@59,@71,@79) */
  casadi_mtimes(w59, casadi_s6, (&w71), casadi_s12, (&w79), casadi_s8, w, 0);
  /* #820: @84 = 0 */
  w84 = 0.;
  /* #821: @47 = zeros(1x2) */
  casadi_clear(w47, 2);
  /* #822: @85 = @71' */
  casadi_copy((&w71), 1, (&w85));
  /* #823: @47 = mac(@85,@60,@47) */
  casadi_mtimes((&w85), casadi_s13, w60, casadi_s10, w47, casadi_s6, w, 0);
  /* #824: @84 = mac(@47,@61,@84) */
  for (i=0, rr=(&w84); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w61+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #825: @79 = (@79+@84) */
  w79 += w84;
  /* #826: @79 = (@79/@11) */
  w79 /= w11;
  /* #827: @84 = 0 */
  w84 = 0.;
  /* #828: @84 = mac(@62,@71,@84) */
  casadi_mtimes(w62, casadi_s6, (&w71), casadi_s12, (&w84), casadi_s8, w, 0);
  /* #829: @85 = 0 */
  w85 = 0.;
  /* #830: @47 = zeros(1x2) */
  casadi_clear(w47, 2);
  /* #831: @71 = @71' */
  /* #832: @47 = mac(@71,@63,@47) */
  casadi_mtimes((&w71), casadi_s13, w63, casadi_s10, w47, casadi_s6, w, 0);
  /* #833: @85 = mac(@47,@50,@85) */
  for (i=0, rr=(&w85); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w50+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #834: @84 = (@84+@85) */
  w84 += w85;
  /* #835: @84 = (@84/@15) */
  w84 /= w15;
  /* #836: @85 = sin(@23) */
  w85 = sin( w23 );
  /* #837: @85 = (@85*@78) */
  w85 *= w78;
  /* #838: @85 = (@19*@85) */
  w85  = (w19*w85);
  /* #839: @85 = (-@85) */
  w85 = (- w85 );
  /* #840: @23 = cos(@23) */
  w23 = cos( w23 );
  /* #841: @23 = (@23*@78) */
  w23 *= w78;
  /* #842: @19 = (@19*@23) */
  w19 *= w23;
  /* #843: @86 = (@86*@19) */
  w86 *= w19;
  /* #844: @10 = (@10*@77) */
  w10 *= w77;
  /* #845: @87 = vertcat(@56, @80, @81, @82, @83, @13, @16, @17, @20, @76, @79, @84, @85, @86, @10) */
  rr=w87;
  *rr++ = w56;
  *rr++ = w80;
  *rr++ = w81;
  *rr++ = w82;
  *rr++ = w83;
  *rr++ = w13;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w20;
  *rr++ = w76;
  *rr++ = w79;
  *rr++ = w84;
  *rr++ = w85;
  *rr++ = w86;
  *rr++ = w10;
  /* #846: (@69[1, 4, 7, 10, 13, 15, 17, 19, 21, 24, 27, 30, 33, 35, 37] = @87) */
  for (cii=casadi_s14, rr=w69, ss=w87; cii!=casadi_s14+15; ++cii, ++ss) rr[*cii] = *ss;
  /* #847: @56 = 0 */
  w56 = 0.;
  /* #848: @80 = sin(@4) */
  w80 = sin( w4 );
  /* #849: @81 = ones(10x1,1nz) */
  w81 = 1.;
  /* #850: {NULL, NULL, NULL, NULL, @82, NULL, NULL, NULL, NULL, NULL} = vertsplit(@81) */
  w82 = w81;
  /* #851: @80 = (@80*@82) */
  w80 *= w82;
  /* #852: @3 = (@3*@80) */
  w3 *= w80;
  /* #853: @3 = (-@3) */
  w3 = (- w3 );
  /* #854: @80 = cos(@4) */
  w80 = cos( w4 );
  /* #855: @80 = (@80*@82) */
  w80 *= w82;
  /* #856: @7 = (@7*@80) */
  w7 *= w80;
  /* #857: @47 = vertcat(@3, @7) */
  rr=w47;
  *rr++ = w3;
  *rr++ = w7;
  /* #858: @56 = mac(@1,@47,@56) */
  for (i=0, rr=(&w56); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w47+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #859: @3 = 0 */
  w3 = 0.;
  /* #860: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #861: @38 = @47' */
  casadi_copy(w47, 2, w38);
  /* #862: @1 = mac(@38,@27,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w38+j, tt=w27+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #863: @3 = mac(@1,@25,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #864: @56 = (@56+@3) */
  w56 += w3;
  /* #865: @56 = (@56/@0) */
  w56 /= w0;
  /* #866: @0 = 0 */
  w0 = 0.;
  /* #867: @0 = mac(@26,@47,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w47+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #868: @3 = 0 */
  w3 = 0.;
  /* #869: @26 = zeros(1x2) */
  casadi_clear(w26, 2);
  /* #870: @1 = @47' */
  casadi_copy(w47, 2, w1);
  /* #871: @26 = mac(@1,@28,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w28+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #872: @3 = mac(@26,@29,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #873: @0 = (@0+@3) */
  w0 += w3;
  /* #874: @0 = (@0/@5) */
  w0 /= w5;
  /* #875: @5 = 0 */
  w5 = 0.;
  /* #876: @5 = mac(@30,@47,@5) */
  for (i=0, rr=(&w5); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w47+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #877: @3 = 0 */
  w3 = 0.;
  /* #878: @30 = zeros(1x2) */
  casadi_clear(w30, 2);
  /* #879: @26 = @47' */
  casadi_copy(w47, 2, w26);
  /* #880: @30 = mac(@26,@33,@30) */
  for (i=0, rr=w30; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w26+j, tt=w33+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #881: @3 = mac(@30,@34,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w30+j, tt=w34+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #882: @5 = (@5+@3) */
  w5 += w3;
  /* #883: @5 = (@5/@8) */
  w5 /= w8;
  /* #884: @8 = 0 */
  w8 = 0.;
  /* #885: @8 = mac(@35,@47,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w47+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #886: @3 = 0 */
  w3 = 0.;
  /* #887: @35 = zeros(1x2) */
  casadi_clear(w35, 2);
  /* #888: @47 = @47' */
  /* #889: @35 = mac(@47,@36,@35) */
  for (i=0, rr=w35; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w47+j, tt=w36+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #890: @3 = mac(@35,@9,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w9+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #891: @8 = (@8+@3) */
  w8 += w3;
  /* #892: @8 = (@8/@12) */
  w8 /= w12;
  /* #893: @74 = 00 */
  /* #894: @89 = 00 */
  /* #895: @90 = 00 */
  /* #896: @91 = 00 */
  /* #897: @12 = 0 */
  w12 = 0.;
  /* #898: @3 = sin(@4) */
  w3 = sin( w4 );
  /* #899: @3 = (@3*@82) */
  w3 *= w82;
  /* #900: @52 = (@52*@3) */
  w52 *= w3;
  /* #901: @52 = (-@52) */
  w52 = (- w52 );
  /* #902: @4 = cos(@4) */
  w4 = cos( w4 );
  /* #903: @4 = (@4*@82) */
  w4 *= w82;
  /* #904: @55 = (@55*@4) */
  w55 *= w4;
  /* #905: @35 = vertcat(@52, @55) */
  rr=w35;
  *rr++ = w52;
  *rr++ = w55;
  /* #906: @12 = mac(@49,@35,@12) */
  for (i=0, rr=(&w12); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w49+j, tt=w35+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #907: @52 = 0 */
  w52 = 0.;
  /* #908: @49 = zeros(1x2) */
  casadi_clear(w49, 2);
  /* #909: @9 = @35' */
  casadi_copy(w35, 2, w9);
  /* #910: @49 = mac(@9,@51,@49) */
  for (i=0, rr=w49; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w9+j, tt=w51+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #911: @52 = mac(@49,@53,@52) */
  for (i=0, rr=(&w52); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w49+j, tt=w53+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #912: @12 = (@12+@52) */
  w12 += w52;
  /* #913: @12 = (@12/@21) */
  w12 /= w21;
  /* #914: @21 = 0 */
  w21 = 0.;
  /* #915: @21 = mac(@57,@35,@21) */
  for (i=0, rr=(&w21); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w57+j, tt=w35+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #916: @52 = 0 */
  w52 = 0.;
  /* #917: @57 = zeros(1x2) */
  casadi_clear(w57, 2);
  /* #918: @49 = @35' */
  casadi_copy(w35, 2, w49);
  /* #919: @57 = mac(@49,@54,@57) */
  for (i=0, rr=w57; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w49+j, tt=w54+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #920: @52 = mac(@57,@58,@52) */
  for (i=0, rr=(&w52); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w57+j, tt=w58+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #921: @21 = (@21+@52) */
  w21 += w52;
  /* #922: @21 = (@21/@2) */
  w21 /= w2;
  /* #923: @2 = 0 */
  w2 = 0.;
  /* #924: @2 = mac(@59,@35,@2) */
  for (i=0, rr=(&w2); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w59+j, tt=w35+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #925: @52 = 0 */
  w52 = 0.;
  /* #926: @59 = zeros(1x2) */
  casadi_clear(w59, 2);
  /* #927: @57 = @35' */
  casadi_copy(w35, 2, w57);
  /* #928: @59 = mac(@57,@60,@59) */
  for (i=0, rr=w59; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w57+j, tt=w60+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #929: @52 = mac(@59,@61,@52) */
  for (i=0, rr=(&w52); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w59+j, tt=w61+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #930: @2 = (@2+@52) */
  w2 += w52;
  /* #931: @2 = (@2/@11) */
  w2 /= w11;
  /* #932: @11 = 0 */
  w11 = 0.;
  /* #933: @11 = mac(@62,@35,@11) */
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w62+j, tt=w35+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #934: @52 = 0 */
  w52 = 0.;
  /* #935: @62 = zeros(1x2) */
  casadi_clear(w62, 2);
  /* #936: @35 = @35' */
  /* #937: @62 = mac(@35,@63,@62) */
  for (i=0, rr=w62; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w35+j, tt=w63+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #938: @52 = mac(@62,@50,@52) */
  for (i=0, rr=(&w52); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w62+j, tt=w50+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #939: @11 = (@11+@52) */
  w11 += w52;
  /* #940: @11 = (@11/@15) */
  w11 /= w15;
  /* #941: @92 = 00 */
  /* #942: @93 = 00 */
  /* #943: @94 = 00 */
  /* #944: @95 = vertcat(@56, @0, @5, @8, @74, @89, @90, @91, @12, @21, @2, @11, @92, @93, @94) */
  rr=w95;
  *rr++ = w56;
  *rr++ = w0;
  *rr++ = w5;
  *rr++ = w8;
  *rr++ = w12;
  *rr++ = w21;
  *rr++ = w2;
  *rr++ = w11;
  /* #945: @96 = @95[:8] */
  for (rr=w96, ss=w95+0; ss!=w95+8; ss+=1) *rr++ = *ss;
  /* #946: (@69[:40:20;2:14:3] = @96) */
  for (rr=w69+0, ss=w96; rr!=w69+40; rr+=20) for (tt=rr+2; tt!=rr+14; tt+=3) *tt = *ss++;
  /* #947: output[1][0] = @69 */
  casadi_copy(w69, 38, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s15;
    case 1: return casadi_s16;
    case 2: return casadi_s17;
    case 3: return casadi_s18;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s19;
    case 1: return casadi_s20;
    case 2: return casadi_s21;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_lifted_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 264;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
