/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tricycle_frenet_lifted_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[2] = {0, 78};
static const casadi_int casadi_s1[1] = {3};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s5[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s6[3] = {0, 0, 0};
static const casadi_int casadi_s7[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s8[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};

static const casadi_real casadi_c0[78] = {0., 0., 0., 0., 1.2500000000000000e+00, 1.8750000000000000e+00, 2.5000000000000000e+00, 3.1250000000000000e+00, 3.7500000000000000e+00, 4.3750000000000000e+00, 5., 5.2453380000000003e+00, 5.4906769999999998e+00, 5.7360150000000001e+00, 5.9813530000000004e+00, 6.2266919999999999e+00, 6.4720300000000002e+00, 6.7173689999999997e+00, 6.9627070000000000e+00, 7.2080450000000003e+00, 7.4533839999999998e+00, 7.6987220000000001e+00, 7.9440600000000003e+00, 8.1893989999999999e+00, 8.4347370000000002e+00, 8.6800759999999997e+00, 8.9254140000000000e+00, 9.5504140000000000e+00, 1.0175414000000000e+01, 1.0800414000000000e+01, 1.1425414000000000e+01, 1.2050414000000000e+01, 1.2675414000000000e+01, 1.3300414000000000e+01, 1.3925414000000000e+01, 1.4550414000000000e+01, 1.5175414000000000e+01, 1.5800414000000000e+01, 1.6425414000000000e+01, 1.7050414000000000e+01, 1.7675414000000000e+01, 1.8300414000000000e+01, 1.8925414000000000e+01, 1.9550414000000000e+01, 2.0175414000000000e+01, 2.0800414000000000e+01, 2.1425414000000000e+01, 2.2050414000000000e+01, 2.2675414000000000e+01, 2.3300414000000000e+01, 2.3925414000000000e+01, 2.4550414000000000e+01, 2.5175414000000000e+01, 2.5800414000000000e+01, 2.6425414000000000e+01, 2.6670414000000001e+01, 2.6915413999999998e+01, 2.7160413999999999e+01, 2.7405414000000000e+01, 2.7650414000000001e+01, 2.7895413999999999e+01, 2.8140414000000000e+01, 2.8385414000000001e+01, 2.8630413999999998e+01, 2.8875413999999999e+01, 2.9120414000000000e+01, 2.9365414000000001e+01, 2.9610413999999999e+01, 2.9855414000000000e+01, 3.0100414000000001e+01, 3.0345414000000002e+01, 3.0970414000000002e+01, 3.1595414000000002e+01, 3.2220413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01};
static const casadi_real casadi_c1[74] = {1.2294395982889900e-14, 2.7952717679117324e-04, -5.5905435356318612e-04, 8.3858153035421522e-04, -3.1446807387973488e-03, 1.1740141424881839e-02, -4.3815884960733388e-02, 1.6352339841808494e-01, -4.5359350821290079e-01, -3.9131804904117706e-01, -4.0232631547442710e-01, -3.9937666569630093e-01, -4.0016702682177213e-01, -3.9995523005566586e-01, -4.0001205348192193e-01, -3.9999655615703672e-01, -4.0000172191799771e-01, -3.9999655615692303e-01, -4.0001205348240559e-01, -3.9995523013101142e-01, -4.0016702635852186e-01, -3.9937666275747141e-01, -4.0232631527718049e-01, -3.9131804876141540e-01, -4.5359351035250917e-01, 1.6352342149694324e-01, -4.3815968733675381e-02, 1.1740453437773132e-02, -3.1458450174321573e-03, 8.4292663196823363e-04, -2.2586151044492900e-04, 6.0519409813433068e-05, -1.6216128802851870e-05, 4.3451053870444890e-06, -1.1642927324180945e-06, 3.1206553058398549e-07, -8.3969389995630436e-08, 2.3812042704813497e-08, -1.1278800750564135e-08, 2.1303181091743585e-08, -7.3933936459711063e-08, 2.7443256769708847e-07, -1.0237963229360985e-06, 3.8207527061514885e-06, -1.4259214484904430e-05, 5.3216105221296967e-05, -1.9860520639674792e-04, 7.4120472037036500e-04, -2.7662136750929659e-03, 1.0323649980011904e-02, -3.8528386244964706e-02, 1.4378989499985134e-01, -3.9873251976690666e-01, 5.2927500857770626e-01, 3.6536086144625729e-01, 4.0928154563725633e-01, 3.9751295600472114e-01, 4.0066663034386563e-01, 3.9982052261980155e-01, 4.0005127917694722e-01, 3.9997436067239633e-01, 4.0005127813346958e-01, 3.9982052679373425e-01, 4.0066661469158077e-01, 3.9751301443994819e-01, 4.0928132754862945e-01, 3.6536167536552827e-01, 5.2927197098926360e-01, -3.9871375186475705e-01, 1.4359225665263775e-01, -3.7811607028998884e-02, 7.3510662734108756e-01, -1.7642559056186784e+01, 5.6351208730960875e-20};

/* kapparef_s:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* tricycle_frenet_lifted_constr_h_fun:(i0[8],i1[2],i2[],i3[16])->(o0[15]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+4, *cr, *cs;
  casadi_real w0, *w1=w+13, w2, w3, w4, w5, w6, w7, *w8=w+21, w9, w10, w11, w12, w13, w14, w15, w16, w17, w18, w19, w20, w21, *w22=w+36, *w23=w+52, *w24=w+54, *w25=w+56, *w26=w+60, *w27=w+64, *w28=w+66, *w29=w+68, *w30=w+72, *w31=w+76;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #2: @2 = input[0][0] */
  w2 = arg[0] ? arg[0][0] : 0;
  /* #3: @3 = -1.41421 */
  w3 = -1.4142135623730951e+00;
  /* #4: @4 = input[0][2] */
  w4 = arg[0] ? arg[0][2] : 0;
  /* #5: @5 = cos(@4) */
  w5 = cos( w4 );
  /* #6: @3 = (@3*@5) */
  w3 *= w5;
  /* #7: @3 = (@2+@3) */
  w3  = (w2+w3);
  /* #8: @5 = input[0][1] */
  w5 = arg[0] ? arg[0][1] : 0;
  /* #9: @6 = -1.41421 */
  w6 = -1.4142135623730951e+00;
  /* #10: @7 = sin(@4) */
  w7 = sin( w4 );
  /* #11: @6 = (@6*@7) */
  w6 *= w7;
  /* #12: @6 = (@5+@6) */
  w6  = (w5+w6);
  /* #13: @8 = vertcat(@3, @6) */
  rr=w8;
  *rr++ = w3;
  *rr++ = w6;
  /* #14: @3 = input[3][0] */
  w3 = arg[3] ? arg[3][0] : 0;
  /* #15: @6 = input[3][1] */
  w6 = arg[3] ? arg[3][1] : 0;
  /* #16: @7 = input[3][2] */
  w7 = arg[3] ? arg[3][2] : 0;
  /* #17: @9 = input[3][3] */
  w9 = arg[3] ? arg[3][3] : 0;
  /* #18: @10 = input[3][4] */
  w10 = arg[3] ? arg[3][4] : 0;
  /* #19: @11 = input[3][5] */
  w11 = arg[3] ? arg[3][5] : 0;
  /* #20: @12 = input[3][6] */
  w12 = arg[3] ? arg[3][6] : 0;
  /* #21: @13 = input[3][7] */
  w13 = arg[3] ? arg[3][7] : 0;
  /* #22: @14 = input[3][8] */
  w14 = arg[3] ? arg[3][8] : 0;
  /* #23: @15 = input[3][9] */
  w15 = arg[3] ? arg[3][9] : 0;
  /* #24: @16 = input[3][10] */
  w16 = arg[3] ? arg[3][10] : 0;
  /* #25: @17 = input[3][11] */
  w17 = arg[3] ? arg[3][11] : 0;
  /* #26: @18 = input[3][12] */
  w18 = arg[3] ? arg[3][12] : 0;
  /* #27: @19 = input[3][13] */
  w19 = arg[3] ? arg[3][13] : 0;
  /* #28: @20 = input[3][14] */
  w20 = arg[3] ? arg[3][14] : 0;
  /* #29: @21 = input[3][15] */
  w21 = arg[3] ? arg[3][15] : 0;
  /* #30: @22 = vertcat(@3, @6, @7, @9, @10, @11, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21) */
  rr=w22;
  *rr++ = w3;
  *rr++ = w6;
  *rr++ = w7;
  *rr++ = w9;
  *rr++ = w10;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w21;
  /* #31: @23 = @22[:2] */
  for (rr=w23, ss=w22+0; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #32: @23 = (@8-@23) */
  for (i=0, rr=w23, cr=w8, cs=w23; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #33: @24 = @23' */
  casadi_copy(w23, 2, w24);
  /* #34: @25 = zeros(2x2) */
  casadi_clear(w25, 4);
  /* #35: @26 = zeros(2x2) */
  casadi_clear(w26, 4);
  /* #36: @3 = cos(@9) */
  w3 = cos( w9 );
  /* #37: @6 = sin(@9) */
  w6 = sin( w9 );
  /* #38: @6 = (-@6) */
  w6 = (- w6 );
  /* #39: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #40: @27 = @27' */
  /* #41: @3 = sin(@9) */
  w3 = sin( w9 );
  /* #42: @6 = cos(@9) */
  w6 = cos( w9 );
  /* #43: @28 = horzcat(@3, @6) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w6;
  /* #44: @28 = @28' */
  /* #45: @29 = horzcat(@27, @28) */
  rr=w29;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #46: @3 = 1 */
  w3 = 1.;
  /* #47: @6 = 1.5 */
  w6 = 1.5000000000000000e+00;
  /* #48: @6 = (@6*@7) */
  w6 *= w7;
  /* #49: @3 = (@3+@6) */
  w3 += w6;
  /* #50: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #51: @3 = (1./@3) */
  w3 = (1./ w3 );
  /* #52: @6 = 0 */
  w6 = 0.;
  /* #53: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #54: @27 = @27' */
  /* #55: @3 = 0 */
  w3 = 0.;
  /* #56: @6 = 1 */
  w6 = 1.;
  /* #57: @6 = (@6+@7) */
  w6 += w7;
  /* #58: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #59: @6 = (1./@6) */
  w6 = (1./ w6 );
  /* #60: @28 = horzcat(@3, @6) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w6;
  /* #61: @28 = @28' */
  /* #62: @30 = horzcat(@27, @28) */
  rr=w30;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #63: @31 = @30' */
  for (i=0, rr=w31, cs=w30; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #64: @26 = mac(@29,@31,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w29+j, tt=w31+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #65: @31 = @29' */
  for (i=0, rr=w31, cs=w29; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #66: @25 = mac(@26,@31,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w26+j, tt=w31+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #67: @1 = mac(@24,@25,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #68: @0 = mac(@1,@23,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #69: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #70: @3 = 1 */
  w3 = 1.;
  /* #71: @0 = (@0-@3) */
  w0 -= w3;
  /* #72: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #73: @0 = 0 */
  w0 = 0.;
  /* #74: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #75: @23 = @22[4:6] */
  for (rr=w23, ss=w22+4; ss!=w22+6; ss+=1) *rr++ = *ss;
  /* #76: @23 = (@8-@23) */
  for (i=0, rr=w23, cr=w8, cs=w23; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #77: @24 = @23' */
  casadi_copy(w23, 2, w24);
  /* #78: @25 = zeros(2x2) */
  casadi_clear(w25, 4);
  /* #79: @26 = zeros(2x2) */
  casadi_clear(w26, 4);
  /* #80: @3 = cos(@13) */
  w3 = cos( w13 );
  /* #81: @6 = sin(@13) */
  w6 = sin( w13 );
  /* #82: @6 = (-@6) */
  w6 = (- w6 );
  /* #83: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #84: @27 = @27' */
  /* #85: @3 = sin(@13) */
  w3 = sin( w13 );
  /* #86: @6 = cos(@13) */
  w6 = cos( w13 );
  /* #87: @28 = horzcat(@3, @6) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w6;
  /* #88: @28 = @28' */
  /* #89: @31 = horzcat(@27, @28) */
  rr=w31;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #90: @3 = 1 */
  w3 = 1.;
  /* #91: @6 = 1.5 */
  w6 = 1.5000000000000000e+00;
  /* #92: @6 = (@6*@12) */
  w6 *= w12;
  /* #93: @3 = (@3+@6) */
  w3 += w6;
  /* #94: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #95: @3 = (1./@3) */
  w3 = (1./ w3 );
  /* #96: @6 = 0 */
  w6 = 0.;
  /* #97: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #98: @27 = @27' */
  /* #99: @3 = 0 */
  w3 = 0.;
  /* #100: @6 = 1 */
  w6 = 1.;
  /* #101: @6 = (@6+@12) */
  w6 += w12;
  /* #102: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #103: @6 = (1./@6) */
  w6 = (1./ w6 );
  /* #104: @28 = horzcat(@3, @6) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w6;
  /* #105: @28 = @28' */
  /* #106: @29 = horzcat(@27, @28) */
  rr=w29;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #107: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #108: @26 = mac(@31,@30,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w30+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #109: @30 = @31' */
  for (i=0, rr=w30, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #110: @25 = mac(@26,@30,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w26+j, tt=w30+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #111: @1 = mac(@24,@25,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #112: @0 = mac(@1,@23,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #113: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #114: @3 = 1 */
  w3 = 1.;
  /* #115: @0 = (@0-@3) */
  w0 -= w3;
  /* #116: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #117: @0 = 0 */
  w0 = 0.;
  /* #118: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #119: @23 = @22[8:10] */
  for (rr=w23, ss=w22+8; ss!=w22+10; ss+=1) *rr++ = *ss;
  /* #120: @23 = (@8-@23) */
  for (i=0, rr=w23, cr=w8, cs=w23; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #121: @24 = @23' */
  casadi_copy(w23, 2, w24);
  /* #122: @25 = zeros(2x2) */
  casadi_clear(w25, 4);
  /* #123: @26 = zeros(2x2) */
  casadi_clear(w26, 4);
  /* #124: @3 = cos(@17) */
  w3 = cos( w17 );
  /* #125: @6 = sin(@17) */
  w6 = sin( w17 );
  /* #126: @6 = (-@6) */
  w6 = (- w6 );
  /* #127: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #128: @27 = @27' */
  /* #129: @3 = sin(@17) */
  w3 = sin( w17 );
  /* #130: @6 = cos(@17) */
  w6 = cos( w17 );
  /* #131: @28 = horzcat(@3, @6) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w6;
  /* #132: @28 = @28' */
  /* #133: @30 = horzcat(@27, @28) */
  rr=w30;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #134: @3 = 1 */
  w3 = 1.;
  /* #135: @6 = 1.5 */
  w6 = 1.5000000000000000e+00;
  /* #136: @6 = (@6*@16) */
  w6 *= w16;
  /* #137: @3 = (@3+@6) */
  w3 += w6;
  /* #138: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #139: @3 = (1./@3) */
  w3 = (1./ w3 );
  /* #140: @6 = 0 */
  w6 = 0.;
  /* #141: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #142: @27 = @27' */
  /* #143: @3 = 0 */
  w3 = 0.;
  /* #144: @6 = 1 */
  w6 = 1.;
  /* #145: @6 = (@6+@16) */
  w6 += w16;
  /* #146: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #147: @6 = (1./@6) */
  w6 = (1./ w6 );
  /* #148: @28 = horzcat(@3, @6) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w6;
  /* #149: @28 = @28' */
  /* #150: @31 = horzcat(@27, @28) */
  rr=w31;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #151: @29 = @31' */
  for (i=0, rr=w29, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #152: @26 = mac(@30,@29,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w30+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #153: @29 = @30' */
  for (i=0, rr=w29, cs=w30; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #154: @25 = mac(@26,@29,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w26+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #155: @1 = mac(@24,@25,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #156: @0 = mac(@1,@23,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #157: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #158: @3 = 1 */
  w3 = 1.;
  /* #159: @0 = (@0-@3) */
  w0 -= w3;
  /* #160: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #161: @0 = 0 */
  w0 = 0.;
  /* #162: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #163: @23 = @22[12:14] */
  for (rr=w23, ss=w22+12; ss!=w22+14; ss+=1) *rr++ = *ss;
  /* #164: @8 = (@8-@23) */
  for (i=0, rr=w8, cs=w23; i<2; ++i) (*rr++) -= (*cs++);
  /* #165: @23 = @8' */
  casadi_copy(w8, 2, w23);
  /* #166: @25 = zeros(2x2) */
  casadi_clear(w25, 4);
  /* #167: @26 = zeros(2x2) */
  casadi_clear(w26, 4);
  /* #168: @3 = cos(@21) */
  w3 = cos( w21 );
  /* #169: @6 = sin(@21) */
  w6 = sin( w21 );
  /* #170: @6 = (-@6) */
  w6 = (- w6 );
  /* #171: @24 = horzcat(@3, @6) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w6;
  /* #172: @24 = @24' */
  /* #173: @3 = sin(@21) */
  w3 = sin( w21 );
  /* #174: @6 = cos(@21) */
  w6 = cos( w21 );
  /* #175: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #176: @27 = @27' */
  /* #177: @29 = horzcat(@24, @27) */
  rr=w29;
  for (i=0, cs=w24; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #178: @3 = 1 */
  w3 = 1.;
  /* #179: @6 = 1.5 */
  w6 = 1.5000000000000000e+00;
  /* #180: @6 = (@6*@20) */
  w6 *= w20;
  /* #181: @3 = (@3+@6) */
  w3 += w6;
  /* #182: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #183: @3 = (1./@3) */
  w3 = (1./ w3 );
  /* #184: @6 = 0 */
  w6 = 0.;
  /* #185: @24 = horzcat(@3, @6) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w6;
  /* #186: @24 = @24' */
  /* #187: @3 = 0 */
  w3 = 0.;
  /* #188: @6 = 1 */
  w6 = 1.;
  /* #189: @6 = (@6+@20) */
  w6 += w20;
  /* #190: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #191: @6 = (1./@6) */
  w6 = (1./ w6 );
  /* #192: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #193: @27 = @27' */
  /* #194: @30 = horzcat(@24, @27) */
  rr=w30;
  for (i=0, cs=w24; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #195: @31 = @30' */
  for (i=0, rr=w31, cs=w30; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #196: @26 = mac(@29,@31,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w29+j, tt=w31+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #197: @31 = @29' */
  for (i=0, rr=w31, cs=w29; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #198: @25 = mac(@26,@31,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w26+j, tt=w31+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #199: @1 = mac(@23,@25,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #200: @0 = mac(@1,@8,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w8+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #201: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #202: @3 = 1 */
  w3 = 1.;
  /* #203: @0 = (@0-@3) */
  w0 -= w3;
  /* #204: output[0][3] = @0 */
  if (res[0]) res[0][3] = w0;
  /* #205: @0 = 0 */
  w0 = 0.;
  /* #206: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #207: @8 = vertcat(@2, @5) */
  rr=w8;
  *rr++ = w2;
  *rr++ = w5;
  /* #208: @23 = @22[:2] */
  for (rr=w23, ss=w22+0; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #209: @23 = (@8-@23) */
  for (i=0, rr=w23, cr=w8, cs=w23; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #210: @24 = @23' */
  casadi_copy(w23, 2, w24);
  /* #211: @25 = zeros(2x2) */
  casadi_clear(w25, 4);
  /* #212: @26 = zeros(2x2) */
  casadi_clear(w26, 4);
  /* #213: @3 = cos(@9) */
  w3 = cos( w9 );
  /* #214: @6 = sin(@9) */
  w6 = sin( w9 );
  /* #215: @6 = (-@6) */
  w6 = (- w6 );
  /* #216: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #217: @27 = @27' */
  /* #218: @3 = sin(@9) */
  w3 = sin( w9 );
  /* #219: @6 = cos(@9) */
  w6 = cos( w9 );
  /* #220: @28 = horzcat(@3, @6) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w6;
  /* #221: @28 = @28' */
  /* #222: @31 = horzcat(@27, @28) */
  rr=w31;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #223: @3 = 1 */
  w3 = 1.;
  /* #224: @6 = 1.5 */
  w6 = 1.5000000000000000e+00;
  /* #225: @6 = (@6*@7) */
  w6 *= w7;
  /* #226: @3 = (@3+@6) */
  w3 += w6;
  /* #227: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #228: @3 = (1./@3) */
  w3 = (1./ w3 );
  /* #229: @6 = 0 */
  w6 = 0.;
  /* #230: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #231: @27 = @27' */
  /* #232: @3 = 0 */
  w3 = 0.;
  /* #233: @6 = 1 */
  w6 = 1.;
  /* #234: @6 = (@6+@7) */
  w6 += w7;
  /* #235: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #236: @6 = (1./@6) */
  w6 = (1./ w6 );
  /* #237: @28 = horzcat(@3, @6) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w6;
  /* #238: @28 = @28' */
  /* #239: @29 = horzcat(@27, @28) */
  rr=w29;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #240: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #241: @26 = mac(@31,@30,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w30+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #242: @30 = @31' */
  for (i=0, rr=w30, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #243: @25 = mac(@26,@30,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w26+j, tt=w30+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #244: @1 = mac(@24,@25,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #245: @0 = mac(@1,@23,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #246: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #247: @3 = 1 */
  w3 = 1.;
  /* #248: @0 = (@0-@3) */
  w0 -= w3;
  /* #249: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  /* #250: @0 = 0 */
  w0 = 0.;
  /* #251: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #252: @23 = @22[4:6] */
  for (rr=w23, ss=w22+4; ss!=w22+6; ss+=1) *rr++ = *ss;
  /* #253: @23 = (@8-@23) */
  for (i=0, rr=w23, cr=w8, cs=w23; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #254: @24 = @23' */
  casadi_copy(w23, 2, w24);
  /* #255: @25 = zeros(2x2) */
  casadi_clear(w25, 4);
  /* #256: @26 = zeros(2x2) */
  casadi_clear(w26, 4);
  /* #257: @3 = cos(@13) */
  w3 = cos( w13 );
  /* #258: @6 = sin(@13) */
  w6 = sin( w13 );
  /* #259: @6 = (-@6) */
  w6 = (- w6 );
  /* #260: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #261: @27 = @27' */
  /* #262: @3 = sin(@13) */
  w3 = sin( w13 );
  /* #263: @6 = cos(@13) */
  w6 = cos( w13 );
  /* #264: @28 = horzcat(@3, @6) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w6;
  /* #265: @28 = @28' */
  /* #266: @30 = horzcat(@27, @28) */
  rr=w30;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #267: @3 = 1 */
  w3 = 1.;
  /* #268: @6 = 1.5 */
  w6 = 1.5000000000000000e+00;
  /* #269: @6 = (@6*@12) */
  w6 *= w12;
  /* #270: @3 = (@3+@6) */
  w3 += w6;
  /* #271: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #272: @3 = (1./@3) */
  w3 = (1./ w3 );
  /* #273: @6 = 0 */
  w6 = 0.;
  /* #274: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #275: @27 = @27' */
  /* #276: @3 = 0 */
  w3 = 0.;
  /* #277: @6 = 1 */
  w6 = 1.;
  /* #278: @6 = (@6+@12) */
  w6 += w12;
  /* #279: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #280: @6 = (1./@6) */
  w6 = (1./ w6 );
  /* #281: @28 = horzcat(@3, @6) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w6;
  /* #282: @28 = @28' */
  /* #283: @31 = horzcat(@27, @28) */
  rr=w31;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #284: @29 = @31' */
  for (i=0, rr=w29, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #285: @26 = mac(@30,@29,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w30+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #286: @29 = @30' */
  for (i=0, rr=w29, cs=w30; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #287: @25 = mac(@26,@29,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w26+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #288: @1 = mac(@24,@25,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #289: @0 = mac(@1,@23,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #290: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #291: @3 = 1 */
  w3 = 1.;
  /* #292: @0 = (@0-@3) */
  w0 -= w3;
  /* #293: output[0][5] = @0 */
  if (res[0]) res[0][5] = w0;
  /* #294: @0 = 0 */
  w0 = 0.;
  /* #295: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #296: @23 = @22[8:10] */
  for (rr=w23, ss=w22+8; ss!=w22+10; ss+=1) *rr++ = *ss;
  /* #297: @23 = (@8-@23) */
  for (i=0, rr=w23, cr=w8, cs=w23; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #298: @24 = @23' */
  casadi_copy(w23, 2, w24);
  /* #299: @25 = zeros(2x2) */
  casadi_clear(w25, 4);
  /* #300: @26 = zeros(2x2) */
  casadi_clear(w26, 4);
  /* #301: @3 = cos(@17) */
  w3 = cos( w17 );
  /* #302: @6 = sin(@17) */
  w6 = sin( w17 );
  /* #303: @6 = (-@6) */
  w6 = (- w6 );
  /* #304: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #305: @27 = @27' */
  /* #306: @3 = sin(@17) */
  w3 = sin( w17 );
  /* #307: @6 = cos(@17) */
  w6 = cos( w17 );
  /* #308: @28 = horzcat(@3, @6) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w6;
  /* #309: @28 = @28' */
  /* #310: @29 = horzcat(@27, @28) */
  rr=w29;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #311: @3 = 1 */
  w3 = 1.;
  /* #312: @6 = 1.5 */
  w6 = 1.5000000000000000e+00;
  /* #313: @6 = (@6*@16) */
  w6 *= w16;
  /* #314: @3 = (@3+@6) */
  w3 += w6;
  /* #315: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #316: @3 = (1./@3) */
  w3 = (1./ w3 );
  /* #317: @6 = 0 */
  w6 = 0.;
  /* #318: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #319: @27 = @27' */
  /* #320: @3 = 0 */
  w3 = 0.;
  /* #321: @6 = 1 */
  w6 = 1.;
  /* #322: @6 = (@6+@16) */
  w6 += w16;
  /* #323: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #324: @6 = (1./@6) */
  w6 = (1./ w6 );
  /* #325: @28 = horzcat(@3, @6) */
  rr=w28;
  *rr++ = w3;
  *rr++ = w6;
  /* #326: @28 = @28' */
  /* #327: @30 = horzcat(@27, @28) */
  rr=w30;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #328: @31 = @30' */
  for (i=0, rr=w31, cs=w30; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #329: @26 = mac(@29,@31,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w29+j, tt=w31+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #330: @31 = @29' */
  for (i=0, rr=w31, cs=w29; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #331: @25 = mac(@26,@31,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w26+j, tt=w31+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #332: @1 = mac(@24,@25,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #333: @0 = mac(@1,@23,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #334: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #335: @3 = 1 */
  w3 = 1.;
  /* #336: @0 = (@0-@3) */
  w0 -= w3;
  /* #337: output[0][6] = @0 */
  if (res[0]) res[0][6] = w0;
  /* #338: @0 = 0 */
  w0 = 0.;
  /* #339: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #340: @23 = @22[12:14] */
  for (rr=w23, ss=w22+12; ss!=w22+14; ss+=1) *rr++ = *ss;
  /* #341: @8 = (@8-@23) */
  for (i=0, rr=w8, cs=w23; i<2; ++i) (*rr++) -= (*cs++);
  /* #342: @23 = @8' */
  casadi_copy(w8, 2, w23);
  /* #343: @25 = zeros(2x2) */
  casadi_clear(w25, 4);
  /* #344: @26 = zeros(2x2) */
  casadi_clear(w26, 4);
  /* #345: @3 = cos(@21) */
  w3 = cos( w21 );
  /* #346: @6 = sin(@21) */
  w6 = sin( w21 );
  /* #347: @6 = (-@6) */
  w6 = (- w6 );
  /* #348: @24 = horzcat(@3, @6) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w6;
  /* #349: @24 = @24' */
  /* #350: @3 = sin(@21) */
  w3 = sin( w21 );
  /* #351: @6 = cos(@21) */
  w6 = cos( w21 );
  /* #352: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #353: @27 = @27' */
  /* #354: @31 = horzcat(@24, @27) */
  rr=w31;
  for (i=0, cs=w24; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #355: @3 = 1 */
  w3 = 1.;
  /* #356: @6 = 1.5 */
  w6 = 1.5000000000000000e+00;
  /* #357: @6 = (@6*@20) */
  w6 *= w20;
  /* #358: @3 = (@3+@6) */
  w3 += w6;
  /* #359: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #360: @3 = (1./@3) */
  w3 = (1./ w3 );
  /* #361: @6 = 0 */
  w6 = 0.;
  /* #362: @24 = horzcat(@3, @6) */
  rr=w24;
  *rr++ = w3;
  *rr++ = w6;
  /* #363: @24 = @24' */
  /* #364: @3 = 0 */
  w3 = 0.;
  /* #365: @6 = 1 */
  w6 = 1.;
  /* #366: @6 = (@6+@20) */
  w6 += w20;
  /* #367: @6 = sq(@6) */
  w6 = casadi_sq( w6 );
  /* #368: @6 = (1./@6) */
  w6 = (1./ w6 );
  /* #369: @27 = horzcat(@3, @6) */
  rr=w27;
  *rr++ = w3;
  *rr++ = w6;
  /* #370: @27 = @27' */
  /* #371: @29 = horzcat(@24, @27) */
  rr=w29;
  for (i=0, cs=w24; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #372: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #373: @26 = mac(@31,@30,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w30+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #374: @30 = @31' */
  for (i=0, rr=w30, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #375: @25 = mac(@26,@30,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w26+j, tt=w30+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #376: @1 = mac(@23,@25,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #377: @0 = mac(@1,@8,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w8+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #378: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #379: @3 = 1 */
  w3 = 1.;
  /* #380: @0 = (@0-@3) */
  w0 -= w3;
  /* #381: output[0][7] = @0 */
  if (res[0]) res[0][7] = w0;
  /* #382: @0 = 0 */
  w0 = 0.;
  /* #383: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #384: @3 = 1.41421 */
  w3 = 1.4142135623730951e+00;
  /* #385: @6 = cos(@4) */
  w6 = cos( w4 );
  /* #386: @3 = (@3*@6) */
  w3 *= w6;
  /* #387: @2 = (@2+@3) */
  w2 += w3;
  /* #388: @3 = 1.41421 */
  w3 = 1.4142135623730951e+00;
  /* #389: @4 = sin(@4) */
  w4 = sin( w4 );
  /* #390: @3 = (@3*@4) */
  w3 *= w4;
  /* #391: @5 = (@5+@3) */
  w5 += w3;
  /* #392: @8 = vertcat(@2, @5) */
  rr=w8;
  *rr++ = w2;
  *rr++ = w5;
  /* #393: @23 = @22[:2] */
  for (rr=w23, ss=w22+0; ss!=w22+2; ss+=1) *rr++ = *ss;
  /* #394: @23 = (@8-@23) */
  for (i=0, rr=w23, cr=w8, cs=w23; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #395: @24 = @23' */
  casadi_copy(w23, 2, w24);
  /* #396: @25 = zeros(2x2) */
  casadi_clear(w25, 4);
  /* #397: @26 = zeros(2x2) */
  casadi_clear(w26, 4);
  /* #398: @2 = cos(@9) */
  w2 = cos( w9 );
  /* #399: @5 = sin(@9) */
  w5 = sin( w9 );
  /* #400: @5 = (-@5) */
  w5 = (- w5 );
  /* #401: @27 = horzcat(@2, @5) */
  rr=w27;
  *rr++ = w2;
  *rr++ = w5;
  /* #402: @27 = @27' */
  /* #403: @2 = sin(@9) */
  w2 = sin( w9 );
  /* #404: @9 = cos(@9) */
  w9 = cos( w9 );
  /* #405: @28 = horzcat(@2, @9) */
  rr=w28;
  *rr++ = w2;
  *rr++ = w9;
  /* #406: @28 = @28' */
  /* #407: @30 = horzcat(@27, @28) */
  rr=w30;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #408: @2 = 1 */
  w2 = 1.;
  /* #409: @9 = 1.5 */
  w9 = 1.5000000000000000e+00;
  /* #410: @9 = (@9*@7) */
  w9 *= w7;
  /* #411: @2 = (@2+@9) */
  w2 += w9;
  /* #412: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #413: @2 = (1./@2) */
  w2 = (1./ w2 );
  /* #414: @9 = 0 */
  w9 = 0.;
  /* #415: @27 = horzcat(@2, @9) */
  rr=w27;
  *rr++ = w2;
  *rr++ = w9;
  /* #416: @27 = @27' */
  /* #417: @2 = 0 */
  w2 = 0.;
  /* #418: @9 = 1 */
  w9 = 1.;
  /* #419: @9 = (@9+@7) */
  w9 += w7;
  /* #420: @9 = sq(@9) */
  w9 = casadi_sq( w9 );
  /* #421: @9 = (1./@9) */
  w9 = (1./ w9 );
  /* #422: @28 = horzcat(@2, @9) */
  rr=w28;
  *rr++ = w2;
  *rr++ = w9;
  /* #423: @28 = @28' */
  /* #424: @31 = horzcat(@27, @28) */
  rr=w31;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #425: @29 = @31' */
  for (i=0, rr=w29, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #426: @26 = mac(@30,@29,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w30+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #427: @29 = @30' */
  for (i=0, rr=w29, cs=w30; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #428: @25 = mac(@26,@29,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w26+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #429: @1 = mac(@24,@25,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #430: @0 = mac(@1,@23,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #431: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #432: @2 = 1 */
  w2 = 1.;
  /* #433: @0 = (@0-@2) */
  w0 -= w2;
  /* #434: output[0][8] = @0 */
  if (res[0]) res[0][8] = w0;
  /* #435: @0 = 0 */
  w0 = 0.;
  /* #436: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #437: @23 = @22[4:6] */
  for (rr=w23, ss=w22+4; ss!=w22+6; ss+=1) *rr++ = *ss;
  /* #438: @23 = (@8-@23) */
  for (i=0, rr=w23, cr=w8, cs=w23; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #439: @24 = @23' */
  casadi_copy(w23, 2, w24);
  /* #440: @25 = zeros(2x2) */
  casadi_clear(w25, 4);
  /* #441: @26 = zeros(2x2) */
  casadi_clear(w26, 4);
  /* #442: @2 = cos(@13) */
  w2 = cos( w13 );
  /* #443: @9 = sin(@13) */
  w9 = sin( w13 );
  /* #444: @9 = (-@9) */
  w9 = (- w9 );
  /* #445: @27 = horzcat(@2, @9) */
  rr=w27;
  *rr++ = w2;
  *rr++ = w9;
  /* #446: @27 = @27' */
  /* #447: @2 = sin(@13) */
  w2 = sin( w13 );
  /* #448: @13 = cos(@13) */
  w13 = cos( w13 );
  /* #449: @28 = horzcat(@2, @13) */
  rr=w28;
  *rr++ = w2;
  *rr++ = w13;
  /* #450: @28 = @28' */
  /* #451: @29 = horzcat(@27, @28) */
  rr=w29;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #452: @2 = 1 */
  w2 = 1.;
  /* #453: @13 = 1.5 */
  w13 = 1.5000000000000000e+00;
  /* #454: @13 = (@13*@12) */
  w13 *= w12;
  /* #455: @2 = (@2+@13) */
  w2 += w13;
  /* #456: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #457: @2 = (1./@2) */
  w2 = (1./ w2 );
  /* #458: @13 = 0 */
  w13 = 0.;
  /* #459: @27 = horzcat(@2, @13) */
  rr=w27;
  *rr++ = w2;
  *rr++ = w13;
  /* #460: @27 = @27' */
  /* #461: @2 = 0 */
  w2 = 0.;
  /* #462: @13 = 1 */
  w13 = 1.;
  /* #463: @13 = (@13+@12) */
  w13 += w12;
  /* #464: @13 = sq(@13) */
  w13 = casadi_sq( w13 );
  /* #465: @13 = (1./@13) */
  w13 = (1./ w13 );
  /* #466: @28 = horzcat(@2, @13) */
  rr=w28;
  *rr++ = w2;
  *rr++ = w13;
  /* #467: @28 = @28' */
  /* #468: @30 = horzcat(@27, @28) */
  rr=w30;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #469: @31 = @30' */
  for (i=0, rr=w31, cs=w30; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #470: @26 = mac(@29,@31,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w29+j, tt=w31+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #471: @31 = @29' */
  for (i=0, rr=w31, cs=w29; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #472: @25 = mac(@26,@31,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w26+j, tt=w31+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #473: @1 = mac(@24,@25,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #474: @0 = mac(@1,@23,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #475: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #476: @2 = 1 */
  w2 = 1.;
  /* #477: @0 = (@0-@2) */
  w0 -= w2;
  /* #478: output[0][9] = @0 */
  if (res[0]) res[0][9] = w0;
  /* #479: @0 = 0 */
  w0 = 0.;
  /* #480: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #481: @23 = @22[8:10] */
  for (rr=w23, ss=w22+8; ss!=w22+10; ss+=1) *rr++ = *ss;
  /* #482: @23 = (@8-@23) */
  for (i=0, rr=w23, cr=w8, cs=w23; i<2; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #483: @24 = @23' */
  casadi_copy(w23, 2, w24);
  /* #484: @25 = zeros(2x2) */
  casadi_clear(w25, 4);
  /* #485: @26 = zeros(2x2) */
  casadi_clear(w26, 4);
  /* #486: @2 = cos(@17) */
  w2 = cos( w17 );
  /* #487: @13 = sin(@17) */
  w13 = sin( w17 );
  /* #488: @13 = (-@13) */
  w13 = (- w13 );
  /* #489: @27 = horzcat(@2, @13) */
  rr=w27;
  *rr++ = w2;
  *rr++ = w13;
  /* #490: @27 = @27' */
  /* #491: @2 = sin(@17) */
  w2 = sin( w17 );
  /* #492: @17 = cos(@17) */
  w17 = cos( w17 );
  /* #493: @28 = horzcat(@2, @17) */
  rr=w28;
  *rr++ = w2;
  *rr++ = w17;
  /* #494: @28 = @28' */
  /* #495: @31 = horzcat(@27, @28) */
  rr=w31;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #496: @2 = 1 */
  w2 = 1.;
  /* #497: @17 = 1.5 */
  w17 = 1.5000000000000000e+00;
  /* #498: @17 = (@17*@16) */
  w17 *= w16;
  /* #499: @2 = (@2+@17) */
  w2 += w17;
  /* #500: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #501: @2 = (1./@2) */
  w2 = (1./ w2 );
  /* #502: @17 = 0 */
  w17 = 0.;
  /* #503: @27 = horzcat(@2, @17) */
  rr=w27;
  *rr++ = w2;
  *rr++ = w17;
  /* #504: @27 = @27' */
  /* #505: @2 = 0 */
  w2 = 0.;
  /* #506: @17 = 1 */
  w17 = 1.;
  /* #507: @17 = (@17+@16) */
  w17 += w16;
  /* #508: @17 = sq(@17) */
  w17 = casadi_sq( w17 );
  /* #509: @17 = (1./@17) */
  w17 = (1./ w17 );
  /* #510: @28 = horzcat(@2, @17) */
  rr=w28;
  *rr++ = w2;
  *rr++ = w17;
  /* #511: @28 = @28' */
  /* #512: @29 = horzcat(@27, @28) */
  rr=w29;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<2; ++i) *rr++ = *cs++;
  /* #513: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #514: @26 = mac(@31,@30,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w31+j, tt=w30+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #515: @30 = @31' */
  for (i=0, rr=w30, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #516: @25 = mac(@26,@30,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w26+j, tt=w30+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #517: @1 = mac(@24,@25,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w24+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #518: @0 = mac(@1,@23,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w23+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #519: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #520: @2 = 1 */
  w2 = 1.;
  /* #521: @0 = (@0-@2) */
  w0 -= w2;
  /* #522: output[0][10] = @0 */
  if (res[0]) res[0][10] = w0;
  /* #523: @0 = 0 */
  w0 = 0.;
  /* #524: @1 = zeros(1x2) */
  casadi_clear(w1, 2);
  /* #525: @23 = @22[12:14] */
  for (rr=w23, ss=w22+12; ss!=w22+14; ss+=1) *rr++ = *ss;
  /* #526: @8 = (@8-@23) */
  for (i=0, rr=w8, cs=w23; i<2; ++i) (*rr++) -= (*cs++);
  /* #527: @23 = @8' */
  casadi_copy(w8, 2, w23);
  /* #528: @25 = zeros(2x2) */
  casadi_clear(w25, 4);
  /* #529: @26 = zeros(2x2) */
  casadi_clear(w26, 4);
  /* #530: @2 = cos(@21) */
  w2 = cos( w21 );
  /* #531: @17 = sin(@21) */
  w17 = sin( w21 );
  /* #532: @17 = (-@17) */
  w17 = (- w17 );
  /* #533: @24 = horzcat(@2, @17) */
  rr=w24;
  *rr++ = w2;
  *rr++ = w17;
  /* #534: @24 = @24' */
  /* #535: @2 = sin(@21) */
  w2 = sin( w21 );
  /* #536: @21 = cos(@21) */
  w21 = cos( w21 );
  /* #537: @27 = horzcat(@2, @21) */
  rr=w27;
  *rr++ = w2;
  *rr++ = w21;
  /* #538: @27 = @27' */
  /* #539: @30 = horzcat(@24, @27) */
  rr=w30;
  for (i=0, cs=w24; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #540: @2 = 1 */
  w2 = 1.;
  /* #541: @21 = 1.5 */
  w21 = 1.5000000000000000e+00;
  /* #542: @21 = (@21*@20) */
  w21 *= w20;
  /* #543: @2 = (@2+@21) */
  w2 += w21;
  /* #544: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #545: @2 = (1./@2) */
  w2 = (1./ w2 );
  /* #546: @21 = 0 */
  w21 = 0.;
  /* #547: @24 = horzcat(@2, @21) */
  rr=w24;
  *rr++ = w2;
  *rr++ = w21;
  /* #548: @24 = @24' */
  /* #549: @2 = 0 */
  w2 = 0.;
  /* #550: @21 = 1 */
  w21 = 1.;
  /* #551: @21 = (@21+@20) */
  w21 += w20;
  /* #552: @21 = sq(@21) */
  w21 = casadi_sq( w21 );
  /* #553: @21 = (1./@21) */
  w21 = (1./ w21 );
  /* #554: @27 = horzcat(@2, @21) */
  rr=w27;
  *rr++ = w2;
  *rr++ = w21;
  /* #555: @27 = @27' */
  /* #556: @31 = horzcat(@24, @27) */
  rr=w31;
  for (i=0, cs=w24; i<2; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<2; ++i) *rr++ = *cs++;
  /* #557: @29 = @31' */
  for (i=0, rr=w29, cs=w31; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #558: @26 = mac(@30,@29,@26) */
  for (i=0, rr=w26; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w30+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #559: @29 = @30' */
  for (i=0, rr=w29, cs=w30; i<2; ++i) for (j=0; j<2; ++j) rr[i+j*2] = *cs++;
  /* #560: @25 = mac(@26,@29,@25) */
  for (i=0, rr=w25; i<2; ++i) for (j=0; j<2; ++j, ++rr) for (k=0, ss=w26+j, tt=w29+i*2; k<2; ++k) *rr += ss[k*2]**tt++;
  /* #561: @1 = mac(@23,@25,@1) */
  for (i=0, rr=w1; i<2; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w23+j, tt=w25+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #562: @0 = mac(@1,@8,@0) */
  for (i=0, rr=(&w0); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w1+j, tt=w8+i*2; k<2; ++k) *rr += ss[k*1]**tt++;
  /* #563: @0 = sqrt(@0) */
  w0 = sqrt( w0 );
  /* #564: @2 = 1 */
  w2 = 1.;
  /* #565: @0 = (@0-@2) */
  w0 -= w2;
  /* #566: output[0][11] = @0 */
  if (res[0]) res[0][11] = w0;
  /* #567: @0 = input[0][6] */
  w0 = arg[0] ? arg[0][6] : 0;
  /* #568: @2 = input[0][7] */
  w2 = arg[0] ? arg[0][7] : 0;
  /* #569: @21 = cos(@2) */
  w21 = cos( w2 );
  /* #570: @21 = (@0*@21) */
  w21  = (w0*w21);
  /* #571: output[0][12] = @21 */
  if (res[0]) res[0][12] = w21;
  /* #572: @2 = sin(@2) */
  w2 = sin( w2 );
  /* #573: @0 = (@0*@2) */
  w0 *= w2;
  /* #574: @2 = 1.03 */
  w2 = 1.0300000000000000e+00;
  /* #575: @0 = (@0/@2) */
  w0 /= w2;
  /* #576: output[0][13] = @0 */
  if (res[0]) res[0][13] = w0;
  /* #577: @0 = input[0][3] */
  w0 = arg[0] ? arg[0][3] : 0;
  /* #578: @2 = kapparef_s(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w2);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #579: @0 = input[0][4] */
  w0 = arg[0] ? arg[0][4] : 0;
  /* #580: @2 = (@2*@0) */
  w2 *= w0;
  /* #581: output[0][14] = @2 */
  if (res[0]) res[0][14] = w2;
  return 0;
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_lifted_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_lifted_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_lifted_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_lifted_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_lifted_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_lifted_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_lifted_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_lifted_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tricycle_frenet_lifted_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tricycle_frenet_lifted_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tricycle_frenet_lifted_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tricycle_frenet_lifted_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tricycle_frenet_lifted_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tricycle_frenet_lifted_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tricycle_frenet_lifted_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_lifted_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 80;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
