/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tricycle_frenet_constr_h_0_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_c4 CASADI_PREFIX(c4)
#define casadi_c5 CASADI_PREFIX(c5)
#define casadi_c6 CASADI_PREFIX(c6)
#define casadi_c7 CASADI_PREFIX(c7)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[2] = {0, 78};
static const casadi_int casadi_s1[1] = {3};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[2] = {0, 76};
static const casadi_int casadi_s5[1] = {2};
static const casadi_int casadi_s6[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s7[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s8[3] = {0, 0, 0};
static const casadi_int casadi_s9[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s10[15] = {10, 3, 0, 3, 6, 9, 2, 5, 6, 3, 5, 6, 4, 5, 7};
static const casadi_int casadi_s11[3] = {3, 0, 0};

static const casadi_real casadi_c0[78] = {0., 0., 0., 0., 1.2500000000000000e+00, 1.8750000000000000e+00, 2.5000000000000000e+00, 3.1250000000000000e+00, 3.7500000000000000e+00, 4.3750000000000000e+00, 5., 5.2453380000000003e+00, 5.4906769999999998e+00, 5.7360150000000001e+00, 5.9813530000000004e+00, 6.2266919999999999e+00, 6.4720300000000002e+00, 6.7173689999999997e+00, 6.9627070000000000e+00, 7.2080450000000003e+00, 7.4533839999999998e+00, 7.6987220000000001e+00, 7.9440600000000003e+00, 8.1893989999999999e+00, 8.4347370000000002e+00, 8.6800759999999997e+00, 8.9254140000000000e+00, 9.5504140000000000e+00, 1.0175414000000000e+01, 1.0800414000000000e+01, 1.1425414000000000e+01, 1.2050414000000000e+01, 1.2675414000000000e+01, 1.3300414000000000e+01, 1.3925414000000000e+01, 1.4550414000000000e+01, 1.5175414000000000e+01, 1.5800414000000000e+01, 1.6425414000000000e+01, 1.7050414000000000e+01, 1.7675414000000000e+01, 1.8300414000000000e+01, 1.8925414000000000e+01, 1.9550414000000000e+01, 2.0175414000000000e+01, 2.0800414000000000e+01, 2.1425414000000000e+01, 2.2050414000000000e+01, 2.2675414000000000e+01, 2.3300414000000000e+01, 2.3925414000000000e+01, 2.4550414000000000e+01, 2.5175414000000000e+01, 2.5800414000000000e+01, 2.6425414000000000e+01, 2.6670414000000001e+01, 2.6915413999999998e+01, 2.7160413999999999e+01, 2.7405414000000000e+01, 2.7650414000000001e+01, 2.7895413999999999e+01, 2.8140414000000000e+01, 2.8385414000000001e+01, 2.8630413999999998e+01, 2.8875413999999999e+01, 2.9120414000000000e+01, 2.9365414000000001e+01, 2.9610413999999999e+01, 2.9855414000000000e+01, 3.0100414000000001e+01, 3.0345414000000002e+01, 3.0970414000000002e+01, 3.1595414000000002e+01, 3.2220413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01};
static const casadi_real casadi_c1[74] = {-3.4056776739063562e-15, 4.1666671497176233e-01, 1.0416665700566359e+00, 1.8750001449149409e+00, 2.4999994565689345e+00, 3.1250020288096985e+00, 3.7499924281918044e+00, 4.3750282584234936e+00, 4.8733676146580969e+00, 5.2454425379801499e+00, 5.4885060913662631e+00, 5.7268871373656607e+00, 5.9582173495914983e+00, 6.1804993193399467e+00, 6.3907359039273652e+00, 6.5901144562766820e+00, 6.7647027635167589e+00, 6.9576765146359927e+00, 7.0761080978676141e+00, 7.2099340552335009e+00, 7.3129736393691864e+00, 7.3963661605354574e+00, 7.4556672338058076e+00, 7.4927432316025175e+00, 7.5054587227317624e+00, 7.4980320948213137e+00, 7.5005272986032923e+00, 7.4998587107651700e+00, 7.5000378583363458e+00, 7.4999898558893232e+00, 7.5000027181063347e+00, 7.4999992716855477e+00, 7.5000001951512800e+00, 7.4999999477094841e+00, 7.5000000140107961e+00, 7.4999999962472028e+00, 7.5000000010006369e+00, 7.4999999997499742e+00, 7.4999999999997318e+00, 7.5000000002509761e+00, 7.4999999989963744e+00, 7.5000000037637102e+00, 7.4999999859485227e+00, 7.5000000524425756e+00, 7.4999998042808880e+00, 7.5000007304340830e+00, 7.4999972739827570e+00, 7.5000101736348688e+00, 7.4999620314778443e+00, 7.5001417004537991e+00, 7.4994711667068694e+00, 7.5019736327189150e+00, 7.4945270733584834e+00, 7.5072647279856781e+00, 7.5443021306107223e+00, 7.6037475495713407e+00, 7.6866028711041308e+00, 7.7916481660119459e+00, 7.9179852648481566e+00, 8.0643667745955110e+00, 8.2293910367695275e+00, 8.4114670783267513e+00, 8.6088414499231742e+00, 8.8196135219805250e+00, 9.0417536621550187e+00, 9.2731202293987529e+00, 9.5114952202504650e+00, 9.7545440895989408e+00, 1.0127010115321639e+01, 1.0624876310844066e+01, 1.1250032570598592e+01, 2.1874366785366853e+01, 3.2306863817874849e+01, 4.2500000000000057e+01};
static const casadi_real casadi_c2[74] = {-3.7660662463840044e-15, -1.3191389938505396e-05, 2.6382779891976146e-05, -3.9574169848335128e-05, 1.4840313690690150e-04, -5.5403837775622417e-04, 2.0677503740998741e-03, -7.7169631186545804e-03, 2.1405893025731388e-02, -1.5047824834658627e-01, -2.4457498934327093e-01, -3.4384258261379097e-01, -4.4172487831940577e-01, -5.3997752330378890e-01, -6.3813180133638558e-01, -7.3631199823364324e-01, -8.3448408540185159e-01, -9.3266496017090883e-01, -1.0308187941938989e+00, -1.1290696624412668e+00, -1.2269619555538092e+00, -1.3261909179024838e+00, -1.4204301156892047e+00, -1.5332945228027581e+00, -1.5990060749931916e+00, -1.5606264919642361e+00, -1.5735212918503823e+00, -1.5700661406342993e+00, -1.5709919456123731e+00, -1.5707438769161921e+00, -1.5708103467229448e+00, -1.5707925361919193e+00, -1.5707973085094353e+00, -1.5707960297703571e+00, -1.5707963724090681e+00, -1.5707962805934232e+00, -1.5707963052172358e+00, -1.5707962985375887e+00, -1.5707963006324408e+00, -1.5707962989326596e+00, -1.5707963036368719e+00, -1.5707962865198908e+00, -1.5707963502835767e+00, -1.5707961123457364e+00, -1.5707970003335447e+00, -1.5707936863200629e+00, -1.5708060543861566e+00, -1.5707598961354008e+00, -1.5709321610721556e+00, -1.5702892595760123e+00, -1.5726886006238190e+00, -1.5637341379286600e+00, -1.5903798296890472e+00, -1.4206348473511390e+00, -1.3261362887883423e+00, -1.2269763974955259e+00, -1.1290657212295343e+00, -1.0308201175862981e+00, -9.3266440842534237e-01, -8.3448416871225828e-01, -7.3631221672566427e-01, -6.3813164438506886e-01, -5.3997726573407245e-01, -4.4172673267861384e-01, -3.4383462355148825e-01, -2.4460497311545196e-01, -1.5036706398665492e-01, -3.7499730937968163e-02, 2.8249480863787979e-02, -1.0173731624572675e-02, 2.6790103531635257e-03, -5.2083432048135703e-02, 1.2500023691556477e+00, -3.6361385053160398e-20};
static const casadi_real casadi_c3[74] = {3.0645386858229446e-16, -1.3089801081462558e-05, 2.6179602168171847e-05, -3.9269403255937282e-05, 1.4726026220898269e-04, -5.4977164556842143e-04, 2.0518263200456910e-03, -7.6575336345958006e-03, 2.1241043050551717e-02, -2.8237618609103877e-02, -3.8682396610175022e-02, -1.0525323690568815e-01, -1.8619963529865763e-01, -2.9175598536716757e-01, -4.1795667603097730e-01, -5.6437405650187411e-01, -7.2938903592795667e-01, -9.1146812297075475e-01, -1.1088407484462068e+00, -1.3196136105385237e+00, -1.5417540248444319e+00, -1.7731205323120875e+00, -2.0114920503632709e+00, -2.2545581015182257e+00, -2.6266319042955568e+00, -3.1249719149929049e+00, -3.7500075253549610e+00, -4.3749979835872210e+00, -5.0000005402961722e+00, -5.6249998552280802e+00, -6.2500000387915300e+00, -6.8749999896058291e+00, -7.5000000027851303e+00, -8.1249999992537170e+00, -8.7500000001999663e+00, -9.3749999999464801e+00, -1.0000000000014053e+01, -1.0624999999997355e+01, -1.1249999999996493e+01, -1.1875000000016668e+01, -1.2499999999936897e+01, -1.3125000000235708e+01, -1.3749999999120327e+01, -1.4375000003282915e+01, -1.4999999987748060e+01, -1.5625000045724844e+01, -1.6249999829352603e+01, -1.6875000636864765e+01, -1.7499997623188381e+01, -1.8125008870381762e+01, -1.8749966895284555e+01, -1.9375123548480055e+01, -1.9872990730699367e+01, -2.0245454768555447e+01, -2.0488503778589820e+01, -2.0726880117085305e+01, -2.0958241753068851e+01, -2.1180400870639410e+01, -2.1391100764373505e+01, -2.1588548071866708e+01, -2.1770604948159676e+01, -2.1935634135494670e+01, -2.2082014509861679e+01, -2.2208351825058564e+01, -2.2313396189904086e+01, -2.2396251415325054e+01, -2.2455698148795783e+01, -2.2492733989491846e+01, -2.2505473666601691e+01, -2.2498028720765653e+01, -2.2500519089521198e+01, -2.2489908227203195e+01, -2.2742202547123352e+01, -2.2499999999999986e+01};
static const casadi_real casadi_c4[76] = {0., 0., 0., 1.2500000000000000e+00, 1.8750000000000000e+00, 2.5000000000000000e+00, 3.1250000000000000e+00, 3.7500000000000000e+00, 4.3750000000000000e+00, 5., 5.2453380000000003e+00, 5.4906769999999998e+00, 5.7360150000000001e+00, 5.9813530000000004e+00, 6.2266919999999999e+00, 6.4720300000000002e+00, 6.7173689999999997e+00, 6.9627070000000000e+00, 7.2080450000000003e+00, 7.4533839999999998e+00, 7.6987220000000001e+00, 7.9440600000000003e+00, 8.1893989999999999e+00, 8.4347370000000002e+00, 8.6800759999999997e+00, 8.9254140000000000e+00, 9.5504140000000000e+00, 1.0175414000000000e+01, 1.0800414000000000e+01, 1.1425414000000000e+01, 1.2050414000000000e+01, 1.2675414000000000e+01, 1.3300414000000000e+01, 1.3925414000000000e+01, 1.4550414000000000e+01, 1.5175414000000000e+01, 1.5800414000000000e+01, 1.6425414000000000e+01, 1.7050414000000000e+01, 1.7675414000000000e+01, 1.8300414000000000e+01, 1.8925414000000000e+01, 1.9550414000000000e+01, 2.0175414000000000e+01, 2.0800414000000000e+01, 2.1425414000000000e+01, 2.2050414000000000e+01, 2.2675414000000000e+01, 2.3300414000000000e+01, 2.3925414000000000e+01, 2.4550414000000000e+01, 2.5175414000000000e+01, 2.5800414000000000e+01, 2.6425414000000000e+01, 2.6670414000000001e+01, 2.6915413999999998e+01, 2.7160413999999999e+01, 2.7405414000000000e+01, 2.7650414000000001e+01, 2.7895413999999999e+01, 2.8140414000000000e+01, 2.8385414000000001e+01, 2.8630413999999998e+01, 2.8875413999999999e+01, 2.9120414000000000e+01, 2.9365414000000001e+01, 2.9610413999999999e+01, 2.9855414000000000e+01, 3.0100414000000001e+01, 3.0345414000000002e+01, 3.0970414000000002e+01, 3.1595414000000002e+01, 3.2220413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01};
static const casadi_real casadi_c5[73] = {1.0000001159322378e+00, 9.9999976813579772e-01, 1.0000002898299662e+00, 9.9999889864638958e-01, 1.0000041155852224e+00, 9.9998463901136969e-01, 1.0000573283707028e+00, 9.9978604750485123e-01, 1.0004909754043139e+00, 9.9072798809581331e-01, 9.7164206979231804e-01, 9.4290284393322643e-01, 9.0602217243581407e-01, 8.5692397143846832e-01, 8.1266775411907388e-01, 7.1162261872411814e-01, 7.8656175941754147e-01, 4.8272759345239485e-01, 5.4547512224297090e-01, 4.1998974532727951e-01, 3.3990824031957734e-01, 2.4171107667639061e-01, 1.5112191108894352e-01, 3.4191323642714898e-02, -1.4899563664766568e-02, 3.9923260511656178e-03, -1.0697405409950012e-03, 2.8663611388135557e-04, -7.6803915235545977e-05, 2.0579547217591811e-05, -5.5142732599211538e-06, 1.4775451720350218e-06, -3.9590687390678169e-07, 1.0608209879414688e-07, -2.8421749975748869e-08, 7.6054948561221629e-09, -2.0010603396514170e-09, 3.9961238762487027e-10, 4.0199057416145936e-10, -2.0073635642603451e-09, 7.6277369753796617e-09, -2.8504299764975374e-08, 1.0639048428906506e-07, -3.9705869991912834e-07, 1.4818451127052158e-06, -5.5303221213609532e-06, 2.0639443379577573e-05, -7.7027451238764757e-05, 2.8747036152760864e-04, -1.0728539950875860e-03, 4.0039456192722421e-03, -1.4942928482471900e-02, 3.4271716485726092e-02, 1.5117307193895529e-01, 2.4263436310456421e-01, 3.3818498584812218e-01, 4.2875630574618445e-01, 5.1566162790290171e-01, 5.9747554998920294e-01, 6.7356841703680015e-01, 7.4316751656010027e-01, 8.0560967998540112e-01, 8.6029417166265409e-01, 9.0669444969180901e-01, 9.4435333568870805e-01, 9.7295914633351732e-01, 9.9203620142234683e-01, 1.0021507418547926e+00, 9.9906259971055533e-01, 1.0002500156072445e+00, 9.9993733786054262e-01, 1.0015197151207678e+00, 9.9851129947348971e-01};
static const casadi_real casadi_c6[73] = {-3.1659335843374394e-05, 6.3318671728770473e-05, -7.9148339688373548e-05, 3.0076369080837861e-04, -1.1239064234610011e-03, 4.1948620029697570e-03, -1.5655541588407127e-02, 5.8427304350693883e-02, -4.6218791291471728e-01, -3.8353868194269675e-01, -4.0461509590369771e-01, -3.9896861764616792e-01, -4.0047816274552739e-01, -4.0007667509645217e-01, -4.0018286406088571e-01, -4.0014980877376843e-01, -4.0018562706897520e-01, -4.0007540888293036e-01, -4.0047092075854995e-01, -3.9900936711565271e-01, -4.0445763611614394e-01, -3.8411881448251517e-01, -4.6003576196227031e-01, -1.7669509774899012e-01, 7.6998477325438339e-02, -2.0631679817833742e-02, 5.5282419457328858e-03, -1.4812879649179829e-03, 3.9690991388980284e-04, -1.0635169080442449e-04, 2.8496849641117912e-05, -7.6357080254726022e-06, 2.0459825250388877e-06, -5.4822193767474629e-07, 1.4690503173302039e-07, -3.9398100033131937e-08, 1.0687435152796683e-08, -3.3517630955867174e-09, 2.7196501432417097e-09, -7.5267399042996451e-09, 2.7387170081034971e-08, -1.0202189720327904e-07, 3.8070054446041760e-07, -1.4207804933948506e-06, 5.3024215708345328e-06, -1.9788905749835344e-05, 7.3853201209533138e-05, -2.7562389880784820e-04, 1.0286423938294423e-03, -3.8389456764907747e-03, 1.4327140312254499e-02, -5.3469615572683302e-02, 4.5671295696298264e-01, 3.8570840229712955e-01, 4.0473425017476167e-01, 3.9963541333057667e-01, 4.0100246384994392e-01, 4.0063554759573755e-01, 4.0073567229830276e-01, 4.0070184484324101e-01, 4.0073702996161431e-01, 4.0063011694284262e-01, 4.0102258389982937e-01, 3.9955962909030884e-01, 4.0501898137157688e-01, 3.8464452705631469e-01, 4.6068299203545421e-01, 1.7690370888364851e-01, -7.7103436431492894e-02, 2.0564387164377959e-02, -5.1541122260046349e-03, 1.2500023691556320e-01, -1.2244921167238999e-01};
static const casadi_real casadi_c7[73] = {-3.1415522596245632e-05, 6.2831045199415047e-05, -7.8538806508930968e-05, 2.9844746474387199e-04, -1.1152510524438466e-03, 4.1625567449825804e-03, -1.5534975927426387e-02, 5.7977346964661190e-02, -1.3304566194245002e-01, -4.2572955718583771e-02, -2.7134300372484171e-01, -3.2993783439047902e-01, -4.3024809304909523e-01, -5.1439380664473278e-01, -5.9679781174662239e-01, -6.7260169735433073e-01, -7.4215506630760830e-01, -8.0449158838659041e-01, -8.5911100490744108e-01, -9.0544519190196493e-01, -9.4305078347991134e-01, -9.7160191375398197e-01, -9.9073816901131673e-01, -1.0004879623152521e+00, -9.9978736051116435e-01, -1.0000569765792897e+00, -9.9998473317161574e-01, -1.0000040907343224e+00, -9.9999890389105328e-01, -1.0000002937015207e+00, -9.9999992130287929e-01, -1.0000000210868811e+00, -9.9999999434973819e-01, -1.0000000015139996e+00, -9.9999999959442232e-01, -1.0000000001081164e+00, -9.9999999997328382e-01, -9.9999999999862188e-01, -1.0000000000322788e+00, -9.9999999987236565e-01, -1.0000000004780991e+00, -9.9999999821538932e-01, -1.0000000066601407e+00, -9.9999997514423167e-01, -1.0000000927628554e+00, -9.9999965380441302e-01, -1.0000012920194601e+00, -9.9999517811778715e-01, -1.0000179955094113e+00, -9.9993283984446912e-01, -1.0002506451128002e+00, -9.9906457970430906e-01, -1.0021453933347488e+00, -9.9203677565050774e-01, -9.7296464692034967e-01, -9.4433320809610055e-01, -9.0677190845126299e-01, -8.5999956626161278e-01, -8.0590737752328356e-01, -7.4308929099170773e-01, -6.7358851973467382e-01, -5.9747091578370604e-01, -5.1566251100768989e-01, -4.2875250957355315e-01, -3.3818459355496699e-01, -2.4263972845195142e-01, -1.5116669671863037e-01, -3.4277158143080411e-02, 1.4939690640880191e-02, -3.9845900088723036e-03, 9.9866939463572990e-04, -2.4220254712335156e-02, 2.3725963799839798e-02};

/* x_ref:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* phi_ref:(x)->(f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c2,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* y_ref:(x)->(f) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c3,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_x_ref:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c5,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_phi_ref:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c6,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* fwd1_y_ref:(x,out_f[1x1,0nz],fwd_x)->(fwd_f) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c4,casadi_s4,casadi_s5,casadi_s2,casadi_c7,1,(&w0),casadi_s3, iw, w);
  /* #2: @0 = input[2][0] */
  w0 = arg[2] ? arg[2][0] : 0;
  /* #3: @1 = (@1*@0) */
  w1 *= w0;
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* tricycle_frenet_constr_h_0_fun_jac_uxt_zt:(i0[8],i1[2],i2[],i3[])->(o0[3],o1[10x3,9nz],o2[3x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+3, *rr, *ss;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, w11, *w12=w+24, *w13=w+33, *w14=w+40, w16, *w17=w+44;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = x_ref(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w2);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #3: @3 = input[0][4] */
  w3 = arg[0] ? arg[0][4] : 0;
  /* #4: @4 = phi_ref(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #5: @5 = sin(@4) */
  w5 = sin( w4 );
  /* #6: @6 = (@3*@5) */
  w6  = (w3*w5);
  /* #7: @2 = (@2-@6) */
  w2 -= w6;
  /* #8: @0 = (@0-@2) */
  w0 -= w2;
  /* #9: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #10: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #11: @2 = y_ref(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w2);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #12: @6 = cos(@4) */
  w6 = cos( w4 );
  /* #13: @7 = (@3*@6) */
  w7  = (w3*w6);
  /* #14: @2 = (@2+@7) */
  w2 += w7;
  /* #15: @0 = (@0-@2) */
  w0 -= w2;
  /* #16: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #17: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #18: @2 = 3.14159 */
  w2 = 3.1415926535897900e+00;
  /* #19: @7 = input[0][5] */
  w7 = arg[0] ? arg[0][5] : 0;
  /* #20: @7 = (@4+@7) */
  w7  = (w4+w7);
  /* #21: @8 = -3.14159 */
  w8 = -3.1415926535897900e+00;
  /* #22: @8 = (@7<=@8) */
  w8  = (w7<=w8);
  /* #23: @9 = 6.28319 */
  w9 = 6.2831853071795800e+00;
  /* #24: @9 = (@9+@7) */
  w9 += w7;
  /* #25: @9 = (@8?@9:0) */
  w9  = (w8?w9:0);
  /* #26: @10 = (!@8) */
  w10 = (! w8 );
  /* #27: @7 = (@10?@7:0) */
  w7  = (w10?w7:0);
  /* #28: @9 = (@9+@7) */
  w9 += w7;
  /* #29: @2 = (@2<=@9) */
  w2  = (w2<=w9);
  /* #30: @7 = 6.28319 */
  w7 = 6.2831853071795800e+00;
  /* #31: @7 = (@9-@7) */
  w7  = (w9-w7);
  /* #32: @7 = (@2?@7:0) */
  w7  = (w2?w7:0);
  /* #33: @11 = (!@2) */
  w11 = (! w2 );
  /* #34: @9 = (@11?@9:0) */
  w9  = (w11?w9:0);
  /* #35: @7 = (@7+@9) */
  w7 += w9;
  /* #36: @0 = (@0-@7) */
  w0 -= w7;
  /* #37: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #38: @12 = zeros(10x3,9nz) */
  casadi_clear(w12, 9);
  /* #39: @13 = ones(10x1,7nz) */
  casadi_fill(w13, 7, 1.);
  /* #40: {NULL, NULL, @0, @7, @9, NULL, NULL, NULL, NULL, NULL} = vertsplit(@13) */
  w0 = w13[2];
  w7 = w13[3];
  w9 = w13[4];
  /* #41: @14 = vertcat(@0, @7, @9) */
  rr=w14;
  *rr++ = w0;
  *rr++ = w7;
  *rr++ = w9;
  /* #42: (@12[:9:3] = @14) */
  for (rr=w12+0, ss=w14; rr!=w12+9; rr+=3) *rr = *ss++;
  /* #43: @15 = 00 */
  /* #44: @0 = ones(10x1,1nz) */
  w0 = 1.;
  /* #45: {NULL, NULL, NULL, NULL, NULL, @7, NULL, NULL, NULL, NULL} = vertsplit(@0) */
  w7 = w0;
  /* #46: @0 = fwd1_x_ref(@1, @15, @7) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=(&w7);
  res1[0]=(&w0);
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #47: @9 = cos(@4) */
  w9 = cos( w4 );
  /* #48: @15 = 00 */
  /* #49: @16 = fwd1_phi_ref(@1, @15, @7) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=(&w7);
  res1[0]=(&w16);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #50: @9 = (@9*@16) */
  w9 *= w16;
  /* #51: @9 = (@3*@9) */
  w9  = (w3*w9);
  /* #52: @0 = (@0-@9) */
  w0 -= w9;
  /* #53: @0 = (-@0) */
  w0 = (- w0 );
  /* #54: @15 = 00 */
  /* #55: @9 = fwd1_y_ref(@1, @15, @7) */
  arg1[0]=(&w1);
  arg1[1]=0;
  arg1[2]=(&w7);
  res1[0]=(&w9);
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #56: @4 = sin(@4) */
  w4 = sin( w4 );
  /* #57: @4 = (@4*@16) */
  w4 *= w16;
  /* #58: @3 = (@3*@4) */
  w3 *= w4;
  /* #59: @9 = (@9-@3) */
  w9 -= w3;
  /* #60: @9 = (-@9) */
  w9 = (- w9 );
  /* #61: @3 = (@8?@16:0) */
  w3  = (w8?w16:0);
  /* #62: @16 = (@10?@16:0) */
  w16  = (w10?w16:0);
  /* #63: @3 = (@3+@16) */
  w3 += w16;
  /* #64: @16 = (@2?@3:0) */
  w16  = (w2?w3:0);
  /* #65: @3 = (@11?@3:0) */
  w3  = (w11?w3:0);
  /* #66: @16 = (@16+@3) */
  w16 += w3;
  /* #67: @16 = (-@16) */
  w16 = (- w16 );
  /* #68: @14 = vertcat(@0, @9, @16) */
  rr=w14;
  *rr++ = w0;
  *rr++ = w9;
  *rr++ = w16;
  /* #69: (@12[1:10:3] = @14) */
  for (rr=w12+1, ss=w14; rr!=w12+10; rr+=3) *rr = *ss++;
  /* #70: @17 = ones(10x1,2nz) */
  casadi_fill(w17, 2, 1.);
  /* #71: {NULL, NULL, NULL, NULL, NULL, NULL, @0, @9, NULL, NULL} = vertsplit(@17) */
  w0 = w17[0];
  w9 = w17[1];
  /* #72: @5 = (@5*@0) */
  w5 *= w0;
  /* #73: @6 = (@6*@0) */
  w6 *= w0;
  /* #74: @6 = (-@6) */
  w6 = (- w6 );
  /* #75: @8 = (@8?@9:0) */
  w8  = (w8?w9:0);
  /* #76: @10 = (@10?@9:0) */
  w10  = (w10?w9:0);
  /* #77: @8 = (@8+@10) */
  w8 += w10;
  /* #78: @2 = (@2?@8:0) */
  w2  = (w2?w8:0);
  /* #79: @11 = (@11?@8:0) */
  w11  = (w11?w8:0);
  /* #80: @2 = (@2+@11) */
  w2 += w11;
  /* #81: @2 = (-@2) */
  w2 = (- w2 );
  /* #82: @14 = vertcat(@5, @6, @2) */
  rr=w14;
  *rr++ = w5;
  *rr++ = w6;
  *rr++ = w2;
  /* #83: (@12[2:11:3] = @14) */
  for (rr=w12+2, ss=w14; rr!=w12+11; rr+=3) *rr = *ss++;
  /* #84: output[1][0] = @12 */
  casadi_copy(w12, 9, res[1]);
  return 0;
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_constr_h_0_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_constr_h_0_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_constr_h_0_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_constr_h_0_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_constr_h_0_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_constr_h_0_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_constr_h_0_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_constr_h_0_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tricycle_frenet_constr_h_0_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tricycle_frenet_constr_h_0_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real tricycle_frenet_constr_h_0_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tricycle_frenet_constr_h_0_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tricycle_frenet_constr_h_0_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tricycle_frenet_constr_h_0_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tricycle_frenet_constr_h_0_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s9;
    case 1: return casadi_s10;
    case 2: return casadi_s11;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_constr_h_0_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 13;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 46;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
