/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) tricycle_frenet_constr_h_0_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_clear_casadi_int CASADI_PREFIX(clear_casadi_int)
#define casadi_de_boor CASADI_PREFIX(de_boor)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_fill_casadi_int CASADI_PREFIX(fill_casadi_int)
#define casadi_low CASADI_PREFIX(low)
#define casadi_nd_boor_eval CASADI_PREFIX(nd_boor_eval)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_de_boor(casadi_real x, const casadi_real* knots, casadi_int n_knots, casadi_int degree, casadi_real* boor) {
  casadi_int d, i;
  for (d=1;d<degree+1;++d) {
    for (i=0;i<n_knots-d-1;++i) {
      casadi_real b, bottom;
      b = 0;
      bottom = knots[i + d] - knots[i];
      if (bottom) b = (x - knots[i]) * boor[i] / bottom;
      bottom = knots[i + d + 1] - knots[i + 1];
      if (bottom) b += (knots[i + d + 1] - x) * boor[i + 1] / bottom;
      boor[i] = b;
    }
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_fill_casadi_int(casadi_int* x, casadi_int n, casadi_int alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_clear_casadi_int(casadi_int* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_int casadi_low(casadi_real x, const casadi_real* grid, casadi_int ng, casadi_int lookup_mode) {
  switch (lookup_mode) {
    case 1:
      {
        casadi_real g0, dg;
        casadi_int ret;
        g0 = grid[0];
        dg = grid[ng-1]-g0;
        ret = (casadi_int) ((x-g0)*(ng-1)/dg);
        if (ret<0) ret=0;
        if (ret>ng-2) ret=ng-2;
        return ret;
      }
    case 2:
      {
        casadi_int start, stop, pivot;
        if (ng<2 || x<grid[1]) return 0;
        if (x>grid[ng-1]) return ng-2;
        start = 0;
        stop  = ng-1;
        while (1) {
          pivot = (stop+start)/2;
          if (x < grid[pivot]) {
            if (pivot==stop) return pivot;
            stop = pivot;
          } else {
            if (pivot==start) return pivot;
            start = pivot;
          }
        }
      }
    default:
      {
        casadi_int i;
        for (i=0; i<ng-2; ++i) {
          if (x < grid[i+1]) break;
        }
        return i;
      }
  }
}

void casadi_nd_boor_eval(casadi_real* ret, casadi_int n_dims, const casadi_real* all_knots, const casadi_int* offset, const casadi_int* all_degree, const casadi_int* strides, const casadi_real* c, casadi_int m, const casadi_real* all_x, const casadi_int* lookup_mode, casadi_int* iw, casadi_real* w) {
  casadi_int n_iter, k, i, pivot;
  casadi_int *boor_offset, *starts, *index, *coeff_offset;
  casadi_real *cumprod, *all_boor;
  boor_offset = iw; iw+=n_dims+1;
  starts = iw; iw+=n_dims;
  index = iw; iw+=n_dims;
  coeff_offset = iw;
  cumprod = w; w+= n_dims+1;
  all_boor = w;
  boor_offset[0] = 0;
  cumprod[n_dims] = 1;
  coeff_offset[n_dims] = 0;
  n_iter = 1;
  for (k=0;k<n_dims;++k) {
    casadi_real *boor;
    const casadi_real* knots;
    casadi_real x;
    casadi_int degree, n_knots, n_b, L, start;
    boor = all_boor+boor_offset[k];
    degree = all_degree[k];
    knots = all_knots + offset[k];
    n_knots = offset[k+1]-offset[k];
    n_b = n_knots-degree-1;
    x = all_x[k];
    L = casadi_low(x, knots+degree, n_knots-2*degree, lookup_mode[k]);
    start = L;
    if (start>n_b-degree-1) start = n_b-degree-1;
    starts[k] = start;
    casadi_clear(boor, 2*degree+1);
    if (x>=knots[0] && x<=knots[n_knots-1]) {
      if (x==knots[1]) {
        casadi_fill(boor, degree+1, 1.0);
      } else if (x==knots[n_knots-1]) {
        boor[degree] = 1;
      } else if (knots[L+degree]==x) {
        boor[degree-1] = 1;
      } else {
        boor[degree] = 1;
      }
    }
    casadi_de_boor(x, knots+start, 2*degree+2, degree, boor);
    boor+= degree+1;
    n_iter*= degree+1;
    boor_offset[k+1] = boor_offset[k] + degree+1;
  }
  casadi_clear_casadi_int(index, n_dims);
  for (pivot=n_dims-1;pivot>=0;--pivot) {
    cumprod[pivot] = (*(all_boor+boor_offset[pivot]))*cumprod[pivot+1];
    coeff_offset[pivot] = starts[pivot]*strides[pivot]+coeff_offset[pivot+1];
  }
  for (k=0;k<n_iter;++k) {
    casadi_int pivot = 0;
    for (i=0;i<m;++i) ret[i] += c[coeff_offset[0]+i]*cumprod[0];
    index[0]++;
    {
      while (index[pivot]==boor_offset[pivot+1]-boor_offset[pivot]) {
        index[pivot] = 0;
        if (pivot==n_dims-1) break;
        index[++pivot]++;
      }
      while (pivot>0) {
        cumprod[pivot] = (*(all_boor+boor_offset[pivot]+index[pivot]))*cumprod[pivot+1];
        coeff_offset[pivot] = (starts[pivot]+index[pivot])*strides[pivot]+coeff_offset[pivot+1];
        pivot--;
      }
    }
    cumprod[0] = (*(all_boor+index[0]))*cumprod[1];
    coeff_offset[0] = (starts[0]+index[0])*m+coeff_offset[1];
  }
}

static const casadi_int casadi_s0[2] = {0, 78};
static const casadi_int casadi_s1[1] = {3};
static const casadi_int casadi_s2[1] = {1};
static const casadi_int casadi_s3[1] = {0};
static const casadi_int casadi_s4[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s5[6] = {2, 1, 0, 2, 0, 1};
static const casadi_int casadi_s6[3] = {0, 0, 0};
static const casadi_int casadi_s7[7] = {3, 1, 0, 3, 0, 1, 2};

static const casadi_real casadi_c0[78] = {0., 0., 0., 0., 1.2500000000000000e+00, 1.8750000000000000e+00, 2.5000000000000000e+00, 3.1250000000000000e+00, 3.7500000000000000e+00, 4.3750000000000000e+00, 5., 5.2453380000000003e+00, 5.4906769999999998e+00, 5.7360150000000001e+00, 5.9813530000000004e+00, 6.2266919999999999e+00, 6.4720300000000002e+00, 6.7173689999999997e+00, 6.9627070000000000e+00, 7.2080450000000003e+00, 7.4533839999999998e+00, 7.6987220000000001e+00, 7.9440600000000003e+00, 8.1893989999999999e+00, 8.4347370000000002e+00, 8.6800759999999997e+00, 8.9254140000000000e+00, 9.5504140000000000e+00, 1.0175414000000000e+01, 1.0800414000000000e+01, 1.1425414000000000e+01, 1.2050414000000000e+01, 1.2675414000000000e+01, 1.3300414000000000e+01, 1.3925414000000000e+01, 1.4550414000000000e+01, 1.5175414000000000e+01, 1.5800414000000000e+01, 1.6425414000000000e+01, 1.7050414000000000e+01, 1.7675414000000000e+01, 1.8300414000000000e+01, 1.8925414000000000e+01, 1.9550414000000000e+01, 2.0175414000000000e+01, 2.0800414000000000e+01, 2.1425414000000000e+01, 2.2050414000000000e+01, 2.2675414000000000e+01, 2.3300414000000000e+01, 2.3925414000000000e+01, 2.4550414000000000e+01, 2.5175414000000000e+01, 2.5800414000000000e+01, 2.6425414000000000e+01, 2.6670414000000001e+01, 2.6915413999999998e+01, 2.7160413999999999e+01, 2.7405414000000000e+01, 2.7650414000000001e+01, 2.7895413999999999e+01, 2.8140414000000000e+01, 2.8385414000000001e+01, 2.8630413999999998e+01, 2.8875413999999999e+01, 2.9120414000000000e+01, 2.9365414000000001e+01, 2.9610413999999999e+01, 2.9855414000000000e+01, 3.0100414000000001e+01, 3.0345414000000002e+01, 3.0970414000000002e+01, 3.1595414000000002e+01, 3.2220413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01, 6.2845413999999998e+01};
static const casadi_real casadi_c1[74] = {-3.4056776739063562e-15, 4.1666671497176233e-01, 1.0416665700566359e+00, 1.8750001449149409e+00, 2.4999994565689345e+00, 3.1250020288096985e+00, 3.7499924281918044e+00, 4.3750282584234936e+00, 4.8733676146580969e+00, 5.2454425379801499e+00, 5.4885060913662631e+00, 5.7268871373656607e+00, 5.9582173495914983e+00, 6.1804993193399467e+00, 6.3907359039273652e+00, 6.5901144562766820e+00, 6.7647027635167589e+00, 6.9576765146359927e+00, 7.0761080978676141e+00, 7.2099340552335009e+00, 7.3129736393691864e+00, 7.3963661605354574e+00, 7.4556672338058076e+00, 7.4927432316025175e+00, 7.5054587227317624e+00, 7.4980320948213137e+00, 7.5005272986032923e+00, 7.4998587107651700e+00, 7.5000378583363458e+00, 7.4999898558893232e+00, 7.5000027181063347e+00, 7.4999992716855477e+00, 7.5000001951512800e+00, 7.4999999477094841e+00, 7.5000000140107961e+00, 7.4999999962472028e+00, 7.5000000010006369e+00, 7.4999999997499742e+00, 7.4999999999997318e+00, 7.5000000002509761e+00, 7.4999999989963744e+00, 7.5000000037637102e+00, 7.4999999859485227e+00, 7.5000000524425756e+00, 7.4999998042808880e+00, 7.5000007304340830e+00, 7.4999972739827570e+00, 7.5000101736348688e+00, 7.4999620314778443e+00, 7.5001417004537991e+00, 7.4994711667068694e+00, 7.5019736327189150e+00, 7.4945270733584834e+00, 7.5072647279856781e+00, 7.5443021306107223e+00, 7.6037475495713407e+00, 7.6866028711041308e+00, 7.7916481660119459e+00, 7.9179852648481566e+00, 8.0643667745955110e+00, 8.2293910367695275e+00, 8.4114670783267513e+00, 8.6088414499231742e+00, 8.8196135219805250e+00, 9.0417536621550187e+00, 9.2731202293987529e+00, 9.5114952202504650e+00, 9.7545440895989408e+00, 1.0127010115321639e+01, 1.0624876310844066e+01, 1.1250032570598592e+01, 2.1874366785366853e+01, 3.2306863817874849e+01, 4.2500000000000057e+01};
static const casadi_real casadi_c2[74] = {-3.7660662463840044e-15, -1.3191389938505396e-05, 2.6382779891976146e-05, -3.9574169848335128e-05, 1.4840313690690150e-04, -5.5403837775622417e-04, 2.0677503740998741e-03, -7.7169631186545804e-03, 2.1405893025731388e-02, -1.5047824834658627e-01, -2.4457498934327093e-01, -3.4384258261379097e-01, -4.4172487831940577e-01, -5.3997752330378890e-01, -6.3813180133638558e-01, -7.3631199823364324e-01, -8.3448408540185159e-01, -9.3266496017090883e-01, -1.0308187941938989e+00, -1.1290696624412668e+00, -1.2269619555538092e+00, -1.3261909179024838e+00, -1.4204301156892047e+00, -1.5332945228027581e+00, -1.5990060749931916e+00, -1.5606264919642361e+00, -1.5735212918503823e+00, -1.5700661406342993e+00, -1.5709919456123731e+00, -1.5707438769161921e+00, -1.5708103467229448e+00, -1.5707925361919193e+00, -1.5707973085094353e+00, -1.5707960297703571e+00, -1.5707963724090681e+00, -1.5707962805934232e+00, -1.5707963052172358e+00, -1.5707962985375887e+00, -1.5707963006324408e+00, -1.5707962989326596e+00, -1.5707963036368719e+00, -1.5707962865198908e+00, -1.5707963502835767e+00, -1.5707961123457364e+00, -1.5707970003335447e+00, -1.5707936863200629e+00, -1.5708060543861566e+00, -1.5707598961354008e+00, -1.5709321610721556e+00, -1.5702892595760123e+00, -1.5726886006238190e+00, -1.5637341379286600e+00, -1.5903798296890472e+00, -1.4206348473511390e+00, -1.3261362887883423e+00, -1.2269763974955259e+00, -1.1290657212295343e+00, -1.0308201175862981e+00, -9.3266440842534237e-01, -8.3448416871225828e-01, -7.3631221672566427e-01, -6.3813164438506886e-01, -5.3997726573407245e-01, -4.4172673267861384e-01, -3.4383462355148825e-01, -2.4460497311545196e-01, -1.5036706398665492e-01, -3.7499730937968163e-02, 2.8249480863787979e-02, -1.0173731624572675e-02, 2.6790103531635257e-03, -5.2083432048135703e-02, 1.2500023691556477e+00, -3.6361385053160398e-20};
static const casadi_real casadi_c3[74] = {3.0645386858229446e-16, -1.3089801081462558e-05, 2.6179602168171847e-05, -3.9269403255937282e-05, 1.4726026220898269e-04, -5.4977164556842143e-04, 2.0518263200456910e-03, -7.6575336345958006e-03, 2.1241043050551717e-02, -2.8237618609103877e-02, -3.8682396610175022e-02, -1.0525323690568815e-01, -1.8619963529865763e-01, -2.9175598536716757e-01, -4.1795667603097730e-01, -5.6437405650187411e-01, -7.2938903592795667e-01, -9.1146812297075475e-01, -1.1088407484462068e+00, -1.3196136105385237e+00, -1.5417540248444319e+00, -1.7731205323120875e+00, -2.0114920503632709e+00, -2.2545581015182257e+00, -2.6266319042955568e+00, -3.1249719149929049e+00, -3.7500075253549610e+00, -4.3749979835872210e+00, -5.0000005402961722e+00, -5.6249998552280802e+00, -6.2500000387915300e+00, -6.8749999896058291e+00, -7.5000000027851303e+00, -8.1249999992537170e+00, -8.7500000001999663e+00, -9.3749999999464801e+00, -1.0000000000014053e+01, -1.0624999999997355e+01, -1.1249999999996493e+01, -1.1875000000016668e+01, -1.2499999999936897e+01, -1.3125000000235708e+01, -1.3749999999120327e+01, -1.4375000003282915e+01, -1.4999999987748060e+01, -1.5625000045724844e+01, -1.6249999829352603e+01, -1.6875000636864765e+01, -1.7499997623188381e+01, -1.8125008870381762e+01, -1.8749966895284555e+01, -1.9375123548480055e+01, -1.9872990730699367e+01, -2.0245454768555447e+01, -2.0488503778589820e+01, -2.0726880117085305e+01, -2.0958241753068851e+01, -2.1180400870639410e+01, -2.1391100764373505e+01, -2.1588548071866708e+01, -2.1770604948159676e+01, -2.1935634135494670e+01, -2.2082014509861679e+01, -2.2208351825058564e+01, -2.2313396189904086e+01, -2.2396251415325054e+01, -2.2455698148795783e+01, -2.2492733989491846e+01, -2.2505473666601691e+01, -2.2498028720765653e+01, -2.2500519089521198e+01, -2.2489908227203195e+01, -2.2742202547123352e+01, -2.2499999999999986e+01};

/* x_ref:(x)->(f) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c1,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* phi_ref:(x)->(f) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c2,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* y_ref:(x)->(f) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = BSpline(@0) */
  casadi_clear((&w1), 1);
  CASADI_PREFIX(nd_boor_eval)((&w1),1,casadi_c0,casadi_s0,casadi_s1,casadi_s2,casadi_c3,1,(&w0),casadi_s3, iw, w);
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* tricycle_frenet_constr_h_0_fun:(i0[8],i1[2],i2[],i3[])->(o0[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1;
  const casadi_real **arg1=arg+4;
  casadi_real w0, w1, w2, w3, w4, w5;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = input[0][3] */
  w1 = arg[0] ? arg[0][3] : 0;
  /* #2: @2 = x_ref(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w2);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #3: @3 = input[0][4] */
  w3 = arg[0] ? arg[0][4] : 0;
  /* #4: @4 = phi_ref(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w4);
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #5: @5 = sin(@4) */
  w5 = sin( w4 );
  /* #6: @5 = (@3*@5) */
  w5  = (w3*w5);
  /* #7: @2 = (@2-@5) */
  w2 -= w5;
  /* #8: @0 = (@0-@2) */
  w0 -= w2;
  /* #9: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #10: @0 = input[0][1] */
  w0 = arg[0] ? arg[0][1] : 0;
  /* #11: @2 = y_ref(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w2);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #12: @1 = cos(@4) */
  w1 = cos( w4 );
  /* #13: @3 = (@3*@1) */
  w3 *= w1;
  /* #14: @2 = (@2+@3) */
  w2 += w3;
  /* #15: @0 = (@0-@2) */
  w0 -= w2;
  /* #16: output[0][1] = @0 */
  if (res[0]) res[0][1] = w0;
  /* #17: @0 = input[0][2] */
  w0 = arg[0] ? arg[0][2] : 0;
  /* #18: @2 = 3.14159 */
  w2 = 3.1415926535897900e+00;
  /* #19: @3 = input[0][5] */
  w3 = arg[0] ? arg[0][5] : 0;
  /* #20: @4 = (@4+@3) */
  w4 += w3;
  /* #21: @3 = -3.14159 */
  w3 = -3.1415926535897900e+00;
  /* #22: @3 = (@4<=@3) */
  w3  = (w4<=w3);
  /* #23: @1 = 6.28319 */
  w1 = 6.2831853071795800e+00;
  /* #24: @1 = (@1+@4) */
  w1 += w4;
  /* #25: @1 = (@3?@1:0) */
  w1  = (w3?w1:0);
  /* #26: @3 = (!@3) */
  w3 = (! w3 );
  /* #27: @3 = (@3?@4:0) */
  w3  = (w3?w4:0);
  /* #28: @1 = (@1+@3) */
  w1 += w3;
  /* #29: @2 = (@2<=@1) */
  w2  = (w2<=w1);
  /* #30: @3 = 6.28319 */
  w3 = 6.2831853071795800e+00;
  /* #31: @3 = (@1-@3) */
  w3  = (w1-w3);
  /* #32: @3 = (@2?@3:0) */
  w3  = (w2?w3:0);
  /* #33: @2 = (!@2) */
  w2 = (! w2 );
  /* #34: @2 = (@2?@1:0) */
  w2  = (w2?w1:0);
  /* #35: @3 = (@3+@2) */
  w3 += w2;
  /* #36: @0 = (@0-@3) */
  w0 -= w3;
  /* #37: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  return 0;
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_constr_h_0_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_constr_h_0_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_constr_h_0_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_constr_h_0_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_constr_h_0_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_constr_h_0_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_constr_h_0_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void tricycle_frenet_constr_h_0_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int tricycle_frenet_constr_h_0_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int tricycle_frenet_constr_h_0_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real tricycle_frenet_constr_h_0_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tricycle_frenet_constr_h_0_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* tricycle_frenet_constr_h_0_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tricycle_frenet_constr_h_0_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* tricycle_frenet_constr_h_0_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int tricycle_frenet_constr_h_0_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 8;
  if (sz_w) *sz_w = 18;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
